### ISSUE TITLE
[KORREKTUR]: Firefox til Android og Focus til Android - Deadline 6. februar

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1002]
https://pontoon.mozilla.org/da/firefox-for-android/all-resources/?status=unreviewed&string=237831
https://pontoon.mozilla.org/da/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?status=unreviewed&string=237872

**Comment by jakobkappel** [comment]
Jeg har gemt alle uden rettelser - der var nemlig ikke noget at rette :)
