### ISSUE TITLE
[KORREKTUR]: Tekst om Brave

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1005]
https://pontoon.mozilla.org/da/mozillaorg/en/firefox/browsers/compare/brave.ftl/?status=missing&string=212608

**Comment by Joergen** [comment]
Jeg har lavet ændringsforslag: https://pontoon.mozilla.org/da/mozillaorg/en/firefox/browsers/compare/brave.ftl/?status=missing&string=212606

Jeg er ikke med på oversættelsen af "portability" med "understøttede enheder" i denne streng: https://pontoon.mozilla.org/da/mozillaorg/en/firefox/browsers/compare/brave.ftl/?status=missing&search=compare-brave-compare-brave-to-the-firefox&string=212606
"Password management" og "Master Password" er underpunkter. Se tabellen her: https://www-dev.allizom.org/da/firefox/browsers/compare/brave/

Dele af sidens indhold (bl.a "Portability") er i filen https://pontoon.mozilla.org/da/mozillaorg/en/firefox/browsers/compare/shared.ftl/?string=212664
Jeg har lavet forslag til nogle af strengene i den fil.
 "Portability" https://pontoon.mozilla.org/da/mozillaorg/en/firefox/browsers/compare/shared.ftl/?status=missing&string=212649

**Comment by jakobkappel** [comment]
Tak for de gode forslag, @Joergen 

Ift. "portability" ved jeg ikke, hvordan vi kan løse det. "Portabilitet" findes åbenbart på dansk ([DDO](https://ordnet.dk/ddo/ordbog?query=portabilitet&tab=for)), men jeg har aldrig stødt på det. Men hér handler det vel om, at browseren fungerer i mange forskellige operativsystemer og/eller på forskellige enheder.

**Comment by Joergen** [comment]
Jeg kendte heller ikke det danske ord "portabilitet". (Min stavekontrol gør heller ikke). Men jeg synes jeg godt vi kan bruge det ord.

**Comment by jakobkappel** [comment]
Ja, lad os gøre det. Jeg kan se, at de fleste sprog (jeg kan stave mig gennem) har gjort det samme.
