### ISSUE TITLE
[KORREKTUR]: Strenge til Firefox (Deadline: 27/2)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1006]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=missing&string=237941

@Joergen, har du læst om ændringen ift. standard-søgetjenester?

**Comment by Joergen** [comment]
@jakobkappel Det ved jeg ikke. Mener du at teste Bing i en Firefox-undersøgelse?

**Comment by Joergen** [comment]
Nu nåede jeg frem til strengen "Your default search engine has been changed....". Jeg tror det drejer sig om brugervalgte søgetjenester, som måske ikke længere kompatible med FF.

**Comment by jakobkappel** [comment]
> Nu nåede jeg frem til strengen "Your default search engine has been changed....". Jeg tror det drejer sig om brugervalgte søgetjenester, som måske ikke længere kompatible med FF.

Det var lige præcis dén, jeg spekulerede over. For jeg forstår ikke rigtigt, hvordan en søgetjeneste ikke længere kan være kompatibel. I langt de fleste søgetjenester handler det jo bare om at kyle et parameter på URLen (?q=søgning).

Af en eller anden grund kan jeg ikke få lov til at se den pågældende bug (1748923). Nå ja, vi må se, hvad der sker.
