### ISSUE TITLE
[KORREKTUR]: Mozilla.org/en/firefox/browsers/compare/shared.ftl

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1007]
Strenge til diverse sider med sammenligninger af Firefox og andre browsere, bl.a Brave:

https://pontoon.mozilla.org/da/mozillaorg/en/firefox/browsers/compare/shared.ftl/?status=unreviewed&string=212664

https://www-dev.allizom.org/da/firefox/browsers/compare/brave/

**Comment by jakobkappel** [comment]
Jeg har slettet et enkelt komma - ellers er alt helt som det skal være :)
