### ISSUE TITLE
[KORREKTUR]: To strenge til donate

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1008]
https://pontoon.mozilla.org/da/mozilla-donate-website/all-resources/?status=unreviewed&string=242385

Jeg har foreslået "mindste beløb" fremfor "minimumsbeløb", da jeg synes, det er lidt nemmere at læse. Men det er virkeligt i småtings-afdelingen.

**Comment by Joergen** [comment]
Ændret
