### ISSUE TITLE
Bøvl med Pontoon

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1009]
Jeg forsøgte at oversætte strengen

> At { -brand-name-firefox }, we have a huge number of dedicated users who appreciate our steadfast dedication to online privacy. For example, the latest version of { -brand-name-firefox } includes a feature called Enhanced Tracking Protection (ETP) which is turned on by default for all users worldwide. ETP blocks over 2,000 trackers, including social trackers from companies like { -brand-name-facebook }, { -brand-name-twitter }, and LinkedIn. It also has an integrated feature called <a { $attrs }>{ -brand-name-firefox-monitor }</a> that automatically notifies you if your password has been breached or needs to be updated. In addition to these protections, Private Browsing mode in { -brand-name-firefox } automatically deletes your browsing information such as history and cookies, leaving no trace after you finish your session.

med

> { -brand-name-firefox } har et stort antal engagerede brugere, der sætter pris på {- brand-name-mozilla }s  dedikation til at beskytte deres privatliv på nettet. For eksempel indeholder den nyeste version af { -brand-name-firefox } en funktion ved navn Udvidet beskyttelse mod sporing, der er slået til som standard for alle brugere. Funktionen blokerer over 2000 sporingsmekanismer, inklusive sporing fra sociale medier som { -brand-name-facebook }, { -brand-name-twitter } og LinkedIn. { -brand-name-firefox } indeholder også <a { $attrs }>{ -brand-name-firefox-monitor }</a>, der automatisk giver dig besked, hvis nogen af dine adgangskoder er blevet lækkede eller trænger til at blive opdateret. Udover disse funktioner sletter Privat browsing-tilstand i { -brand-name-firefox } automatisk informationer om din adfærd på nettet som din historik og dine cookies. På dén måde er der ingen spor tilbage, når du slutter sessionen.

Det giver denne besked: "Expected a character from range: "a-zA-Z""

@Joergen, er du stødt på noget lignende - og hvad var løsningen?

**Comment by Joergen** [comment]
Jeg kan ikke finde den pågældende engelske streng på Pontoon! Jeg kan finde to næsten ens strenge, der ligner den. https://pontoon.mozilla.org/da/mozillaorg/en/firefox/browsers/compare/chrome.ftl/?search=%3Ca+%7B+%24attrs+%7D%3E%7B+-brand-name-firefox-monitor+%7D%3C%2Fa%3E&string=212821
Fælles for den engelske og den danske streng, du angiver i dette issue er, at der mangler et afsluttende  `</a>` i begge strenge.
`<a { $attrs }>{ -brand-name-firefox-monitor }</a>`

**Comment by jakobkappel** [comment]
Den er her: https://pontoon.mozilla.org/da/mozillaorg/en/firefox/browsers/compare/chrome.ftl/?status=missing&string=212821

Github ser ud til at smide </a> ud, for det er på Pontoon.

Det kan også være fordi, at Pontoon forventer et ord som det første fremfor en variabel. Eller også er det fordi, jeg har brugt en variabel, der ikke er i originalen. Jeg prøver lidt forskelligt, når jeg har tid. Jeg blev bare doven og ville lige tjekke, om du havde fået samme fejl på et tidspunkt.

**Comment by Joergen** [comment]
> Github ser ud til at smide ud, for det er på Pontoon.

Åh ja. Det burde jeg have regnet ud. Jeg måtte også bruge kode-formatering i mit indlæg for at få  vist `<a { $attrs }>{ -brand-name-firefox-monitor }</a>`

I den danske tekst har du en forekomst af {- brand-name-mozilla }, som ikke findes i den engelske tekst. Den ser ud til at være fejlformateret. Hvis du vil bruge den, skal den nok se sådan ud: { -brand-name-mozilla }. Den skal starte med {mellemrumbindestreg. Ikke {bindestregmellemrum

**Comment by jakobkappel** [comment]
Hov, ja. Godt set. Tak!

Den rigtige formatering af variablen giver dog fejlbeskeden "Obsolete term reference: -brand-name-mozilla", hvilket ikke er så meget bedre. Så det bliver "vores" i stedet.
