### ISSUE TITLE
[KORREKTUR]: Nye strenge til Focus

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1010]
https://pontoon.mozilla.org/da/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?status=unreviewed&string=242843

Jeg har desværre overset deadline - men bedre sent end slet ikke.

**Comment by Joergen** [comment]
Jeg tror at de seneste strenge blev tilgængelige for oversættelse for 11 dage siden. Det er et par dage før deadline!

**Comment by jakobkappel** [comment]
Ja, så er det heller ikke nemt. Men det kan være, at de nye strenge først kommer i den næste version? Nu får vi se :)

**Comment by Joergen** [comment]
To ændringsforslag: https://pontoon.mozilla.org/da/focus-for-android/all-resources/?status=unreviewed&string=242847

**Comment by jakobkappel** [comment]
> To ændringsforslag: https://pontoon.mozilla.org/da/focus-for-android/all-resources/?status=unreviewed&string=242847

Tak. Jeg lærer åbenbart aldrig dét med klik/tryk...
