### ISSUE TITLE
[KORREKTUR]: 34 nye strenge til Firefox (Deadline: 27. marts)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1011]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=missing&string=243099

**Comment by Pokersut** [comment]
Jeg har lavet et par ændringsforslag til strengene med "theme settings", men jeg kan ikke gennemskue konteksten, så måske passer de ikke.

**Comment by Joergen** [comment]
Tooltippet vises, når man peger på Nightly theme.
![match_your](https://user-images.githubusercontent.com/3466269/159280305-9a05af61-7626-4a24-86df-00dd31c182b7.png)

**Comment by jakobkappel** [comment]
De passer i hvert fald bedre end mine forslag :) Jeg gemmer forslagene og lukker her.
