### ISSUE TITLE
[KORREKTUR]: Mozilla.org/en/newsletter_form.ftl

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1012]
Seks strenge: https://pontoon.mozilla.org/da/mozillaorg/en/newsletter_form.ftl/?status=unreviewed&string=242782
De engelske strenge kan ses her: https://www-dev.allizom.org/en-US/
Klik i tekstfeltet .

**Comment by jakobkappel** [comment]
@Joergen Jeg er i tvivl om 

"Love the Web" > "Vild med internettet"

Den engelske streng må næsten være en opfordring, "Elsk internettet" - hvilket på dansk nok bliver lidt spøjst. 

Et alternativ kunne være "Vild med internettet?" Det er selvfølgelig ikke en opfordring, men resultatet bliver "Er du vild med internettet, så tilmeld dig hér for at hjælpe os med at beskytte det".

**Comment by Joergen** [comment]
@jakobkappel Jeg har også tænkt, at der manglede et ? i den streng.
Jeg tilføjer et, så det bliver "Vild med internettet?"
