### ISSUE TITLE
[KORREKTUR]: Artikel om nyheder i Firefox til iOS version 99

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1013]
https://support.mozilla.org/da/kb/nyheder-i-firefox-til-ios-version-99/review/240903

**Comment by Joergen** [comment]
Jeg har lavet en ny revision. Jeg har bl.a fjernet nøgleordene. Jeg plejer kun at bruge dem, når den engelske artikel bruger dem- Se endvidere https://support.mozilla.org/da/kb/brug-af-nogleord-til-soegerangering Jeg har formindsket billedet, så det ikke er for stort til en mobil.

**Comment by jakobkappel** [comment]
Det lyder godt - jeg kigger på din revision.

Min beta-version er ikke inkluderet i det omtalte eksperiment, så vi må desværre finde os i, at skærmbilledet ikke er med dansk tekst.
