### ISSUE TITLE
Mærkelig sætning på https://commonvoice.mozilla.org/da/listen

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1023]
![billede](https://user-images.githubusercontent.com/3586612/166686650-d175e757-342b-4e01-bd1b-3d6bfb636d04.png)

https://pontoon.mozilla.org/da/common-voice/web/locales/en/messages.ftl/?search=udtalte+de&string=179054

**Comment by Pokersut** [comment]
Mon ikke det er et kønsneutralt "they"? Jeg foreslår, at vi laver en passiv-konstruktion i stedet: "Blev sætningen udtalt korrekt?"

**Comment by jakobkappel** [comment]
Fin løsning - men jeg er lidt utryg ved "korrekt udtalt", da folk jo kan have 117 holdninger til, hvad det så betyder.

Måske "Blev sætningen læst korrekt op"?

**Comment by Pokersut** [comment]
Ja, det er nok bedre!

**Comment by peterleth1** [comment]
Tak!
