### ISSUE TITLE
[KORREKTUR]: Firefox til iOS - Deadline 22. maj

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1025]
8 strenge: https://pontoon.mozilla.org/da/firefox-for-ios/firefox-ios.xliff/?status=unreviewed&string=243960

**Comment by jakobkappel** [comment]
Det ser også godt ud, @Joergen 

En enkelt ting: 

"Vælg, hvad der skal vises som startsiden."

Af en eller anden grund synes jeg, at det lyder mere korrekt i ubestemt form: "Vælg, hvad der skal vises som startside."

**Comment by Joergen** [comment]
Ændret.
