### ISSUE TITLE
[KORREKTUR]: 8 nye strenge til Firefox (Deadline: 22. maj)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1026]
(https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=244511)

**Comment by Joergen** [comment]
Jeg har lavet lidt ændringsforslag. "ancestor" -> "overordnet"? Vi plejer at oversætte "parent" med "forælder".
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=244508

**Comment by jakobkappel** [comment]
> Jeg har lavet lidt ændringsforslag. "ancestor" -> "overordnet"? Vi plejer at oversætte "parent" med "forælder". https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=244508

Ja, "forælder" er lidt unøjagtigt. Men jeg kom til at kigge på nogle af de andre sprog. Hvad med "Klik på overordnet element"? Så er det mere tydeligt, hvad der er på spil.

**Comment by Pokersut** [comment]
Plejer vi at bruge det engelske ord "style sheet"? Der findes det danske ord "stilark", som jeg egentlig synes, er meget fint - men det er måske for ukendt?

Hvis vi bruger "style sheet", så synes jeg, vi skal sammenskrive det - altså "stylesheet".

**Comment by Joergen** [comment]
Jeg har lavet lidt ændringsforslag. "ancestor" -> "overordnet"? Vi plejer at oversætte "parent" med "forælder".
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=244508

> > Jeg har lavet lidt ændringsforslag. "ancestor" -> "overordnet"? Vi plejer at oversætte "parent" med "forælder". https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=244508
> 
> Ja, "forælder" er lidt unøjagtigt. Men jeg kom til at kigge på nogle af de andre sprog. Hvad med "Klik på overordnet element"? Så er det mere tydeligt, hvad der er på spil.

Ja, det er visk ok.

**Comment by Joergen** [comment]
> Plejer vi at bruge det engelske ord "style sheet"? Der findes det danske ord "stilark", som jeg egentlig synes, er meget fint - men det er måske for ukendt?
> 
> Hvis vi bruger "style sheet", så synes jeg, vi skal sammenskrive det - altså "stylesheet".

Jeg kan ikke finde en eneste forekomst af "stilark" i de danske oversættelser. Jeg har på fornemmelsen, at vi har diskuteret brugen af "stilark" vs. "style sheet" en gang for længe siden.

**Comment by jakobkappel** [comment]
> Plejer vi at bruge det engelske ord "style sheet"? Der findes det danske ord "stilark", som jeg egentlig synes, er meget fint - men det er måske for ukendt?
> 
> Hvis vi bruger "style sheet", så synes jeg, vi skal sammenskrive det - altså "stylesheet".

Ja, vi plejer at bruge "style sheet" - se https://transvision.mozfr.org/?recherche=style+sheet&repo=gecko_strings&sourcelocale=en-US&locale=da&search_type=strings 

Strenge med ordet er nemlig henvendt til udviklere, så det giver mening at holde de fleste fagudtryk på engelsk for at gøre det nemmere at finde hjælp via søgetjenester. Hvilket vi ganske rigtigt havde en diskussion om engang i tidernes morgen. 

Men der er altså et eller andet, der gør det mere rart at se på, når der står "stylesheet". Hvilket Den Danske Ordbog også synes. Og det kan de fleste søgetjenester sagtens håndtere. Så jeg synes fint at vi kan ændre til dét i de relevante strenge.

**Comment by Joergen** [comment]
Ok. Opretter du et nyt issue?

**Comment by jakobkappel** [comment]
> Ok. Opretter du et nyt issue?

Jeps
