### ISSUE TITLE
[KORREKTUR]: 24 nye strenge til Firefox - Deadline: 19. juni

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1031]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=244704

**Comment by Joergen** [comment]
Det er godt nok en langhåret omgang. Havde også svært ved at finde strengene i Nightly. Fx dem i about:profiling
Ændringsforslag: https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=244697

**Comment by jakobkappel** [comment]
Ja, de er ikke nemme... 

Tak for forslagene. Jeg har gemt alle undtagen dit forslag til "The main threads for the Nimbus experiments SDK", som jeg har lavet et nyt forslag til inspireret af dit: https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=244992
