### ISSUE TITLE
[KORREKTUR]: Thunderbird (deadline: 24. juni)

### ISSUE THREAD

**Issue by Pokersut** [MozillaDanmark/mozilla-dk#1039]
114 strenge: [https://pontoon.mozilla.org/da/thunderbird/all-resources/?status=unreviewed]

Jeg er lidt usikker på konteksten, de steder, hvor der snakkes om "message header". Har valgt at bibeholde "header" alle steder, men måske er der steder, hvor det skal være "overskrift"?

**Comment by Joergen** [comment]
Jeg har lavet ændringsforslag: https://pontoon.mozilla.org/da/thunderbird/all-resources/?status=missing&string=245311
Jeg tror det er rigtigt at bruge "header" i strengene. Den ene streng ligner en vi har i adressebogen i den nuværende version. Den anden streng med "Autocrypt header" er jeg ikke helt med på. Men der er ikke nogle overskrifter i TB.

**Comment by Pokersut** [comment]
Gode forslag - alle er godkendt.

**Comment by Joergen** [comment]
Jeg har ændret et af mine godkendte forlag tilbag til Mikkels forslag:
https://pontoon.mozilla.org/da/thunderbird/all-resources/?status=missing&string=245309
https://autocrypt.org/level1.html#the-autocrypt-header
