### ISSUE TITLE
[KORREKTUR]: Common Voice

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1040]
25 nye strenge: https://pontoon.mozilla.org/da/common-voice/web/locales/en/messages.ftl/?status=unreviewed&string=245024
Der er et nyt forslag til en allerede godkendt streng blandt strengene.

Nogle af strengene er live her: https://commonvoice.mozilla.org/da/about?tab=how-add-language#playbook

**Comment by jakobkappel** [comment]
Det ser fint ud, @Joergen 

Nu mangler der "bare" sætningerne fra #1029 - og dem ved jeg ikke rigtigt, hvad vi skal stille op med.
