### ISSUE TITLE
[KORREKTUR]: Mozilla.org

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1041]
2 strenge: https://pontoon.mozilla.org/da/mozillaorg/en/firefox/products.ftl/?status=unreviewed&string=224625
https://www-dev.allizom.org/en-US/firefox/products/

2 strenge: https://pontoon.mozilla.org/da/mozillaorg/en/firefox/set-as-default/landing.ftl/?status=unreviewed&string=246035
https://www-dev.allizom.org/en-US/firefox/set-as-default/

2 strenge: https://pontoon.mozilla.org/da/mozillaorg/en/mozorg/about/shared.ftl/?status=unreviewed&string=244396
https://www-dev.allizom.org/en-US/about/manifesto/details/

**Comment by Pokersut** [comment]
Alle godkendt.
