### ISSUE TITLE
[KORREKTUR]: Firefox Accponts

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1049]
62 strenge: https://pontoon.mozilla.org/da/firefox-accounts/all-resources/?status=unreviewed&string=247223
De fleste af strengene er uændret i oversættelserne. I de engelske strenge har man skiftet "verify" ud med "confirm".

**Comment by Pokersut** [comment]
To forslag, resten godkendt.

**Comment by Joergen** [comment]
Tak for det, @Pokersut
