### ISSUE TITLE
[KORREKTUR]: Firefox til Android - Deadline 11. september

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1053]
16 strenge: https://pontoon.mozilla.org/da/firefox-for-android/all-resources/?status=unreviewed&string=247827

**Comment by jakobkappel** [comment]
Det ser godt ud, @Joergen 

Jeg har et enkelt forslag: https://pontoon.mozilla.org/da/firefox-for-android/all-resources/?status=missing&string=247828.
