### ISSUE TITLE
[OVERSÆTTELSE]: Firefox Relay Add-on

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1057]
Oprindeligt brugte Mozilla begrebet "email alias". Det blev erstattet med "email mask". Jeg så på et tidspunkt meddelelsen "**Aliases are now masks**". Artiklen i vidensbasen på SUMO er også blevet ændret. Men man har ikke fjernet strengene med "alias" fra Pontoon. Der er ingen grund til at bruge tid på strengene, med "alias". Men de skal måske godkendes for at få den danske oversættelse med i udvidelsen.
Jeg har lavet forslag til de fleste af de manglende strenge.

**Comment by jakobkappel** [comment]
Det var da forvirrende...

Jeg kigger strengene igennem og ser, om jeg kan komme på nogle forslag til de sidste.

**Comment by jakobkappel** [comment]
@Joergen https://pontoon.mozilla.org/da/firefox-relay-add-on/all-resources/?status=missing&string=237533

Jeg kom til at lave forslag til nogle af de eksisterende strenge med "alias", så dér kan du bare gemme tidligere forslag - eller hvad du ny synes. Som du skriver ovenfor, så bliver de sikkert ikke vist nogen steder alligevel.

**Comment by Joergen** [comment]
Jeg lukker issuet, men tjekker udvidelsen, når den bliver opdateret med de danske strenge.
