### ISSUE TITLE
For lang streng i Firefox iOS

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1060]
<img width="375" alt="iPhone 8-Onboarding-2" src="https://user-images.githubusercontent.com/3586612/191682179-8c14f028-b1d8-43d4-8e85-29bd768661c0.png">

Det er ikke nemt at se den nederste knap ("Spring over"). 

Beta-versionen blev udgivet i nat, så jeg håber, at vi kan nå at få ændringer med.

---
Løsning 1:
"Hop fra telefonen til computeren og tilbage" >
"Fra telefonen til computeren og tilbage"

Løsning 2:
"Hent faneblade og adgangskoder fra dine andre enheder for at fortsætte, hvor du slap." > 
"Hent faneblade og adgangskoder fra andre enheder for at fortsætte, hvor du slap."

Løsning 3:
???

https://pontoon.mozilla.org/da/firefox-for-ios/firefox-ios.xliff/?search=Hop+fra+telefonen+til+computeren+og+tilbage&string=247583
https://pontoon.mozilla.org/da/firefox-for-ios/firefox-ios.xliff/?search=Hent+faneblade+og+adgangskoder+fra+dine+andre+enheder+for+at+forts%C3%A6tte,+hvor+du+slap.&string=247580

**Comment by Joergen** [comment]
Både den tyske og den franske oversættelse skaber samme problem.
Ingen af dine to nye forslag er kortere end de engelske strenge. Spørgsmålet er, om dine nye forslag er korte nok.
"Hop from phone to laptop and back"
"Fra telefon til computer og tilbage" er lidt kortere end dit nye forslag. Det ser også kortere ud end den engelske streng, når jeg skriver den her. Men den er to tegn længere end den engelske!
"Hop fra telefon til computer og tilbage" er en anelse længere end den engelske

Hop from phone to laptop and back (33 tegn)
Hop fra telefonen til computeren og tilbage (43 tegn)
Hop fra telefon til computer og tilbage (39 tegn) <- Nyt forslag.
Fra telefon til computer og tilbage (35  tegn)

Nedenstående har 19 tegn i hver linje.
Hop fra telefon til
computer og tilbage

**Comment by jakobkappel** [comment]
Jeg prøver med "Fra telefon til computer og tilbage" og så må vi se, om den dukker op i den næste beta-version.

**Comment by jakobkappel** [comment]
> Jeg prøver med "Fra telefon til computer og tilbage" og så må vi se, om den dukker op i den næste beta-version.

Det gjorde den ikke. 

Jeg nævner det for Delphine, så hun kan prøve at få udviklerne til at hive de seneste strenge ind ved opdatering.

**Comment by jakobkappel** [comment]
https://github.com/mozilla-l10n/firefoxios-l10n/issues/166
