### ISSUE TITLE
[KORREKTUR]: Focus til Android

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1062]
16 strenge: https://pontoon.mozilla.org/da/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?status=unreviewed&string=261480

**Comment by jakobkappel** [comment]
@Joergen Et enkelt forslag: https://pontoon.mozilla.org/da/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?status=unreviewed&string=261481
