### ISSUE TITLE
[KORREKTUR]: En haster til Firefox Accounts (Deadline - 14. oktober)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1066]
> Today a few strings were exposed to Pontoon, one of those strings is a fix to a high-impact issue within the checkout flow. The localization for the string below will be pushed on October 14. Please prioritize the translation of the following string over the others, as we would like to push this fix for our localized languages as soon as possible. File: main.ftl ID: payment-confirm-with-legal-links-static

https://pontoon.mozilla.org/da/firefox-accounts/all-resources/?status=unreviewed&string=262208

Jeg tog resten af de manglende også, nu jeg var i gang: 
https://pontoon.mozilla.org/da/firefox-accounts/all-resources/?status=unreviewed&string=262211

**Comment by Joergen** [comment]
Jeg har lavet et ændringsforslag, der ligner de oprindelige (nu udgåede) strenge mere. Bl.a "tjenestevilkårene" og "privatlivspolitikken" med lille begyndelsesbogstav og "autoriserer hermed" -> "giver hermed tilladelse til".
https://pontoon.mozilla.org/da/firefox-accounts/all-resources/?status=unreviewed&string=262208

**Comment by jakobkappel** [comment]
Ja, det virker jo meget bedre - tak for forslaget og hurtig udrykning :)
