### ISSUE TITLE
[KORREKTUR]: Strenge til ny side om MDN Plus

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1067]
https://pontoon.mozilla.org/da/mozillaorg/en/firefox/whatsnew/whatsnew-developer-mdnplus.ftl/?status=unreviewed&string=246036

https://www-dev.allizom.org/da/firefox/102.0a2/whatsnew/

**Comment by Joergen** [comment]
Et ændringsforslag: https://pontoon.mozilla.org/da/mozillaorg/en/firefox/whatsnew/whatsnew-developer-mdnplus.ftl/?status=unreviewed&string=246019

**Comment by jakobkappel** [comment]
> Et ændringsforslag: https://pontoon.mozilla.org/da/mozillaorg/en/firefox/whatsnew/whatsnew-developer-mdnplus.ftl/?status=unreviewed&string=246019

Det var godt, at du fangede fejlen - nogle gange går det vist liiige hurtigt nok :)
