### ISSUE TITLE
[KORREKTUR]: Side om Firefox på Chromebooks

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1068]
https://pontoon.mozilla.org/da/mozillaorg/en/firefox/browsers/chromebook.ftl/?status=unreviewed&string=216019

https://www-dev.allizom.org/da/firefox/browsers/chromebook/

Nu jeg ser siden: 
Det ser mærkeligt ud med "Hent Firefox _Browser_..." Jeg ved godt, at det er sådan, originalen ser ud - men alligevel.

**Comment by Joergen** [comment]
Nej, kønt er det ikke.
