### ISSUE TITLE
[KORREKTUR]: 35 nye strenge til Firefox (Deadline: 6. november)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1071]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=missing&string=263125

**Comment by Joergen** [comment]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=263122

**Comment by jakobkappel** [comment]
Det er godt, at du er en effiktiv korrekturlæser ;) Sikke nogle dumme fejl, jeg har lavet...
