### ISSUE TITLE
[KORREKTUR]: 9 nye strenge til Firefox iOS (Deadline - 4/12)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1075]
https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=missing&string=263510

**Comment by Joergen** [comment]
Jeg synes, der kommer flere og flere reklamestrenge i produkterne.

**Comment by jakobkappel** [comment]
Ja, det gør der. Det kan være, at de har lavet nogle undersøgelser, der peger på at nye brugere ikke opdager de omtalte funktioner?
