### ISSUE TITLE
[KORREKTUR]: Ny side, "Hvad er en browser?"

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1078]
https://pontoon.mozilla.org/da/mozillaorg/en/firefox/browsers/history/what-is-a-browser.ftl/?status=unreviewed&string=217821

https://www-dev.allizom.org/da/firefox/browsers/what-is-a-browser/

**Comment by Pokersut** [comment]
En ordentlig omgang amerikansk salgs-lingo! 

Rigtig mange gode og kreative løsninger, men jeg har tilladt mig at lave en række bud på alternative formuleringer, som jeg synes, ligger lidt bedre i munden.

**Comment by jakobkappel** [comment]
@Pokersut Ja, der er skruet op til 11 på alle sprogknapperne!

Mange tak for forslagene - de er rigtigt gode.

Jeg har godkendt de fleste, bortset fra tre, hvor jeg har tilføjet nogle ændringsforslag til dine: https://pontoon.mozilla.org/da/mozillaorg/en/firefox/browsers/history/what-is-a-browser.ftl/?status=unreviewed&string=217829 

De to første har en anden oversættelse af "amazed" (som i "Det er vildt imponerende, at det kan lade sig gøre...") og den sidste har "motiver" i stedet for "bevæggrunde", som jeg synes begynder at se noget gammeldags ud.

**Comment by Pokersut** [comment]
Meget bedre med "imponerende" - og du har nok ret i, at "motiver" er mere tidssvarende end "bevæggrunde". Alle godkendt!
