### ISSUE TITLE
[KORREKTUR]: 5 nye strenge til Firefox iOS

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1081]
https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=missing&string=266434

Deadline er angivet til 4/12, men jeg tror at disse strenge gælder en kommende deadline. Ellers er de kommet til meget sent.

**Comment by Joergen** [comment]
Jeg tror også, at de er til en senere udgivelse.
