### ISSUE TITLE
[KORREKTUR]: 6 nye strenge til Terminology

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1083]
https://pontoon.mozilla.org/da/terminology/all-resources/?status=unreviewed&string=266336

Jeg kiggede lidt på, hvordan andre sprog håndterer nonprofit/non-profit. Måske skulle vi gøre noget lignende og ændre til "almennyttig"?

**Comment by Joergen** [comment]
Jeg foretrækker nonprofit/non-profit. 
Jeg synes ikke, at oversættelse til "almennyttig" dækker https://ordnet.dk/ddo/ordbog?query=almennyttig
https://ordnet.dk/ddo/ordbog?query=nonprofit-

**Comment by jakobkappel** [comment]
> Jeg foretrækker nonprofit/non-profit. Jeg synes ikke, at oversættelse til "almennyttig" dækker https://ordnet.dk/ddo/ordbog?query=almennyttig https://ordnet.dk/ddo/ordbog?query=nonprofit-

Det gør jeg faktisk også, nu jeg har set ordbogsopslagene. Men det er da irriterende, at dansk ikke har noget godt ord med samme betydning,
