### ISSUE TITLE
Oversættelse af "privately"

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1084]
Jeg er stødt på et par strenge til https://monitor.firefox.com/, som jeg har meget svært ved at finde på gode oversættelser til: 

- Use the internet privately with a VPN [...]
- A VPN can hide your real IP address so you can use the internet privately.

Det virker ikke så godt med "privat", da det er nemt at læse som "i modsætning til dit arbejdsliv". 

Jeg kan ikke komme på noget bedre end at skrive helt om med "Beskyt din identitet på internettet ved at bruge en VPN", "... så du kan bruge internettet uden at afsløre din identitet." eller i dén retning. 

Der er også den gamle streng "Browse faster, privately", som er oversat "Brows hurtigere, privat". 

Har I andre nogen gode bud?

**Comment by Pokersut** [comment]
Jeg synes, det er nogle gode omskrivninger!

Ved ikke helt, hvad man skal gøre med den gamle streng. "Brows hurtigere og beskyt din identitet", måske?

**Comment by jakobkappel** [comment]
Så holder jeg mig til dem :)

Konteksten for den gamle streng handler ved nærmere eftersyn om funktionen 'privat browsing' (ikke VPN-tjenesten), så dér skal det nok oversættes anderledes - måske:

![billede](https://user-images.githubusercontent.com/3586612/206154904-1f5795e2-04c8-41a3-b758-b983bdff8011.png)


Jeg fik desuden øje på: 

![billede](https://user-images.githubusercontent.com/3586612/206154225-1d17a365-7bf7-4ee3-b1db-fe9828de2163.png)

Dér bliver det ikke så pænt, hvis strengen knækkes over i to linjer. 

"Beskyt dit privatliv"?

**Comment by Pokersut** [comment]
Nej, her giver det fint mening med "privat browsing".

**Comment by jakobkappel** [comment]
Hov, jeg glemte at få lukket den hér...
