### ISSUE TITLE
[KORREKTUR]: Focus til Android - Deadline 8. januar

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1088]
10 strenge: https://pontoon.mozilla.org/da/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?status=unreviewed&string=267013

**Comment by Pokersut** [comment]
To forslag, resten godkendt.

Jeg kan ikke helt finde ud af, om jeg bryder mig om ordet "reduktion" - men jeg kan se, at norsk og svensk bruger noget tilsvarende. Måske ville "begrænsning" være bedre?

**Comment by Joergen** [comment]
Jeg kan endnu ikke se de pågældende strenge i Focus til Android. Men strenge magen til kan ses i Firefox til Android.
Længden af strengen "Reduktion af cookie-bannere" er to tegn kortere end "Begrænsning af cookie-bannere". Fx bliver strengen  "Udvidet beskyttelse mod sporing", der er to tegn længere end  "Begrænsning af cookie-bannere" trunkeret. Med brugen af ordet "reduktion" er vi på den sikre side.
