### ISSUE TITLE
[KORREKTUR]: En håndfuld nye strenge til Firefox - Deadline: 8/1

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1090]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed

**Comment by Joergen** [comment]
Et forslag nyt forslag til strengen med "request for". Forespørgsel -> Anmodning
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=267316

**Comment by jakobkappel** [comment]
> Et forslag nyt forslag til strengen med "request for". Forespørgsel -> Anmodning https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=267316

Det var en god idé - tak for den
