### ISSUE TITLE
[KORREKTUR]: Firefox til Android Deadline 5. februar 2023

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1094]
32 strenge: https://pontoon.mozilla.org/da/firefox-for-android/mozilla-mobile/fenix/app/src/main/res/values/strings.xml/?status=unreviewed&string=267998

Vi plejer at oversætte "pop-ups" med "pop op-vinduer". Men jeg synes ikke brugen af "vinduer" er velegnet på en telefon. Jeg synes heller ikke, at der er tale om vinduer i gammeldags forstand, da der er tale om cookie-anmodninger.

**Comment by Pokersut** [comment]
"Pop up-beskeder", måske?

**Comment by Joergen** [comment]
Hvad siger du @jakobkappel ? Der er lignende strenge i Firefox til computer.

**Comment by jakobkappel** [comment]
> 

Jeg synes, at "pop op-beskeder" virker rigtigt fint

**Comment by jakobkappel** [comment]
Det ser fint ud, @Joergen 

Fire forslag til rettelser: https://pontoon.mozilla.org/da/firefox-for-android/all-resources/?status=unreviewed&string=267690

**Comment by Joergen** [comment]
Tak for det, @jakobkappel
