### ISSUE TITLE
[KORREKTUR]: Focus til Android - Deadline 5. februar 2023

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1096]
5 strenge: https://pontoon.mozilla.org/da/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?status=unreviewed&string=268150

**Comment by jakobkappel** [comment]
@Joergen, et enkelt forslag: https://pontoon.mozilla.org/da/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?status=unreviewed&string=268150

**Comment by Joergen** [comment]
Tak for det.
