### ISSUE TITLE
[KORREKTUR]: 45 strenge tli Firefox (Deadline - 5. februar)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1097]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=268159

**Comment by Joergen** [comment]
Lidt ændringsforslag: https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=268176

**Comment by jakobkappel** [comment]
Tak for hjælpen, @Joergen . 

Jeg har føjet "Pop-up" til [ordlisten](https://github.com/MozillaDanmark/mozilla-dk/wiki/Ordliste),. 

Strengen med"Used" er jeg ikke sikker på, at jeg helt har fattet. Er det for at gøre opmærksom på, at en (engangs-)adgangskode allerede er brugt (og ikke kan bruges igen) - eller at en gemt adgangskode er blevet autofyldt mindst én gang? I det første tilfælde er "brugt" god, i det sidste synes jeg, at "anvendt" virker bedre. 

Ift. "læsetilladelse" synes jeg, at det er så tilpas usædvanligt et ord, at en bindestreg burde hjælpe folk, der ikke er så gode til at læse. Men det er gætværk. 

Det er forresten en sær sætning; det må vel være en bruger(gruppe) tilknyttet filen, der ikke har tilladelse til at læse den?

**Comment by Joergen** [comment]
Strengen "Last Used" vises på siden about:logins. Det samme gør "Used". Den første vises i menuen "Sorter efter". Den er oversat med "Senest brugt". Den nye "Used vises i en tidslinje:

![Used](https://user-images.githubusercontent.com/3466269/215577712-243d22dd-ee1c-4fb8-bf72-c6c3d645ea03.png)

Lad os bruge "Anvendt" begge steder. https://pontoon.mozilla.org/da/firefox/browser/browser/aboutLogins.ftl/?status=unreviewed&string=200701

Mht. "Selected file does not have read permission", så er den ikke letforståelig.  En søgning efter den pågældende ordlyd giver også kun et resultat (udover strengen selv). Måske bliver den streng ændret på et tidspunkt, så den bliver mere forståelig.

**Comment by jakobkappel** [comment]
> Strengen "Last Used" vises på siden about:logins. Det samme gør "Used". Den første vises i menuen "Sorter efter". Den er oversat med "Senest brugt". Den nye "Used vises i en tidslinje:
> 
> ![Used](https://user-images.githubusercontent.com/3466269/215577712-243d22dd-ee1c-4fb8-bf72-c6c3d645ea03.png)
> 
> Lad os bruge "Anvendt" begge steder. https://pontoon.mozilla.org/da/firefox/browser/browser/aboutLogins.ftl/?status=unreviewed&string=200701

Ok, så giver det hele mening. Jeg godkender lige de sidste forslag, så.
