### ISSUE TITLE
[KORREKTUR]: En stak strenge til https://monitor.firefox.com/

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1098]
https://pontoon.mozilla.org/da/firefox-monitor-website/all-resources/?status=unreviewed&string=267701

Test-site: https://monitor-localization.herokuapp.com/

**Comment by Pokersut** [comment]
Har lavet et par alternative forslag til nogle af strengene - og rettet en enkelt "læk" i intetkøn til fælleskøn, da det (endnu) er det korrekte.

**Comment by jakobkappel** [comment]
Gode forslag - tak for hjælpen, @Pokersut 

Det er virkeligt spændende (og rodet) med ords køn. Især når samme kombination af bogstaver bliver brugt til forskellige ord, der kun adskiller sig fra hinanden ved at have forskellige køn (lem, los osv.) Godt at man allerede kan dansk og ikke skal til at lære det...
