### ISSUE TITLE
[KORREKTUR]: 6 strenge til Firefox (Deadline: 5. marts)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1103]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=268494

@Joergen, jeg kan se, at du allerede er gået i gang med at kigge på forslagene. Jeg er meget i tvivl om ordlyden på Glean-strengene - de ruller ikke så let af tungen, for nu at sige det pænt. Men de engelske er også noget knudrede...

**Comment by Joergen** [comment]
Ja, de strenge er ikke ligefrem lette. De bliver ikke nemmere af, at de refererer til foregående felter/rullelister/knapper/afkrydsningsfelter i selvsamme liste.

2 forslag: https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=268512

**Comment by Joergen** [comment]
Jeg har set de danske strenge i Nightly (about:glean), ændret et af mine forslag og lavet yderligere et forslag:

3 forslag: https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=268514

**Comment by jakobkappel** [comment]
Gode forslag, tak for dem :)
