### ISSUE TITLE
[KORREKTUR]: 15 strenge til Firefox

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1105]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=275911

**Comment by Joergen** [comment]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=275995

Oversat en nyligt tilkommet streng + Lavede ændringsforslag til oversættelse af "Case sensitive" - også i et par ældre godkendte strenge.

**Comment by jakobkappel** [comment]
@Joergen Det er altså lidt farligt med de dér automatiske forslag, hvis det første er forkert og man har travlt. Godt at du er vågen :)
