### ISSUE TITLE
[KORREKTUR]: Strenge til diverse Mozilla.org-sider

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1106]
2 strenge: https://pontoon.mozilla.org/da/mozillaorg/en/firefox/new/desktop.ftl/?status=unreviewed&string=268339
Strengene er en del af sidens beskrivelse. https://www-dev.allizom.org/en-US/firefox/new/

2 manglende strenge: https://pontoon.mozilla.org/da/mozillaorg/en/firefox/browsers.ftl/?status=missing&string=267248
Her har jeg et problem med oversættelse af "Enterprise". Jeg har fundet to andre forekomster, hvor det er "oversat" med "Enterprise", med det er brand-navne. "Firefox Enterprise" og "Enterprise".
Strengene er sidens titel og beskrivelse. https://www-dev.allizom.org/en-US/firefox/browsers/

**Comment by jakobkappel** [comment]
> 2 manglende strenge: https://pontoon.mozilla.org/da/mozillaorg/en/firefox/browsers.ftl/?status=missing&string=267248 Her har jeg et problem med oversættelse af "Enterprise". Jeg har fundet to andre forekomster, hvor det er "oversat" med "Enterprise", med det er brand-navne. "Firefox Enterprise" og "Enterprise". Strengene er sidens titel og beskrivelse. https://www-dev.allizom.org/en-US/firefox/browsers/

"Til virksomheder"?

**Comment by Joergen** [comment]
https://pontoon.mozilla.org/da/mozillaorg/en/firefox/new/desktop.ftl/?status=unreviewed&string=268339
https://pontoon.mozilla.org/da/mozillaorg/en/firefox/browsers.ftl/?status=unreviewed&string=267248

**Comment by Joergen** [comment]
<del>https://pontoon.mozilla.org/da/mozillaorg/en/mozorg/mission.ftl/?status=unreviewed&string=276517<del/>

**Comment by Pokersut** [comment]
To alternative forslag - der går lidt på kompromis med de engelske formuleringer til fordel for øget læsbarhed på dansk. Måske for meget?

**Comment by Joergen** [comment]
Tak for det. Jeg har godkendt de to strenge.
