### ISSUE TITLE
[KORREKTUR]: 291 strenge til Thunderbird

### ISSUE THREAD

**Issue by Pokersut** [MozillaDanmark/mozilla-dk#1107]
https://pontoon.mozilla.org/da/thunderbird/all-resources/?status=unreviewed

Er usikker på, hvad "spaces" præcis refererer til, og jeg kan ikke huske, om vi har oversat det før?

**Comment by jakobkappel** [comment]
Det er oversat med "områder": https://hg.mozilla.org/projects/comm-l10n/annotate/default/da/mail/messenger/messenger.ftl#l199 (jeg har lavet et forslag til slåfejlene i linje 204). 

Du kan søge efter gamle oversættelser i et projekt ved at filtrere efter "All"

![billede](https://user-images.githubusercontent.com/3586612/223940731-ef43846d-aeae-4e80-957a-9e07f4f8499a.png)

Der er også værktøjet https://transvision.mozfr.org/, der har lidt mere avancerede indstillinger, mulighed for at søge på tværs af projekter og andre smarte ting. Dér skal du så lige huske at sætte "Target Locale" til "da" :)

**Comment by Joergen** [comment]
24 strenge med ændringsforslag: https://pontoon.mozilla.org/da/thunderbird/all-resources/?status=unreviewed&string=268310

Jeg har kigget brugerfladen igennem efter at have godkendt de fleste forslag, og lavet nogle små justeringer og ændringsforslag.
