### ISSUE TITLE
Korrektur: 5 nye strenge til Terminology

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1108]
https://pontoon.mozilla.org/da/terminology/all-resources/?status=missing&string=275855

Både "Privacy Notice" og "Privacy Policy" er (som tidligere) oversat "Privatlivspolitik", men måske skulle vi se, om vi kan finde på noget bedre. Jeg kan dog ikke lige komme på noget.

**Privacy Policy** handler om, hvordan personlige oplysninger generelt håndteres af Mozilla og i deres produkter

> _Noun. A statement that discloses the set of practices related to the handling of personal information by mozilla or its products. for example, mozilla's privacy policy can be found here: https://www.mozilla.org/en-us/privacy/. E.g. We also adhere to the practices outlined in the mozilla privacy policy for how we receive, handle and share information we collect from firefox._

**Privacy Notice** handler om, hvilke data der indsamles i produkter, hvordan de deles og hvorfor

> _Noun. Notice that explains what data s mozilla product collected, shared and why. it may also include additional information such as settings that can change how much is shared. one example is firefox browser's privacy notice which can be found here: https://www.mozilla.org/en-us/privacy/firefox/. E.g. In this privacy notice, we explain what data firefox shares and point you to settings to share even less. we also adhere to the practices outlined in the mozilla privacy policy for how we receive, handle and share information we collect from firefox._

**Comment by Joergen** [comment]
Korte forslag:
"Privacy Notice" -> "Privatlivserklæring" eller "Privatlivsmeddelelse"
"Privacy Policy" -> "Privatlivspolitik"

**Comment by jakobkappel** [comment]
> Korte forslag: "Privacy Notice" -> "Privatlivserklæring" eller "Privatlivsmeddelelse" "Privacy Policy" -> "Privatlivspolitik"

Jeg synes, at det bliver bedst med "-erklæring". Gider du at tjekke, om jeg har ramt de rigtige taster undervejs?
