### ISSUE TITLE
[KORREKTUR]: Mozilla.org/en/firefox/accounts.ftl

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1117]
13 strenge: https://pontoon.mozilla.org/da/mozillaorg/en/firefox/accounts.ftl/?status=unreviewed&string=276511
https://www-dev.allizom.org/en-US/firefox/accounts/

**Comment by jakobkappel** [comment]
Det ser rigtigt fint ud, @Joergen 

Jeg har et enkelt rettelsesforslag: 

https://pontoon.mozilla.org/da/mozillaorg/en/firefox/accounts.ftl/?status=unreviewed&string=276518
