### ISSUE TITLE
Ændring i popup ved fjernet login

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1119]
Nuværende:
![image](https://user-images.githubusercontent.com/3586612/230070749-4084f81f-799b-48a7-9797-b22de8f4a7d8.png)

Det bliver lidt tungt med "dette/Denne".

Forslag:
![image](https://user-images.githubusercontent.com/3586612/230070878-49f53f67-d0b1-4bcd-97be-a29f808705f8.png)

Ved nærmere eftertanke er det måske bedre at beholde "Fjern _dette_ login", så det er helt tydeligt, at der er tale om det login, man får vist.

**Comment by Joergen** [comment]
Jeg foretrækker den nuværende oversættelse. Jeg synes ikke den er "tung".

**Comment by jakobkappel** [comment]
Okay, så beholder vi den som den er :)
