### ISSUE TITLE
[KORREKTUR]: 14 nye strenge til Firefox iOS (Deadline - 30 .april)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1121]
https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed&string=278328

**Comment by Joergen** [comment]
Ændringsforslag til 2 strenge: https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed&string=278411
