### ISSUE TITLE
[KORREKTUR]: 5 nye strenge til Firefox iOS (Deadline - 30. april)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1125]
https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed&string=278847

**Comment by Joergen** [comment]
Jeg ved ikke helt med denne: 
https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed&string=278847

**Comment by jakobkappel** [comment]
> Jeg ved ikke helt med denne: https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed&string=278847

Næ, det kan jo fint være begge dele. Men jeg gætter alligevel på, at det er tips _om_ Firefox. For hvis det skulle være tips _fra_ Firefox, må det vel netop være tips om Firefox eller nogen af de andre Mozilla-ting (Monitor, VPN osv.) - og dér fungerer det vel også fint, hvis vi bruger "om"?

En mulig løsning, der ikke tager stilling til betydningen, kunne være "$variabel-tips". Men eftersom det er Firefox til iOS kunne vi måske være uheldige, at der kommer til at stå "Firefox til iOS-tips" - og det er ikke så lækkert.

**Comment by Joergen** [comment]
Jeg kan af en eller anden grund ikke godkende strenge. Når jeg klikker på "Approve",  står der "Approving", men strengen ser ikke ud til at være blevet godkendt.
Kan du ikke se, om du kan godkende den?
