### ISSUE TITLE
[KORREKTUR]: 45 strenge til Firefox (Deadline - 29. maj)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1126]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=279211

**Comment by Joergen** [comment]
6 forslag: https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=279211

**Comment by jakobkappel** [comment]
Tak, @Joergen Jeg skal altså huske at læse de dér kommentarer...

Det undrer mig også med strengen, der har "{ -fxaccount-brand-name(capitalization: "sentence") }" Men jeg kan se, at de fleste andre sprog også har smidt (capitalization...)' ud, og resultatet bør jo være fint på dansk også. 

Hvad siger du til https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=279370 i stedet for dit forslag? Jeg synes ofte, at 'bekræfte' eller 'godkende' bliver lidt nemmere at forstå end 'verficere'. Vi har tidligere oversat det lidt som vinden blæser (https://transvision.mozfr.org/?recherche=verification&repo=all_projects&sourcelocale=en-US&locale=da&search_type=strings), så måske var det tid til at få føjet det til ordlisten (med retningslinjer for, hvornår det ene eller det andet skal bruges).

**Comment by Joergen** [comment]
> Hvad siger du til https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=279370 i stedet for dit forslag? Jeg synes ofte, at 'bekræfte' eller 'godkende' bliver lidt nemmere at forstå end 'verficere'. Vi har tidligere oversat det lidt som vinden blæser (https://transvision.mozfr.org/?recherche=verification&repo=all_projects&sourcelocale=en-US&locale=da&search_type=strings), så måske var det tid til at få føjet det til ordlisten (med retningslinjer for, hvornår det ene eller det andet skal bruges).

Jeg lavede kun forslaget fordi du tidligere havde oversat "User verification" med "Bruger-autentificering". Jeg foretrækker helt klart "bekræfte" eller "godkende". Jeg retter de to tidligere godkendte strenge også og godkender alle tre. Kan vi overhovedet lave retningslinjer for, hvornår vi bruger "bekræfte" og hvornår vi bruger  "godkende"? Men vi kan forhåbentligt begrænse brugen til de to.

**Comment by jakobkappel** [comment]
Jamen, det var jo dumt af mig. Men nej, det er ikke helt så nemt at lave retningslinjer omkring det - kan jeg se, nu jeg kigger nærmere på strengene på transvision. Der er endda en enkelt streng, hvor "verifikation" ser ud til at være den rette løsning (https://hg.mozilla.org/projects/comm-l10n/file/default/da/mail/messenger/openpgp/openpgp.ftl#l696)
