### ISSUE TITLE
[KORREKTUR]: 44 nye (gamle) strenge til Firefox iOS (Deadline - 28. maj)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1127]
Der er blevet lavet noget, sådan at nogle gamle strenge er røget i svinget. 

Langt de fleste strenge er kopieret ind fra tidligere, og for en del af dem er der ændret på variabler. Ellers skulle der ikke  være så meget at korrekturlæse. 

https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed&string=279546

**Comment by Joergen** [comment]
Underligt - jeg har ikke modtaget mail vedrørende dette issue!

**Comment by Joergen** [comment]
Nu dukkede mailen op. To timer forsinket. Det samme gælder mails vedrørende issue  #1126 De var mere end to timer forsinket. Lad os håbe, at det var et midlertidigt glitch.

**Comment by jakobkappel** [comment]
> Nu dukkede mailen op. To timer forsinket. Det samme gælder mails vedrørende issue #1126 De var mere end to timer forsinket. Lad os håbe, at det var et midlertidigt glitch.

Det var da sært. Men jo, der har sikkert været en eller anden midlertidig fejl et sted.

**Comment by Joergen** [comment]
Et ændringsforslag: https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed&string=279555

**Comment by jakobkappel** [comment]
Perfekt, tak!
