### ISSUE TITLE
[KORREKTUR]: 14 nye strenge til Firefox (Deadline - 26. juni)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1135]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=missing&string=280350

**Comment by Joergen** [comment]
Jeg har lavet nogle ændringsforslag. Jeg kan ikke godkende resten før dette issue er løst: https://github.com/mozilla/pontoon/issues/2885

**Comment by Joergen** [comment]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=280900

**Comment by jakobkappel** [comment]
Perfekt. 

Men hvad siger du til https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=280900?

**Comment by Joergen** [comment]
https://transvision.mozfr.org/?recherche=codec&repo=all_projects&sourcelocale=en-US&locale=da&search_type=strings
https://www.microsoft.com/en-us/language/Search?&searchTerm=Codec&langID=142&Source=true&productid=0

Måske ændre nuværende forekomster af "kodeks" til "codecs"?

**Comment by Joergen** [comment]
https://dsn.dk/soeg/?soegeord=kodeks
https://en.wikipedia.org/wiki/Codec

**Comment by jakobkappel** [comment]
Der kan man bare se. Jeg føjer det til wiki'en og opretter et issue
