### ISSUE TITLE
[KORREKTUR]: 15 nye strenge til Firefox iOS (Deadline - 26. juni)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1136]
https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed&string=280825

**Comment by Joergen** [comment]
Samme problem med at godkende nogle af strengene her.

**Comment by Joergen** [comment]
https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed&string=280826
