### ISSUE TITLE
Forkert sprog i mail "Nyt login til Pontoon"

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1137]
![billede](https://github.com/MozillaDanmark/mozilla-dk/assets/3586612/b14b2d4a-bfdc-4fd1-a1cc-9a5bd03ff8b0)

Jeg ved ikke, om det er en central fejl eller noget, vi kan fikse.

**Comment by Joergen** [comment]
Jeg har indberettet problemet i november 2022 . 
https://github.com/mozilla/fxa/issues/14412

**Comment by jakobkappel** [comment]
> Jeg har indberettet problemet i november 2022 . [mozilla/fxa#14412](https://github.com/mozilla/fxa/issues/14412)

Jamen, så er der ikke andet for at vente noget mere på bedre tider. Men det er trods alt et fremskridt, at det nu er på græsk fremfor koreansk - det er jo lidt tættere på ;)
