### ISSUE TITLE
Ændre nuværende forekomster af 'kodeks*' til 'codec*'

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1138]
https://transvision.mozfr.org/?recherche=codec&repo=all_projects&sourcelocale=en-US&locale=da&search_type=strings
https://www.microsoft.com/en-us/language/Search?&searchTerm=Codec&langID=142&Source=true&productid=0

---

Begrundelse:  
https://dsn.dk/soeg/?soegeord=kodeks
https://en.wikipedia.org/wiki/Codec

**Comment by Joergen** [comment]
Jeg fandt én forekomst. https://pontoon.mozilla.org/da/all-projects/all-resources/?search=kodeks&string=151660
