### ISSUE TITLE
[KORREKTUR]: Thunderbird, 23 strenge

### ISSUE THREAD

**Issue by Pokersut** [MozillaDanmark/mozilla-dk#1160]
https://pontoon.mozilla.org/da/thunderbird/all-resources/?status=unreviewed

Der er vist ikke så mange ben i dem :-)

**Comment by Joergen** [comment]
Ændringsforslag: "Messages". Ændret oversættelse fra "Beskeder" til "meddelelser".
https://pontoon.mozilla.org/da/thunderbird/mail/messenger/about3Pane.ftl/?status=unreviewed&string=285842

**Comment by Pokersut** [comment]
Den glemmer jeg altid - tak 🙂
