### ISSUE TITLE
[KORREKTUR]/[OVERSÆTTELSE]: Firefox til Android - Deadline 15. oktober - 2023

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1161]
1 streng, jeg har problemer med at oversætte: https://pontoon.mozilla.org/da/firefox-for-android/mozilla-mobile/fenix/app/src/main/res/values/strings.xml/?string=285153

108 strenge: https://pontoon.mozilla.org/da/firefox-for-android/all-resources/?status=unreviewed&string=285503

**Comment by jakobkappel** [comment]
Nej, den er ikke nem. Jeg har lavet et (ikke vanvittigt elegant) forslag. Men det kan være, at du kan bruge det til at finde på noget bedre :)

Lidt andre forslag: https://pontoon.mozilla.org/da/firefox-for-android/all-resources/?status=unreviewed&string=285233

**Comment by Joergen** [comment]
Tak.
