### ISSUE TITLE
[KORREKTUR]: 18 strenge til Firefox (Deadline - 15. oktober)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1162]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=285878

**Comment by Joergen** [comment]
Indsat et par ? og godkendt.
https://pontoon.mozilla.org/da/firefox/browser/browser/newtab/asrouter.ftl/?string=285872
https://pontoon.mozilla.org/da/firefox/browser/browser/newtab/asrouter.ftl/?string=285865

**Comment by jakobkappel** [comment]
Tak - og god weekend, @Joergen :)
