### ISSUE TITLE
Hjælp til nørdet streng i Firefox (til deadline 12/11)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1166]
> Please note that you are using the Glean JS API by using the devtools console.
> This means the metric category and metric name are formatted in
> \<code>camelCase\</code> unlike in the Rust and C++ APIs.

Det er "metric category og "metric name", jeg ikke kan finde ud af. Kan det måske være "analyse-kategorien" og "...navnet"?

Jeg har lidt lyst til at finde på en dansk oversættelse af camelCase :D

**Comment by Joergen** [comment]
Har du tjekket about:glean i Nightly?

**Comment by Joergen** [comment]
Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1857543

**Comment by Joergen** [comment]
https://mozilla.github.io/glean/book/appendix/glossary.html

**Comment by jakobkappel** [comment]
Jeg har kigget lidt rundt. Men jeg ved stadig ikke rigtigt, hvad jeg skal gøre med "metric". 

Måske "analyse-resultat" - > "kategori for analyse-resultat" og "navn på analyse-resultat"?

**Comment by Joergen** [comment]
Dette er mit bedste bud:
`Bemærk, at når du bruger konsollen i udviklerværktøj, bruger du Glean JS-API'et.`
`Det betyder, at i modsætning til i Rust- og i C++-API'erne,`
`er mål-kategorier og mål-navne formateret i <code>camelCase</code>.`

**Comment by Joergen** [comment]
@jakobkappel Vores sidste to indlæg har krydset hinanden. Kan du ikke prøve at lave et forslag med "kategori for analyse-resultat" og "navn på analyse-resultat"?

**Comment by jakobkappel** [comment]
Sådan kan det jo gå :)

https://pontoon.mozilla.org/da/firefox/all-resources/?string=286098

**Comment by Joergen** [comment]
Godkendt
