### ISSUE TITLE
[KORREKTUR]: Firefox til iOS (Deadline - 10/12)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1170]
https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed&string=290612

**Comment by Joergen** [comment]
Indsat et mellemrum i en enkelt streng (https://pontoon.mozilla.org/da/firefox-for-ios/firefox-ios.xliff/?search=Shopping.OptInCard.FirstParagraph.AmazonOnly.Description.v122&string=291074) og godkendt alle.
