### ISSUE TITLE
[KORREKTUR]: Firefox til Android - (Deadline - 10/12)

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1171]
6 strenge: https://pontoon.mozilla.org/da/firefox-for-android/all-resources/?status=unreviewed&string=290638

**Comment by jakobkappel** [comment]
Det ser godt ud, @Joergen 

Et enkelt ændringsforslag:

https://pontoon.mozilla.org/da/firefox-for-android/all-resources/?status=unreviewed&string=290637

**Comment by Joergen** [comment]
Tak, @jakobkappel
