### ISSUE TITLE
[KORREKTUR]: Mozilla.org - en/firefox/browsers/compare/index.ftl (sammenligning af browsere)

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1173]
hennsoe har bl.a lavet forslag til siden med sammenligning af browsere. Jeg har kigget strengene igennem og løst et par tekniske problemer samt lavet nogle få ændringsforslag, så det er de samme begrebet bruges på siderne.
33 strenge: https://pontoon.mozilla.org/da/mozillaorg/en/firefox/browsers/compare/index.ftl/?string=212626
https://www-dev.allizom.org/da/firefox/browsers/compare/

**Comment by jakobkappel** [comment]
Mange tak for forslagene, @hennsoe. Det ser rigtigt godt ud!

Vi bruger Github til at holde styr på opgaver, diskutere svære strenge, korrekturlæsning og meget andet. 

Så opret endelig issues hér, når du gerne vil have andre til at korrekturlæse dine forslag eller hvis du gerne vil diskutere noget. Du kan læse mere detaljeret om brugen af vores brug af Pontoon/Github i følgende wiki-artikler: 

- [Vejledning til oversættelse på Pontoon](https://github.com/MozillaDanmark/mozilla-dk/wiki/Vejledning-til-overs%C3%A6ttelse-p%C3%A5-Pontoon ) Hvor billederne desværre er forsvundet for nylig, fordi de fandtes på en server, vi brugte inden Github. Så det skal vi lige have styr på (#1174 ). 
- [Om issues](https://github.com/MozillaDanmark/mozilla-dk/wiki/Opret-issues)

I wiki'en kan du også læse mere om, hvordan vi arbejder med oversættelser (style-guide etc.), hvordan vi tester oversættelser samt anden nyttig viden om at orientere sig i de Mozilla-projekter, vi arbejder med. 

---
Som du kan se på oversigten over issues er der mere at lave end vi har tid til. Så vi værdsætter virkelig din hjælp!

**Comment by jakobkappel** [comment]
@hennsoe, så har @Joergen og jeg kigget dine forslag igennem. Nogle er gemt uden videre, andre er gemt med små rettelser - og en række af strengene har vi lavet nye forslag til: 

https://pontoon.mozilla.org/da/mozillaorg/en/firefox/browsers/compare/index.ftl/?status=unreviewed&string=212643

Tanken er nu, at vi alle kigger forslagene igennem og finder frem til den bedste løsning i fællesskab :)

Nedenfor har jeg skrevet lidt om baggrunden for nogle af mine forslag. Sig endelig til, hvis I synes at der er noget, jeg har misforstået. 

### Utility
Ordbogen siger godt nok "anvendelighed" eller "brugbarhed". Men i sammenhængen bliver det sært: 

![image](https://github.com/MozillaDanmark/mozilla-dk/assets/3586612/1560011c-a200-4009-804d-282a50d29005)

Tingene på listen er funktioner, ikke "utilities". 

### Privacy
Det er et besværligt begreb at oversætte, eftersom det kan bruges på en noget andet måde på engelsk end på dansk. Eksempelvis går det fint at sige "Make privacy a habit", "For your privacy, translations never leave your device." eller bruge "...level of privacy..." , hvilket direkte oversat bliver ret mystisk. "Beskyttelse af dit privatliv" plejer at fungere i de fleste sammenhæng. Problemet er selvfølgelig, at der ikke altid er plads til så meget ekstra tekst.  

### Portability
Den er også svær. "Portabilitet" har jo den rigtige betydning, men det er ikke ligefrem et ord, man hører hver eller hveranden dag. Og det findes slet ikke i https://ordnet.dk/korpusdk. "Understøttelse på flere enheder" eller noget i dén retning dækker betydningen fint, men det er unægteligt noget langt i det. 

![image](https://github.com/MozillaDanmark/mozilla-dk/assets/3586612/e9640c5f-123b-473f-85fd-924f4ded53c7)
vs
![image](https://github.com/MozillaDanmark/mozilla-dk/assets/3586612/8695b419-c69f-43be-b1da-c3c70b19b2b0)

("Tilgængelighed på mobil" kommer vist fra en anden fil. Men det må næsten være en fejl. "Tilgængelig til mobil"?)

---
Jeg kom til at klikke lidt for hurtigt på https://pontoon.mozilla.org/da/mozillaorg/en/firefox/browsers/compare/index.ftl/?status=unreviewed&string=212631 - og fik slettet et forslag, én af jer havde tilføjet, fremfor ét med fejl i, jeg selv havde lavet :/

**Comment by Joergen** [comment]
Flere strenge på den side deles af flere sider, der sammenligner Firefox med andre browsere. Bl.a. "Portabilitet"  (Jeg mener bestemt at vi har diskuteret den oversættelse tidligere) og "Funktionalitet".
https://pontoon.mozilla.org/da/mozillaorg/en/firefox/browsers/compare/shared.ftl/?string=212649

**Comment by Joergen** [comment]
https://github.com/MozillaDanmark/mozilla-dk/issues/1005

**Comment by jakobkappel** [comment]
Det var godt husket, @Joergen!

Jeg er stadig ikke så vild med "Portabilitet". Men det er heller ikke nemt at finde på noget andet, der virker i alle tilfælde.

- Understøttelse på flere enheder
- Til flere platforme / enheder
- Understøttede platforme / enheder

**Comment by hennsoe** [comment]
Hvis man skulle holde det til et ord så kunne "flytbar" eller "forskydelig" være nogle muligheder, men jeg synes også at noget i retning af "Understøttet på flere platforme" kunne ramme det godt. og hvis man stadig skal holde den kort, så er jeg med på Jakobs "Til flere platforme"

**Comment by jakobkappel** [comment]
@Joergen, gider du løbe de udestående forslag igennem ved lejlighed? 

https://pontoon.mozilla.org/da/mozillaorg/en/firefox/browsers/compare/index.ftl/?status=missing&string=212622

@hennsoe, sig endelig til, hvis du er kommet på bedre løsninger i mellemtiden - eller hvis du har lyst til at lave mere, men ikke helt ved, hvor du skal tage fat :)

**Comment by Joergen** [comment]
@jakobkappel Jeg kigger på strengene.
Er det første komma i disse to strenge ikke anbragt forkert? 
https://pontoon.mozilla.org/da/mozillaorg/en/firefox/browsers/compare/index.ftl/?search=The+first+thing+to+point+out+about&string=212644

**Comment by hennsoe** [comment]
Jo, kommaet er sat forkert, har tilføjet en rettet, samt lidt for læseligheden.

Tilføjelse: Den anden er også fin nok, hvis kommaet flyttes til at være imellem "er" og "at".
