### ISSUE TITLE
[KORREKTUR]: Nye strenge til Firefox iOS (Deadline - 14/1)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1175]
__Link til strenge markeret "unreviewed" på pontoon.mozilla.org eller ny oversættelse på support.mozilla.org:__

https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed

Der er mange gengangere og ikke så mange helt nye strenge.

__Link eller instruktion til at teste oversættelsen:__

https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.firefox-ios.l10n-screenshots.latest/da

**Comment by Joergen** [comment]
To strenge tilbage:
https://pontoon.mozilla.org/da/firefox-for-ios/firefox-ios.xliff/?status=missing&string=220029

Lidt forskellig oversættelse af  strenge med "Authenticate": https://pontoon.mozilla.org/da/firefox-for-ios/firefox-ios.xliff/?search=Authenticate&string=280825

**Comment by jakobkappel** [comment]
Der er i mellemtiden kommet nye strenge til med deadline 11/2. Så jeg lukker denne og tager de manglende strenge i løbet af ugen
