### ISSUE TITLE
"Switching to a new device" oversat på to forskellige måder i Firefox

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1180]
Jeg kiggede på artiklen "[Back up your Firefox data](https://support.mozilla.org/en-US/kb/switching-devices)" på SUMO og opdagede, at vi har to forskellige oversættelser af strengen "**Switching to a new device**": https://transvision.mozfr.org/?recherche=Switching+to+a+new+device&repo=gecko_strings&sourcelocale=en-US&locale=da&search_type=strings
Det ene menupunkt er i Firefox-menuen -> Hjælp (**Skifte til en anden enhed**), det andet i menuen Hjælp (**Skifte til en ny enhed**).
Kunne vi ikke nøjes med  en af dem?

**Comment by jakobkappel** [comment]
Så er der kun én variant (med "...ny...")
