### ISSUE TITLE
[KORREKTUR + hjælp]: Nye strenge til Monitor-websted (Deadline - 29/1)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1181]
https://pontoon.mozilla.org/da/firefox-monitor-website/all-resources/?status=missing&string=292511

https://fx-breach-alerts.herokuapp.com/

Der er en håndfuld strenge, som henviser til amerikanske forhold (om 'credit reports' og sådan noget). Skal vi bare oversætte dem direkte eller tilføje kommentarer i stil med "Gælder kun i USA"?

**Comment by Joergen** [comment]
> https://pontoon.mozilla.org/da/firefox-monitor-website/all-resources/?status=missing&string=292511
> 
> https://fx-breach-alerts.herokuapp.com/
> 
> Der er en håndfuld strenge, som henviser til amerikanske forhold (om 'credit reports' og sådan noget). Skal vi bare oversætte dem direkte eller tilføje kommentarer i stil med "Gælder kun i USA"?

Jeg synes vi skal oversætte dem direkte uden kommentarer.

**Comment by Joergen** [comment]
Forslag: https://pontoon.mozilla.org/da/firefox-monitor-website/all-resources/?status=unreviewed&string=292511
Mangler: https://pontoon.mozilla.org/da/firefox-monitor-website/all-resources/?extra=missing-without-unreviewed&string=292479

**Comment by jakobkappel** [comment]
@Joergen, så er der nogle forslag til de manglende strenge: 

https://pontoon.mozilla.org/da/firefox-monitor-website/all-resources/?status=unreviewed&string=292430

**Comment by Joergen** [comment]
@jakobkappel 
Der er lige den ene streng tilbage: https://pontoon.mozilla.org/da/firefox-monitor-website/all-resources/?status=missing&string=292522
Se min kommentar og mit nye forslag til strengen.

**Comment by jakobkappel** [comment]
Mange tak, @Joergen

Jeg har føjet et nyt forslag til, så nu er der da lidt at vælge mellem :D 

Jeg har også spurgt ind til strengen på https://chat.mozilla.org, for den er altså ikke ligefrem entydig.

**Comment by Joergen** [comment]
Godkendt forslaget.
