### ISSUE TITLE
[KORREKTUR]: Nye strenge til Firefox [Deadline - 11/2]

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1185]
Beklager den korte frist. Jeg har været helt i brædderne med noget corona/influenza-skrammel. Formodentlig er deadline nok først mandag. 

https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=300107

Rigtigt godt arbejde med alle forslagene,@hennsoe! Du må meget gerne sige til her på Github, når der er noget klart til korrektur, så vi andre kan kigge på det :)

----

Jeg er usikker på strengene med "Sample was..." ''Scanning' fungerer fint i mange af strengene, men i dem med rumlige begreber "venstre, højre" etc. synes jeg, at det bliver lidt unøjagtigt (også i originalerna).

**Comment by Joergen** [comment]
> Jeg er usikker på strengene med "Sample was..." ''Scanning' fungerer fint i mange af strengene, men i dem med rumlige begreber "venstre, højre" etc. synes jeg, at det bliver lidt unøjagtigt (også i originalerna).

Jeg kan ikke rigtigt komme på bedre forslag. Jeg overvejede at foreslå  oversættelse af "Sample was too low." med "Scanningen er udført for lavt". Men det er jo ikke scanningen, men fingeraftrykket/øjet der er for lavt. Så skulle der byttes rundt, så forslaget i stedet blev "Scanningen er udført for højt.".

**Comment by Joergen** [comment]
Hvis det skal give mening på dansk, skal "Sample" oversættes forskelligt (eller måske helt udelades).
Jeg laver lige nogle forslag, der måske kan bruges eller inspirere.

**Comment by Joergen** [comment]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=292876

**Comment by hennsoe** [comment]
Jeg har lige kigget på nogle af strengene, og Joergens rettelser fra "det" til "den" ser fine ud, men det kreperer mig lidt at "Speakers" bliver til "højtalere", hvis det, som der står i kommentarerne, skal bruges som et generelt ord til både hovedtelefoner og højtalere.

**Comment by hennsoe** [comment]
Jeg er også mere til Joergens rettelser angående det med at se skærm indhold. (https://pontoon.mozilla.org/da/firefox/all-resources/?string=300099), hvis det ikke skal være i stil af min.

Jeg har dog lidt et problem med "Det scannede", ved f.eks.; https://pontoon.mozilla.org/da/firefox/all-resources/?string=292872

Det afviger fra alle andre lignende sprog (SE), men også NL og DE oversættelserne har det i ubestemt form.

**Comment by jakobkappel** [comment]
> Jeg har lige kigget på nogle af strengene, og Joergens rettelser fra "det" til "den" ser fine ud, men det kreperer mig lidt at "Speakers" bliver til "højtalere", hvis det, som der står i kommentarerne, skal bruges som et generelt ord til både hovedtelefoner og højtalere.

Problemet er, at "lydenhed" kan indbefatte mikrofoner - og det er jo en helt anden situation at give en fil adgang til. Kunne det i stedet være "... andre højttalere eller hovedtelefoner", alternativt "...afspille lyd på andre [lokale] enheder"?

----

Strengene med "Sample" er svære. Jeg hælder nok mest til at oversætte de, der indeholder rumlige begreber, uden 'Skanningen' eller 'Det skannede", altså "For langt til højre" etc. Det burde fremgå af konteksten, hvad der er på spil.

**Comment by Joergen** [comment]
> > Jeg har lige kigget på nogle af strengene, og Joergens rettelser fra "det" til "den" ser fine ud, men det kreperer mig lidt at "Speakers" bliver til "højtalere", hvis det, som der står i kommentarerne, skal bruges som et generelt ord til både hovedtelefoner og højtalere.
> 
> Problemet er, at "lydenhed" kan indbefatte mikrofoner - og det er jo en helt anden situation at give en fil adgang til. Kunne det i stedet være "... andre højttalere eller hovedtelefoner", alternativt "...afspille lyd på andre [lokale] enheder"?

Ja, det fungerer. Har lavet nyt forslag.

Mine forslag til strengene, der starter med "Allow" i filen webrtcIndicator.ftl, har jeg taget fra lignende strenge i filen. https://transvision.mozfr.org/?recherche=webrtc-allow-share&repo=gecko_strings&sourcelocale=en-US&locale=da&search_type=entities

**Comment by hennsoe** [comment]
> Problemet er, at "lydenhed" kan indbefatte mikrofoner - og det er jo en helt anden situation at give en fil adgang til. Kunne det i stedet være "... andre højttalere eller hovedtelefoner", alternativt "...afspille lyd på andre [lokale] enheder"?

Det kunne også være "afspilningsenhed", som er set i oversættelser ved andre programmer.

**Comment by Joergen** [comment]
> > Problemet er, at "lydenhed" kan indbefatte mikrofoner - og det er jo en helt anden situation at give en fil adgang til. Kunne det i stedet være "... andre højttalere eller hovedtelefoner", alternativt "...afspille lyd på andre [lokale] enheder"?
> 
> Det kunne også være "afspilningsenhed", som er set i oversættelser ved andre programmer.

Der skal rettes flere steder i filen: https://pontoon.mozilla.org/da/firefox/browser/browser/webrtcIndicator.ftl/?search=speakers&string=262173

**Comment by Joergen** [comment]
> Strengene med "Sample" er svære. Jeg hælder nok mest til at oversætte de, der indeholder rumlige begreber, uden 'Skanningen' eller 'Det skannede", altså "For langt til højre" etc. Det burde fremgå af konteksten, hvad der er på spil.

Det er desværre ikke noget jeg kan teste, men prøv det.

**Comment by jakobkappel** [comment]
Jeg har desværre heller ikke mulighed for at teste. Så jeg opretter et issue og undersøger det nærmere.

Til strengene med 'Speakers' har jeg foreslået "...adgang til at afspille lyd på andre enheder". "Afspilningsenhed" synes jeg ikke virker så godt, eftersom konteksten ikke indikerer, at det har noget med lyd at gøre (som i Windows, hvor ordet optræder i indstillingerne for lyd). 

https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=262173
