### ISSUE TITLE
[KORREKTUR]: Nye strenge til Firefox iOS [Deadline - 11/2]

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1186]
https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed&string=292040

**Comment by Joergen** [comment]
En streng. Jeg har ikke godkendt den. Se kommentar.
https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed&string=292040

**Comment by jakobkappel** [comment]
Opdateret til at være af samme form som https://transvision.mozfr.org/?recherche=Authenticate+to&repo=firefox_ios&sourcelocale=en-US&locale=da&search_type=strings
