### ISSUE TITLE
[KORREKTUR]: Mozilla.org/en/firefox/browsers/compare/index.ftl

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1191]
Fire strenge: https://pontoon.mozilla.org/da/mozillaorg/en/firefox/browsers/compare/index.ftl/?status=unreviewed&string=301173

Stage: https://www-dev.allizom.org/firefox/browsers/compare/

**Comment by Pokersut** [comment]
To godkendt, to mindre ændringsforslag.

**Comment by Joergen** [comment]
Tak for forslagene @Pokersut
