### ISSUE TITLE
[KORREKTUR]: Nye strenge til Firefox iOS (Deadline - 10/3)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1194]
https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed&string=301277

Skærmbilleder: 
https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mobile.v2.firefox-ios.l10n-screenshots.latest.da/artifacts/public%2Fscreenshots%2Fda.zip

**Comment by Joergen** [comment]
Ok. Men skærmbillederne er fra november 23.

**Comment by jakobkappel** [comment]
Det var da pokkers, at skærmbillederne ikke er opdaterede. Og sjusket af mig ikke at tjekke dem (bruger dem ikke selv, fordi jeg har en telefon med en beta-version).
