### ISSUE TITLE
[KORREKTUR + hjælp]: Nye strenge til Firefox (Deadline - 10/3) 

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1195]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=missing

Der er en håndfuld strenge, jeg ikke kan finde ud af. De har samme form: 

`Utility Generic Audio Decoder`
`Utility Windows Media Foundation` 
[etc.]

_GROUP COMMENT Localization for Gecko process types defined in GeckoProcessTypes.h_

**Comment by Joergen** [comment]
> Der er en håndfuld strenge, jeg ikke kan finde ud af. De har samme form:
> 
> `Utility Generic Audio Decoder` `Utility Windows Media Foundation` [etc.]
> 
> _GROUP COMMENT Localization for Gecko process types defined in GeckoProcessTypes.h_

Dem undrede jeg mig også over. Jeg kiggede også på disse resultater https://searchfox.org/mozilla-central/search?q=GeckoProcessTypes.h&path=&case=false&regexp=false uden at blive meget klogere.
Strengene vises på siden about:support under **Fjern-processer**.

![fjern-processer](https://github.com/MozillaDanmark/mozilla-dk/assets/3466269/d621ff12-a131-4cfb-af4f-aae94db6f692)

**Comment by Joergen** [comment]
Jeg ved ikke hvad man bedst kan oversætte "Utility" med i dette tilfælde, men her er nogle bud.
Program
Funktion
Værktøj
Hjælpemiddel
Hjælpeprogram

**Comment by Joergen** [comment]
Du har oversat "Utility" med "Værktøj" på siden about:processes
![værktoejer](https://github.com/MozillaDanmark/mozilla-dk/assets/3466269/47099abc-8f80-4ab5-8655-3477f348a55a)

**Comment by jakobkappel** [comment]
Godt fundet. Men sært, at der ikke er skilletegn i de nye strenge ("Værktøj: JavaScript Oracle" eller noget i den stil). 

Der er kommet lidt nye strenge til, siden jeg åbnede issuet. De kommer forhåbentlig ikke med i den næste beta, men så er de da taget :)

https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=301621

**Comment by Joergen** [comment]
>Men sært, at der ikke er skilletegn i de nye strenge ("Værktøj: JavaScript Oracle" eller noget i den stil).

Ja, det tænkte jeg også på.
Der er lige et par strenge tilbage. Det er som om, der mangler noget i den ene streng. Men måske er det med vilje? 
I den anden har jeg ændret en access key, så det passer bedre til de nye access keys.
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=285521

**Comment by jakobkappel** [comment]
Hov. Jeg har helt overset den sætning. 

Godt at du var opmærksom på dét med access key'en :)
