### ISSUE TITLE
[KORREKTUR]: Mozilla VPN Client - Deadline 29 marts 2024

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1199]
14 strenge: https://pontoon.mozilla.org/da/mozilla-vpn-client/all-resources/?status=unreviewed&string=302327
"undervisningsindhold" er det, der vises, når man klikker på et ? i appen.
Se evt. https://mozilla-mobile.github.io/mozilla-vpn-client/?branch=i18n_automation_for_2.21.0

**Comment by jakobkappel** [comment]
Jeg har slettet et enkelt komma (i to identiske strenge) - og så har jeg tilføjet et enkelt forslag: 

https://pontoon.mozilla.org/da/mozilla-vpn-client/all-resources/?status=unreviewed&string=302299
(det er selvfølgelig en smagssag, så bare kyl forslaget ud, hvis du synes noget andet :)

**Comment by Joergen** [comment]
Tak for det @jakobkappel  - og go påske.
