### ISSUE TITLE
[KORREKTUR]: Thunderbird, 69 strenge

### ISSUE THREAD

**Issue by Pokersut** [MozillaDanmark/mozilla-dk#1201]
Link: https://pontoon.mozilla.org/da/thunderbird/all-resources/?status=unreviewed

Der er nogle strenge, der alle begynder med "List-", fx "List-ID", "List-Subscribe" og "List-Archive". De har alle en kommentar, der hedder "List management header - RFC 2369", men jeg kan ikke gennemskue, hvad det betyder.

Umiddelbart virker det til at være nogle interne system-betegnelser, så jeg har ikke oversat dem.

/Mikkel

**Comment by jakobkappel** [comment]
Det tror jeg er den rigtige løsning, @Pokersut 

Ifølge https://www.rfc-editor.org/rfc/rfc2369 indeholder  RFC 2369: 

> [...] **_a set of structured fields to be added to email messages sent by email distribution lists._** Each field typically contains a URL (usually mailto [[RFC2368](https://www.rfc-editor.org/rfc/rfc2368)]) locating the relevant information or performing the command directly. The three core header fields described in this document are List-Help, List-Subscribe, and List-Unsubscribe.

Så det ligner egentlig lidt en fejl, at strengene er blevet tagget op til at blive oversat (og på flere sprog også er blevet det). Som at oversætte \<code> med \<kode>. Men det er bare et gæt.

**Comment by Joergen** [comment]
Jeg har højreklikket på List-ID i meddelelseshovedet på en mail fra Github.

![List-ID](https://github.com/MozillaDanmark/mozilla-dk/assets/3466269/4a4bc248-c83f-4bfc-930d-27e2b6afee30)

**Comment by Joergen** [comment]
Jeg har lavet nogle ændringsforslag: https://pontoon.mozilla.org/da/thunderbird/all-resources/?status=unreviewed&string=292879

"List-ID" må være modtagerens ID i den mailingliste, meddelelsen er sendt fra. Den vises i meddelelseshovedet i TB. De andre "List-"-strenge vises kun, hvis man vælger Vis -> Meddelelseshoveder -> Alt.

**Comment by Pokersut** [comment]
@Joergen, tænker du "list" som verbum i strengen "List arkiver" (https://pontoon.mozilla.org/da/thunderbird/all-resources/?status=unreviewed&string=301979)?

Jeg opfatter det som et substantiv, men det giver måske ikke mening ift. den kommentar, der er til strengen.

Jeg har det personligt lidt stramt med den nydanske betydning af "liste" - så hvis det er et verbum, vil jeg foretrække "oplist" 🙂

**Comment by Joergen** [comment]
Ifølge RFC 2369:

> [3.6](https://www.rfc-editor.org/rfc/rfc2369#section-3.6). List-Archive
> 
>    The List-Archive field describes how to access archives for the list.
> 
>    Examples:
> 
>      List-Archive: <mailto:archive@host.com?subject=index%20list>
>      List-Archive: <ftp://ftp.host.com/pub/list/archive/>
>      List-Archive: <http://www.host.com/list/archive/> (Web Archive)

![List-Archive](https://github.com/MozillaDanmark/mozilla-dk/assets/3466269/0592769f-7ee3-48b9-abd6-2bc2c1daebbf)

Hvis jeg højreklikker på List-ID og vælger "List Archives" (se skærmbillede), åbnes https://github.com/MozillaDanmark/mozilla-dk
"Afmeld abonnement" svarer til at klikke på "List-Unsubscribe". "Skriv" svarer til at klikke på "List-Post".

Kun hvis brugeren har valgt at få vist hele headeren, vises punkterne efter "Liste-ID".

**Comment by Joergen** [comment]
Et eksempel:
Jeg har modtaget en mail fra Delphine via Mozilla Discourse. Vælger jeg menupunktet "List Archives" i den mail, åbnes https://discourse.mozilla.org/t/interview-women-in-localization/128751

**Comment by jakobkappel** [comment]
"Vis arkiv"?

**Comment by Pokersut** [comment]
> "Vis arkiv"?

Ja, det er en fin løsning - men igen: Det kommer an på, om "list" i den oprindelige streng er et verbum eller et substantiv.

Når der er bindestreg i strengen, kan det vel kun være et substantiv? Og dermed "liste" på dansk.

**Comment by jakobkappel** [comment]
Jeg kiggede ikke grundigt nok på Jørgens skærmbillede... 

![billede](https://github.com/MozillaDanmark/mozilla-dk/assets/3586612/abf7056d-e336-4922-9044-4146ab9dbeb9)

Strengen til højre giver mening at oversætte som "Vis arkiv". 

Strengene til venstre må være substantiver, der skal beskrive de links, der står ud for. Men resultatet af at klikke på de links er vel det samme som at klikke på menu-punkterne?

Liste-ID
Liste-afmelding
???
Liste-arkiv

**Comment by Joergen** [comment]
Den tilbageværende streng er "List Archives". Her opfatter jeg "List" som et verbum.
Jeg har godkendt alle strengene med "List-" i deres oprindelige engelske version undtagen "List-ID", hvor jeg godkendte oversættelsen "Liste-ID". Det har jeg netop ændret. Alle strenge fra RFC 2369 med "List-" er godkendt med deres oprindelige engelske tekst.
De pågældende strenge vises kun, når brugeren har valgt at få vist alle elementerne i mail headeren. Mail headeren indeholder også andre elementer der er på engelsk.

**Comment by Pokersut** [comment]
> Den tilbageværende streng er "List Archives".

Ah, selvfølgelig - det var mig, der ikke var vågen! Troede, det var strengen med bindestreg, der manglede ...

@Joergen, hvad siger du til @jakobkappels forslag, "Vis arkiv"? Den kan jeg godt lide.

**Comment by Joergen** [comment]
> @Joergen, hvad siger du til @jakobkappels forslag, "Vis arkiv"? Den kan jeg godt lide.

Ja - den er ok. Brug V som access key

**Comment by Pokersut** [comment]
Tak for kommentarer, begge to!
