### ISSUE TITLE
mozilla.org: Sammenligning mellem Firefox og Chrome

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1203]
Vi har bakset med flere af sammenligning-siderne ret længe, så jeg åbner et issue for at gøre det lidt nemmere at huske på at blive færdig med dem.

https://pontoon.mozilla.org/da/mozillaorg/en/firefox/browsers/compare/chrome.ftl/?status=missing&string=212825

**Comment by jakobkappel** [comment]
Der mangler kun fem strenge i filen, men det er nogle store mundfulde.

**Comment by Joergen** [comment]
Fra chat.mozilla.org vedrørende siderne med browser-sammenligninger:
"Apparently the pages were taken down late last week for legal reasons. The replacement pages are being coded and will be ready for localization at a later time."

**Comment by jakobkappel** [comment]
Suk

Men så må vi jo bare vente på, at der dukker nogle nye op
