### ISSUE TITLE
[KORREKTUR]: 43 nye strenge til Firefox (Deadline - 5. maj)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1205]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=303157

**Comment by Joergen** [comment]
Jeg har lavet nogle ændringsforslag og skrevet nogle kommentarer til nogle af strengene:
https://pontoon.mozilla.org/da/firefox/all-resources/?status=missing&string=303144

**Comment by jakobkappel** [comment]
Tak, @Joergen 

Der er kommet en stak nye strenge til i mellemtiden - og jeg har lavet nogle nye forslag til de strenge, du havde kommentarer til: 

https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=304437

**Comment by Joergen** [comment]
Jeg fandt denne artikel vedrørende standardbrowser i Win11: https://komputer.dk/internet/browser/skift-let-standardbrowser-i-windows-11

Jeg kan se af en kommentar, jeg har lavet i artiklen på SUMO, at jeg har gættet mig frem til oversættelsen i den artikel.
Jeg retter på Pontoon og SUMO.

**Comment by Joergen** [comment]
1 stk tilbage: https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=304431

**Comment by jakobkappel** [comment]
Sjovt med Komputer-artiklen - det er én af mine gamle kolleger som har skrevet den. Og han er en vældigt kvik og grundig fyr, så det er garanteret rigtigt :)
