### ISSUE TITLE
[KORREKTUR]: En sjat strenge til mozilla.org

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1206]
https://pontoon.mozilla.org/da/mozillaorg/en/firefox/features/add-ons-2023.ftl/?status=unreviewed&string=284899

Jeg kan ikke finde filen på https://github.com/mozilla-l10n/www-l10n/tree/master/da/firefox, så måske er den forældet.

---

https://pontoon.mozilla.org/da/mozillaorg/en/firefox/features/eyedropper-2023.ftl/?status=unreviewed&string=284761

https://www-dev.allizom.org/da/firefox/features/eyedropper/

**Comment by Joergen** [comment]
> Jeg kan ikke finde filen på https://github.com/mozilla-l10n/www-l10n/tree/master/da/firefox, så måske er den forældet.

Måske, men den findes live her: https://www.mozilla.org/en-US/firefox/features/add-ons/

Et enkelt ændringsforslag:
https://pontoon.mozilla.org/da/mozillaorg/en/firefox/features/eyedropper-2023.ftl/?status=unreviewed&string=284869

**Comment by jakobkappel** [comment]
Filerne dukker åbenbart først op i repositoriet, når der er mindst en oversat streng gemt i filen på Pontoon: https://github.com/mozilla-l10n/www-l10n/blob/master/da/firefox/features/add-ons-2023.ftl Så lærte jeg da noget nyt i dag :)
