### ISSUE TITLE
[OVERSÆTTELSE][KORREKTUR]: Mozilla VPN Client - Deadline 29 april

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1207]
8 strenge uden forslag: https://pontoon.mozilla.org/da/mozilla-vpn-client/all-resources/?extra=missing-without-unreviewed&string=304133

Jeg har lavet forslag til en del strenge - herunder ændringsforslag til alle strengene med sprognavne (fra lille til stort begyndelsesbogstav).  85 forslag til 53 manglende strenge
https://pontoon.mozilla.org/da/mozilla-vpn-client/all-resources/?status=missing&string=304133
https://pontoon.mozilla.org/da/mozilla-vpn-client/extras.xliff/?status=unreviewed&string=304122

**Comment by jakobkappel** [comment]
Det ser godt ud - håber ikke at du har alt for ondt i klippe-klistre-fingrene :)

Skal vi måske forsøge at få slået tjekket fra, der fortæller at en oversættelse er identisk med originalen? Jeg tror aldrig, at jeg er stødt på et tilfælde, hvor det var til nogen som helst nytte.

**Comment by Joergen** [comment]
> Skal vi måske forsøge at få slået tjekket fra, der fortæller at en oversættelse er identisk med originalen? Jeg tror aldrig, at jeg er stødt på et tilfælde, hvor det var til nogen som helst nytte.

Ja, den advarsel er helt overflødig.
Ofte har jeg også bare brug for at navigere rundt mellem strengene i Pontoon uden at godkende forslag. Men med funktionen, der automatisk udfylder input-feltet, bliver jeg ofte spurgt, om jeg vil forlade strengen uden at godkende. Jeg bliver hele tiden tvunget til at klikke på en knap for at komme videre.
