### ISSUE TITLE
[KORREKTUR]: 14 strenge til Firefox iOS (Deadline 5/5)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1210]
https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed&string=304544

**Comment by Joergen** [comment]
Rettet oversættelse af "Privacy notice" fra "Privatlivspolitik" til "Privatlivserklæring" og godkendt.
Jeg håber vi snart får mulighed for at rette i Translation Memory.

**Comment by jakobkappel** [comment]
Ja, det kunne være rart. 

Men issuet har ret lav prioritet (P3), så det bliver desværre nok ikke lige foreløbig. De har 29 issues med P2 i køen...
