### ISSUE TITLE
[KORREKTUR]: 8 strenge til Mozilla VPN

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1211]
https://pontoon.mozilla.org/da/mozilla-vpn-client/all-resources/?status=missing&string=304133

**Comment by Joergen** [comment]
https://pontoon.mozilla.org/da/mozilla-vpn-client/all-resources/?status=unreviewed&string=304107

**Comment by jakobkappel** [comment]
Perfekt, tak!
