### ISSUE TITLE
[KORREKTUR]: 14 strenge til Thunderbird

### ISSUE THREAD

**Issue by Pokersut** [MozillaDanmark/mozilla-dk#1213]
https://pontoon.mozilla.org/da/thunderbird/all-resources/?status=unreviewed

Jeg kan ikke bestemme mig for, om det skal hedde "Certifikatet **for** { $hostname }" eller "Certifikatet **til** { $hostname }". Er gået med "for".

**Comment by Joergen** [comment]
Det er også oversat med "Certifikatet for" i Firefox: https://transvision.mozfr.org/?recherche=The+certificate+for&repo=gecko_strings&sourcelocale=en-US&locale=da&search_type=strings

**Comment by Joergen** [comment]
Et par ændringsforslag: https://pontoon.mozilla.org/da/thunderbird/all-resources/?status=unreviewed&string=304284

**Comment by Pokersut** [comment]
Tak, @Joergen !
