### ISSUE TITLE
[KORREKTUR]: Common Voice

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1214]
@jakobkappel 

Jeg tror det er nemmere at kommunikerer her vedrørende diverse strenge, end på Pontoon.
**You want to join the Common Voice mailing list** -> Du vil tilmelde dig mailinglisten for Common Voice
![You_want-to-join](https://github.com/MozillaDanmark/mozilla-dk/assets/3466269/7dec66be-beaf-4823-be64-5ce895c8e465)

**Comment by jakobkappel** [comment]
Ja, det er det nok. 

Der er en række eksempler på "Fejllæsninger", hvor strengene er oversat direkte til dansk. Men det bliver noget forvirrende, da der jo så ikke er nogen fejl i de danske eksempler: 

![billede](https://github.com/MozillaDanmark/mozilla-dk/assets/3586612/044adf79-6309-49e0-8246-62ca2ec0afa3)

**Comment by jakobkappel** [comment]
https://commonvoice.mozilla.org/en/guidelines

**Comment by Joergen** [comment]
https://github.com/MozillaDanmark/mozilla-dk/issues/1029

**Comment by Joergen** [comment]
Reader Effects -> Oplæsereffekter
Jeg tror vi også havde den oppe at vende sidst.
Der findes allerede en godkendt version af strengen: https://pontoon.mozilla.org/da/common-voice/all-resources/?search=Reader+Effects&string=228310

**Comment by jakobkappel** [comment]
> #1029

Der kan man bare se. Det havde jeg glemt alt om...
