### ISSUE TITLE
Oversættelse af "complementary" i forbindelse med Accessibility

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1215]
Der er lige dukket en "ny" streng op vedrørende **accessibility**. Vi har tidligere oversat ordet med "komplementær" og "supplerende". https://transvision.mozfr.org/?recherche=complementary&repo=gecko_strings&sourcelocale=en-US&locale=da&search_type=strings
V bør bruge samme oversættelse til alle tre forekomster.
https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/complementary.html

**Comment by jakobkappel** [comment]
Enig. 

Efter at have læst teksten på siden, du linker til, så synes jeg at "supplerende" er det bedste bud. 

Så jeg ændrer til dét alle tre steder.
