### ISSUE TITLE
[KORREKTUR]: Firefox (Deadline - 2. juni)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1218]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=305858

@Joergen, der findes også lidt forslag til ændringer af nogle af de strenge, du har taget

**Comment by Joergen** [comment]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=305847
Vi har tidligere oversat "Monospace" med "Monospatieret" i Firefox. Jeg har lavet endnu et forslag: "Fast tegnbredde".
Brugeren kan vælge mellem "Sans-serif", "Serif" og "Monospace" under Skrifttype.

**Comment by jakobkappel** [comment]
God løsning med "Fast tegnbredde", så er der ikke noget at tage fejl af :)
