### ISSUE TITLE
[KORREKTUR]: Strenge til Firefox (Deadline - 30. juni)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1225]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=195982

Der var en del forslag til mindre, stilistiske rettelser fra Jens Peter, som jeg har afvist. Det tager nemlig ret lang tid at tjekke konsistens med tilsvarende strenge på tværs af funktioner/programmer - ikke mindst i forhold til https://support.mozilla.org/. Og jeg synes hellere, at vi skal bruge tiden på alle de mange projekter, vi er bagude med :)

**Comment by Joergen** [comment]
Lavede tre ændringer og godkendte. Fjernede bindestreg i to strenge og ændrede "til/fra" til "til eller fra".
https://pontoon.mozilla.org/da/firefox/all-resources/?string=189631
https://pontoon.mozilla.org/da/firefox/all-resources/?string=306869
https://pontoon.mozilla.org/da/firefox/all-resources/?string=193832

**Comment by jakobkappel** [comment]
Tak for hjælpen.

Jeg har føjet "Click to toggle [...]" til https://github.com/MozillaDanmark/mozilla-dk/wiki/Ordliste.
