### ISSUE TITLE
[KORREKTUR]: Et par nye strenge til Firefox og Thunderbird (Deadline 30/6, 1/7)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1228]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=307299

https://pontoon.mozilla.org/da/thunderbird/all-resources/?status=missing&string=307006
(@Joergen, jeg forstår ikke, hvorfor accesskey til de to identiske strenge er 'R' - så jeg har bare beholdt den)

**Comment by Joergen** [comment]
Den forstår jeg heller ikke. Den ene streng er til menuen Hjælp, den anden til Thunderbird-menuen -> Hjælp. (Se skærmbillede). Jeg troede først, at strengene skulle erstatte de to eksisterende  forekomster af "Get Help" / "Få hjælp":
https://pontoon.mozilla.org/da/thunderbird/mail/messenger/appmenu.ftl/?string=248218
https://pontoon.mozilla.org/da/thunderbird/mail/messenger/menubar.ftl/?string=248209

Access key "R" må være R'et i Thunderbird. Men det ser dumt ud i Thunderbird Daily. Måske er det en fejl, der bliver rettet.
Jeg synes vi skal beholde "R" for nu.

![Get_help_with](https://github.com/MozillaDanmark/mozilla-dk/assets/3466269/bc4a3218-cee2-4b75-8788-6e27e7bcffbe)

**Comment by jakobkappel** [comment]
Ja, det ser sært ud. Vi må se, om det er en midlertidig løsning.
