### ISSUE TITLE
[KORREKTUR]: Firefox til Android - Deadline 28. juli

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1230]
22 strenge: https://pontoon.mozilla.org/da/firefox-for-android/all-resources/?status=unreviewed&string=309025

**Comment by jakobkappel** [comment]
Et par forslag og kommentarer: 
https://pontoon.mozilla.org/da/firefox-for-android/all-resources/?status=unreviewed&string=307470

Strengene med "This bar tucks away"..." synes jeg er svære. "...bliver skjul" kunne være en anden mulighed.
