### ISSUE TITLE
[KORREKTUR]: Firefox (Deadline - 28. juli)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1232]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=307526

- Der er en række access-keys, jeg ikke kan gennemskue. 
- En række strenge indeholder "The Windows file-dialog ", som jeg svagt erindrer at Microsoft har oversat. Jeg kan desværre ikke komme i tanke om oversættelesn eller finde den - MS har godtnok kvadret funktionen til at søge i deres termonologi :/
- Jeg kan ikkeregne ud, hvad "Interference" skal referere til. Det har et eller andet med https://wiki.mozilla.org/Security/Sandbox/Process_model at gøre, men jeg har ikke tid til at grave i det og tør derfor ikke foreslå "interferens",

**Comment by Joergen** [comment]
> * En række strenge indeholder "The Windows file-dialog ", som jeg svagt erindrer at Microsoft har oversat. Jeg kan desværre ikke komme i tanke om oversættelesn eller finde den - MS har godtnok kvadret funktionen til at søge i deres termonologi :/

Fildialogboks? https://support.microsoft.com/da-dk/topic/egenskaben-filedialog-8510b02d-e455-44a9-bf38-3787e6d5c8c1
Filbrowser?
Stifinder?
Jeg har ikke gennemgået de pågældende strenge (endnu), men jeg har lavet nogle ændringsforslag til nogle af de andre  strenge:
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=307582

**Comment by Joergen** [comment]
Måske "Fildialogboksen i Windows..."?

**Comment by jakobkappel** [comment]
> Måske "Fildialogboksen i Windows..."?

Det synes jeg er en god løsning, @Joergen . Jeg retter. 

Så mangler der bare "Save PDF before leaving?" Synes du det virker med "Gem PDF, før du lukker?" - eller har du et bedre forslag? Vi kan eventuelt have "... PDF-filen" med

**Comment by Joergen** [comment]
Har lavet forslag og godkendt oversættelsen "Gem PDF-filen, før du lukker?"
