### ISSUE TITLE
[KORREKTUR]: Firefox til iOS (Deadline - 28. juli)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1233]
https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed&string=307332

Næsten alle strenge har været oversat tidligere. 

En del af dem (`Addresses.EditAddress.Autofill*`) er - som tidligere - beholdt på engelsk, fordi det er begreber, der ikke bruges i oversat form.

**Comment by Joergen** [comment]
https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed&string=307375

**Comment by jakobkappel** [comment]
Tak, @Joergen. Godt at du fangede "Pin" - jeg tænkte mig ikke om og fik ikke læst kommentaren.
