### ISSUE TITLE
[KORREKTUR]: Firefox - Deadline 25. august

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1238]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=309375

**Comment by Joergen** [comment]
Forslag til 10 strenge: https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=309375

**Comment by jakobkappel** [comment]
Tak for hjælpen, @Joergen 

Der er en enkelt streng tilbage, som jeg har omformuleret efter at have kigget på, hvordan nogle af de andre sprog har gjort: 

https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=309311
