### ISSUE TITLE
[KORREKTUR]: 67 strenge til Firefox iOS (Deadline + 22. september)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1240]
https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed&string=309607

Næsten alle strenge er kopieret fra Translation memory.

**Comment by Joergen** [comment]
Jeg er i tvivl om en enkelt streng: https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=missing&string=309579
Jeg har skrevet en kommentar til strengen.

**Comment by jakobkappel** [comment]
Ja, der var jeg lidt for hurtig. Godt at du var mere grundig :)
