### ISSUE TITLE
[KORREKTUR]: Mozilla.org/en/firefox/all.ftl

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1243]
Forslag til 27 nye strenge: https://pontoon.mozilla.org/da/mozillaorg/en/firefox/all.ftl/?status=unreviewed&string=309648
De er til diverse download-sider: https://www-dev.allizom.org/da/firefox/all/

**Comment by jakobkappel** [comment]
Hov, jeg blev afbrudt midt i det hele. Men nu er der styr på alle strengene.
