### ISSUE TITLE
[KORREKTUR]: Diverse Mozilla.org-sider  -- Deadline 23. september

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1246]
Jeg så lige, at der er tre mozilla.org-filer med deadline den 23. september.

~~Ny footer: https://pontoon.mozilla.org/da/mozillaorg/en/footer-refresh.ftl/?string=310051~~
~~Tilmelding til nyhedsbrev: https://pontoon.mozilla.org/da/mozillaorg/en/newsletter_form.ftl/?status=unreviewed&string=309968
https://www-dev.allizom.org/en-US/~~

Ny Mozilla.org-startside: https://pontoon.mozilla.org/da/mozillaorg/en/mozorg/home-new.ftl/?string=282853
https://www-dev.allizom.org/da/

**Comment by jakobkappel** [comment]
Godt at du lagde mærke til det, @Joergen 

Det var mere omfattende end jeg regnede med - og jeg vil gerne være lidt ekstra grundig, fordi det sikkert er strenge, der kommer til at findes lang tid fremover. Så resten må blive i morgen. 

Et par forslag til footeren:

https://pontoon.mozilla.org/da/mozillaorg/en/footer-refresh.ftl/?status=unreviewed&string=310051

**Comment by jakobkappel** [comment]
Nyhedsbrevstilmelding: 
https://pontoon.mozilla.org/da/mozillaorg/en/newsletter_form.ftl/?status=unreviewed&string=309950

Startside - jeg når ikke det hele i dag, men indtil videre ser det sådan hér ud: 
https://pontoon.mozilla.org/da/mozillaorg/en/mozorg/home-new.ftl/?status=unreviewed&string=282857

**Comment by jakobkappel** [comment]
Beklgar ventetiden. Men nu tror jeg, at jeg er nået hele vejen rundt: https://pontoon.mozilla.org/da/mozillaorg/en/mozorg/home-new.ftl/?status=unreviewed&string=282833

**Comment by Joergen** [comment]
4 rettelser/ændringsforslag.
https://pontoon.mozilla.org/da/mozillaorg/en/mozorg/home-new.ftl/?status=missing&string=282833

**Comment by jakobkappel** [comment]
Rigtigt gode forslag. Tak, @Joergen
