### ISSUE TITLE
[KORREKTUR]: Mozilla.org/en/firefox/features/adblocker.ftl 	

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1250]
Fem  strenge: https://pontoon.mozilla.org/da/mozillaorg/en/firefox/features/adblocker.ftl/?status=unreviewed&string=310471
https://www-dev.allizom.org/en-US/firefox/features/adblocker/

**Comment by jakobkappel** [comment]
Et par forslag: https://pontoon.mozilla.org/da/mozillaorg/en/firefox/features/adblocker.ftl/?status=unreviewed&string=310471
