### ISSUE TITLE
Ret op på inkonsekvent oversættelse af 'collapse' og 'expand'

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1256]
https://transvision.mozfr.org/?recherche=collapse&repo=all_projects&sourcelocale=en-US&locale=da&search_type=strings
https://transvision.mozfr.org/?recherche=expand&repo=all_projects&sourcelocale=en-US&locale=da&search_type=strings

Ved samme lejlighed kan ordene jo meget passende føjes til https://github.com/MozillaDanmark/mozilla-dk/wiki/Ordliste

collapse > sammenfold
expand > udvid

**Comment by Joergen** [comment]
Jeg har lavet ændringsforslagene.
**Firefox**: https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=159700
**Firefox til Android**: https://pontoon.mozilla.org/da/firefox-for-android/all-resources/?status=unreviewed&string=262216
**Firefox til iOS**: https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed&string=286535
**Mozilla Accounts**: https://pontoon.mozilla.org/da/mozilla-accounts/all-resources/?status=unreviewed&string=310578

Jeg har tilføjet ordene til ordlisten.

**Comment by jakobkappel** [comment]
Perfekt!
