### ISSUE TITLE
[KORREKTUR]: Firefox Monitor Website

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1257]
https://pontoon.mozilla.org/da/firefox-monitor-website/all-resources/?status=unreviewed&string=306860

Jeg ved ikke, hvad vi skal stille op med "Advanced or manual action is needed by you to complete an action."

**Comment by Joergen** [comment]
Det er ikke sikkert, at du får vist det samme, som mig. Her er et par skærmbilleder fra oversigten: https://fx-breach-alerts.herokuapp.com/user/dashboard/action-needed

![status](https://github.com/user-attachments/assets/16a46b9e-d112-459b-9de7-376efb717ae8)

Når man klikker på ? vises dialogen "Status for eksponeringer", med den pågældende streng.
![Status_for_eksponering](https://github.com/user-attachments/assets/237d73e8-c5e5-4d3e-9cfe-f2de7a064839)

**Comment by jakobkappel** [comment]
Argh, jeg glemte at trykke på knappen for at gemme min kommentar nedenfor...

"For at løse problemet skal du udføre en avanceret eller manuel handling"?

Men hvordan er en handling avanceret, hvis den ikke er manuel? 

Måske kunne vi skrive lidt om med "Du skal udføre en handling for at løse problemet"? Jeg gætter på, at folk kan se i næste trin, hvad der skal ske.

**Comment by Joergen** [comment]
> Men hvordan er en handling avanceret, hvis den ikke er manuel?

Der er **Manuelt** og **Auto-remove**.
Den sidste metode kræver et betalt abonnement på Monitor Plus⁩.

Man kan klikke på "Løs alle eksponeringer". Næse trin viser to knapper "Remove them for me" eller "I’ll remove them manually".

Klikker man på ""Remove them for me", åbnes en dialog med teksten "We’ll auto-remove these and guide you through exposures that need manual fixes". Her skal man så vælge en abonnementsplan.

**Comment by jakobkappel** [comment]
Den her røg lidt langt ned i dyngerne.

Jeg har foreslået "For at løse problemet skal du udføre en avanceret eller manuel handling."
