### ISSUE TITLE
[KORREKTUR]: Diverse strenge til Mozilla.org

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1260]
14 strenge:
https://pontoon.mozilla.org/da/mozillaorg/en/download_button.ftl/?status=unreviewed

https://pontoon.mozilla.org/da/mozillaorg/en/firefox/all.ftl/?status=unreviewed&string=311652

https://pontoon.mozilla.org/da/mozillaorg/en/sub_navigation.ftl/?status=missing&string=307573

https://pontoon.mozilla.org/da/mozillaorg/en/ui.ftl/?status=missing&string=309663

https://pontoon.mozilla.org/da/mozillaorg/en/navigation_v2.ftl/?status=unreviewed&string=216341

**Comment by Pokersut** [comment]
Alle godkendt, på nær denne: https://pontoon.mozilla.org/da/mozillaorg/en/sub_navigation.ftl/?status=unreviewed&string=307573

Da jeg oversatte strenge til mobilversionen af TB, valgte vi at bibeholde det engelske navn ("Thunderbird Mobile") - hvis denne streng henviser til det, skal der være overensstemmelse.

**Comment by Joergen** [comment]
I dette tilfælde er der tale om Firefox til mobiltelefon.
"Computer" "**Mobile**" "Funktioner" "Sammenlign browsere" "Mere"
https://www-dev.allizom.org/da/firefox/

**Comment by Pokersut** [comment]
Så er jeg i tvivl om, hvad der er bedst. 

I sammenhæng med produtnavnet er jeg mest til at beholde den engelske betegnelse "Firefox Mobile". Men som menupunkt fungerer det danske nok bedre.

Jeg godkender "Mobil" :-)

**Comment by Joergen** [comment]
Tak for det.
Når "Desktop" og "Mobile" optræder sammen, plejer vi at oversætte med "Computer" og "Mobil".
