### ISSUE TITLE
[KORREKTUR]: Firefox tll Android - Deadline 17. november

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1262]
26 strenge: https://pontoon.mozilla.org/da/firefox-for-android/all-resources/?status=unreviewed&string=311416

**Comment by jakobkappel** [comment]
Et enkelt forslag og en streng, jeg ikke helt forstår: 

https://pontoon.mozilla.org/da/firefox-for-android/all-resources/?status=missing&string=311120

**Comment by Joergen** [comment]
Der er flere strenge, jeg desværre ikke kan se i Nightly til Android (endnu). Jeg tjekker af og til, om de er dukket op.
