### ISSUE TITLE
Oversættelse af "This website complies with the Certificate Transparency policy."

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1263]
Jeg fandt strengen  "This website complies with the Certificate Transparency policy." oversat med "Dette websted overholder åbne revisions-optegnelser-politikken.", da der dukkede et par nye strenge op med "certificate transparency".
https://transvision.mozfr.org/?recherche=Certificate+Transparency+policy&repo=gecko_strings&sourcelocale=en-US&locale=da&search_type=strings

Sporet tilbage til https://bugzilla.mozilla.org/show_bug.cgi?id=1320566. Jeg synes ikke oversættelsen på nogen måde er fyldestgørende.

https://en.wikipedia.org/wiki/Certificate_Transparency

Strengen vises bl.a i vinduet Sideoplysninger under Sikkerhed på https://support.mozilla.org/da/kb/vinduet-sideoplysninger-vis-tekniske-detaljer i Nightly

**Comment by jakobkappel** [comment]
Nej, det er en mystisk oversættelse. Og jeg kan se, at der har været en del strenge af samme form tidligere: https://github.com/mozilla-l10n/firefox-l10n/commit/9b38bc5f6719d24918b2fda0685e60a6db5d5f3e#diff-dbcfb50e666cea50da3c51f71590700fc9eee133f08150e186cef4092fb40672

Jeg har ikke ordentligt tid til at kigge på det lige nu, så jeg vender tilbage.

**Comment by jakobkappel** [comment]
https://pontoon.mozilla.org/da/firefox/security/manager/chrome/pippki/pippki.properties/?search=pageInfo_CertificateTransparency_Compliant&search_identifiers=true&string=163264

Der findes et par andre strenge med "Certificate Transparency", hvor det er oversat lidt anderledes ("gennemsigtighed [...] for certifikater"). Men jeg synes, at det bliver for meget "for" i denne sammenhæng - derfor det lidt uskønne ord "certifikat-gennemsigtighed".

Ét af skærmbillederne på https://support.mozilla.org/da/kb/vinduet-sideoplysninger-vis-tekniske-detaljer er på engelsk, så jeg lægger lige et dansk op i stedet.

**Comment by Joergen** [comment]
Godkendt.
