### ISSUE TITLE
[KORREKTUR]: Firefox (Deadline - 17/11)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1264]
Beklager den korte frist - der skete lige 117 ting på én gang. 

https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=278387

Oversættelsen af den lange streng med "Extensions and themes..." ser lidt forkert ud ift. længden på linjerne, men det burde være okay: 

![Screenshot 2024-11-15 at 11-11-27 Danish (da) · Firefox](https://github.com/user-attachments/assets/d26f5619-8000-402a-a844-53495c259697)

Der er en del strenge med "Tilmeld dig...", Var det i grunde ikke mere rart at læse, hvis det var "Opret en konto...."? fx "Tilmeld dig eller log ind på din konto" > "Opret en konto eller log ind"

**Comment by Joergen** [comment]
>Oversættelsen af den lange streng med "Extensions and themes..." ser lidt forkert ud ift. længden på linjerne, men det burde være okay:

Jeg ændrede strengen for et par dage siden, da den indeholdt en slåfejl (att). Ved dn lejlighed ændrede leg lidt på længden af nogle dele.

>Der er en del strenge med "Tilmeld dig...", Var det i grunde ikke mere rart at læse, hvis det var "Opret en konto...."? fx "Tilmeld dig eller log ind på din konto" > "Opret en konto eller log ind"

Jeg foretrækker, at vi bruger "Opret en konto" som oversættelse af "Create an account".

Du mangler at oversætte en del strenge i filen certError.ftl: https://pontoon.mozilla.org/da/firefox/toolkit/toolkit/neterror/certError.ftl/?status=missing&string=311487

**Comment by Joergen** [comment]
@jakobkappel Hvis du ikke kan nå at oversætte de manglende strenge, så håber jeg, at du kan nå et gennemgå 23 forslag:  https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=313295

**Comment by jakobkappel** [comment]
Det var sært. Jeg har haft samme faneblad med Pontoon åbent ret længe, så jeg burde nok have genindlæst siden. 

Jeg ser, hvor meget jeg kan nå. Det bliver nok først i aften.

**Comment by Joergen** [comment]
Jeg har lavet lidt flere forslag. Flere sætninger går igen i strengene  i filen certError.ftl.

**Comment by jakobkappel** [comment]
Så tror jeg, at vi er kommet hele vejen rundt:

https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=176220

**Comment by Joergen** [comment]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=176220
