### ISSUE TITLE
[KORREKTUR]: Firefox ios (Deadline: 17/11)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1265]
https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed&string=311426

**Comment by Joergen** [comment]
%1$@ tabs closed: %2$@  -> %2$@ lukkede faneblade fra %1$@ https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed&string=311424

Den synes jeg ikke lyder rigtigt.

Hvis jeg i Firefox View på fx. Firefox til Android lukker fx 3 faneblade, vises meddelelsen på Firefox til computer. Og omvendt. Lignende streng "%1$s tabs closed: %2$d" er oversat med "%1$s-faneblade lukket: %2$d" i Firefox til Android.
![Faneblade lukket](https://github.com/user-attachments/assets/4bb5a56c-753e-4cd5-b39f-2ca95c724742)

Den er heller ikke for køn.

I Firefox til Computer vises "3 faneblade i Firefox lukket" https://transvision.mozfr.org/?sourcelocale=en-US&locale=da&repo=gecko_strings&search_type=entities&recherche=browser/browser/accounts.ftl:account-tabs-closed-remotely&entire_string=entire_string

Måske bedre med "%2$@ faneblade lukket fra %1$@".
Jeg kunne rette i Firefox til Android, så strengene ligner hinanden.

**Comment by jakobkappel** [comment]
Jeg synes, at vi skal bruge %2$@ faneblade lukket fra %1$@ - jeg retter

**Comment by Joergen** [comment]
Rettet og godkendt i Firefox til Android også.
