### ISSUE TITLE
[KORREKTUR]: Firefox til Android - Deadline 15. december

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#1267]
55 strenge: https://pontoon.mozilla.org/da/firefox-for-android/all-resources/?status=unreviewed

**Comment by Pokersut** [comment]
Tre forslag:

1. I "Learn more about usage data" opfatter jeg "usage data" som "data om den måde, du bruger Firefox på", men ved ikke, om det er korrekt. For det svarer vist også til det, de kalder "interaction data" i andre strenge.
2. "Debug locales to enable". I kommentaren står der, at det er overskriften på "the list of debug locales that can be enabled and disabled" - så "debug locales" må være et sammensat substantiv?
3. Ved "Update before March 14" står der i kommentaren, at "update" er et verbum :-)

Resten godkendt.

**Comment by Joergen** [comment]
> 3\. Ved "Update before March 14" står der i kommentaren, at "update" er et verbum :-)

Ups! Det havde jeg overset.
Alle godkendt.
