### ISSUE TITLE
[KORREKTUR]: 48 nye strenge til Firefox (deadline - 15/12)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1269]
Beklager den kort tidsfrist. Jeg var blevet logget ud fra Pontoon og opdagede først deadline, da jeg loggede ind tidligere.

https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=313917

**Comment by Joergen** [comment]
15 forslag: https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed
I filen "aboutGlean.ftl" har jeg bl.a ændret "metrics" til  "målinger" jvf. tidligere oversættelse i filen. https://transvision.mozfr.org/?sourcelocale=en-US&locale=da&repo=gecko_strings&search_type=entities&recherche=toolkit/toolkit/about/aboutGlean.ftl:about-glean-label-for-ping-names&entire_string=entire_string

Husk også issue #1263

**Comment by jakobkappel** [comment]
Mange tak for hjælpen, @Joergen

Jeg kigger på 1263 :)
