### ISSUE TITLE
KORREKTUR: Mozilla.org/en/banners/firefox-mobile.ftl

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#868]
Ny fil med to strenge:
https://pontoon.mozilla.org/da/mozillaorg/en/banners/firefox-mobile.ftl/?string=212774

**Comment by jakobkappel** [comment]
Det ser fint ud. 

Men sært, at det er to strenge og ikke én. Der er nok noget logik i Fluent, der ikke er helt færdigt endnu.
