### ISSUE TITLE
[KORREKTUR]: Nye strenge til Firefox (deadline: 14/7)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#869]
__Link til strenge markeret "unreviewed" på pontoon.mozilla.org eller ny oversættelse på support.mozilla.org:__
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=213247

__Anden nyttig info til at hjælpe med at forstå sammenhængen for oversættelserne:__
Beklager den korte varsel. Det tog noget længere tid end jeg havde regnet med...

Jeg ved ikke helt, hvordan vi skal gøre ift. korrektur. Men noget i retning af: 
- Godkend dem, der ikke fejler noget
- Kom med forslag til bedre oversættelser (og indsæt link i kommentar + assign til mig)
- Skriv kommentarer på Pontoon (bare for at vi kan se, hvordan det virker)
- Eller hvad du nu lige synes giver bedst mening i gerningsøjeblikket

**Comment by Joergen** [comment]
Jeg har lavet ændringsforslag: https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=212945

**Comment by jakobkappel** [comment]
Tak for hurtig udrykning, @Joergen!
