### ISSUE TITLE
[KORREKTUR]: Seneste strenge til Android

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#870]
__Link til strenge markeret "unreviewed" på pontoon.mozilla.org eller ny oversættelse på support.mozilla.org:__
https://pontoon.mozilla.org/da/android-l10n/all-resources/?status=unreviewed&string=212725

__Link eller instruktion til at teste oversættelsen:__

__Anden nyttig info til at hjælpe med at forstå sammenhængen for oversættelserne:__
Jeg har godkendt næsten alle af dine forslag og er kommet med forslag til de sidste strenge. Assign mig, hvis der er noget, jeg skal kigge på :)

**Comment by Joergen** [comment]
Jeg har rettet et par småting og godkendt strengene.
