### ISSUE TITLE
KORREKTUR: Mozilla.org

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#871]
Der er lavet ændringer i flere filer/sider.
https://pontoon.mozilla.org/da/mozillaorg/en/firefox/all.ftl/?status=unreviewed&string=213192
https://pontoon.mozilla.org/da/mozillaorg/en/firefox/features/bookmarks.ftl/?status=unreviewed&string=213351
https://pontoon.mozilla.org/da/mozillaorg/en/firefox/features/independent.ftl/?status=unreviewed&string=213403
https://pontoon.mozilla.org/da/mozillaorg/en/firefox/features/password-manager.ftl/?status=unreviewed&string=213431

**Comment by jakobkappel** [comment]
Det ser godt ud.

Jeg har et par forslag: 
https://pontoon.mozilla.org/da/mozillaorg/en/firefox/features/bookmarks.ftl/?status=unreviewed&string=213351
https://pontoon.mozilla.org/da/mozillaorg/en/firefox/features/independent.ftl/?status=unreviewed&string=213403
https://pontoon.mozilla.org/da/mozillaorg/en/firefox/features/password-manager.ftl/?status=unreviewed&string=213431

Det er ikke hver dag, man får lejlighed til at anvende ordet "adgangskode-magiker". Men når det så endelig sker, så er det altså med at gribe chancen :D

**Comment by Joergen** [comment]
Tak for det, Jakob
