### ISSUE TITLE
[KORREKTUR]: Nye strenge til Firefox iOS (Deadline: 22. juli)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#872]
__Link til strenge markeret "unreviewed" på pontoon.mozilla.org eller ny oversættelse på support.mozilla.org:__
https://pontoon.mozilla.org/da/firefox-for-ios/firefox-ios.xliff/?status=unreviewed&string=213193

__Link eller instruktion til at teste oversættelsen:__
https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.firefox-ios.l10n-screenshots.latest/da (NB at de har ændret på, hvordan skærmbilleder bliver dannet, så man er lige nu nødt til at hente en zip-fil med samtlige skærmbilleder...)

__Anden nyttig info til at hjælpe med at forstå sammenhængen for oversættelserne:__

**Comment by Joergen** [comment]
Jeg har godkendt og lavet et par ændringsforslag: https://pontoon.mozilla.org/da/firefox-for-ios/firefox-ios.xliff/?status=unreviewed&string=213193 

Der er stadig nogle strenge på skærmbillederne, der er for lange.

Ps. Jeg har ikke modtaget en mail om dette issue.

**Comment by jakobkappel** [comment]
Tak for dét, Jørgen. 

Ift. for lange strenge, er det så fx "Synkronise   de faneblade"? Jeg har tidligere oprettet en bug om problemet. Så blev fejlen rettet (men på grund af en tilsyneladende urelateret kodeændring...) Og så blev den genintroduceret for et par versioner siden (og jeg har ikke haft tid til at kigge på det). 

Hvordan ser det ud, hvis du går til https://github.com/notifications?query=repo%3AMozillaDanmark%2Fmozilla-dk ? 

Og hvad med under "Notifications" til højre forneden på dette issue? Hos mig står der "You’re receiving notifications because you’re watching this repository." Det samme burde være tilfældet hos dig. Hvis dét er tilfældet, så kan mailen måske have fået tæv af dit spamfilter?

**Comment by jakobkappel** [comment]
Hov, @Joergen - bare lige for at helt sikker på, at du får en mail :)

**Comment by Joergen** [comment]
Trunkerede strenge er: 
"Indlæs igen med beskyttelse mod sporing"
"Indlæs igen uden beskyttelse mod sporing"
"Udvidet beskyttelse mod sporing er SLÅET FRA for dette websted"
"Udvidet beskyttelse mod sporing er SLÅET TIL for dette websted"
"Sporings-cookies på tværs af websteder"

Jeg har modtaget mail og der står "You’re receiving notifications because you’re watching this repository." Jeg ved ikke, om der også stod det, før jeg kommenterede issuet. Jeg holder øje med det.

**Comment by jakobkappel** [comment]
Det er også rigtigt. Jeg kan huske, at vi blev enige om, at finde en bedre løsning senere. Det må jo så være sådan lige omkring nu. Jeg opretter et nyt issue og lægger hovedet i blød. Så kan du også se, om notifikationerne virker som de skal.
