### ISSUE TITLE
Få styr på strenge, der bliver trunkeret

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#873]
"Indlæs igen med beskyttelse mod sporing"
"Indlæs igen uden beskyttelse mod sporing"
"Udvidet beskyttelse mod sporing er SLÅET FRA for dette websted"
"Udvidet beskyttelse mod sporing er SLÅET TIL for dette websted"
"Sporings-cookies på tværs af websteder"

**Comment by Joergen** [comment]
Jeg modtog heller ingen mail vedrørende dette issue. Bruger du altid "skabelonen", når du opretter et issue? Prøv uden næste gang eller omvendt.

**Comment by Joergen** [comment]
I de seneste skærmbilleder fra i dag (21 juli) er strengene ombrudt.
