### ISSUE TITLE
[KORREKTUR]: Strenge til Common Voice

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#875]
__Link til strenge markeret "unreviewed" på pontoon.mozilla.org eller ny oversættelse på support.mozilla.org:__
https://pontoon.mozilla.org/da/common-voice/all-resources/?status=unreviewed&string=200845

__Link eller instruktion til at teste oversættelsen:__
Indholdet på denne server opdateres dagligt: https://dev.commonvoice.allizom.org/da (der kan man desværre ikke logge sig ind (pt?).
Anden server der opdateres et par dage før indholdet pushes til selve siden: https://commonvoice.allizom.org/da

**Comment by jakobkappel** [comment]
@Joergen, jeg ville bare lige sikre mig, at du havde set den hér. Hvis ikke, så lad os kigge på din opsætning af notifikationer sammen, når det lige passer ind i planerne.

**Comment by Joergen** [comment]
Jeg har set issuet. Jeg har også kigget på nogle af strengene. Der er et par ting, som vi lige skal have afklaret:
Denne streng består af tre afsnit. Du har kun lavet forslag til den første. https://pontoon.mozilla.org/da/common-voice/web/locales/en/messages.ftl/?status=unreviewed&string=195020

"Clip" er tidligere blevet oversat med "Klip". I dine forslag er det oversat med  "Optagelser".

Du har oversat "Website" med "Hjemmeside" flere steder.

**Comment by jakobkappel** [comment]
> Denne streng består af tre afsnit. Du har kun lavet forslag til den første. https://pontoon.mozilla.org/da/common-voice/web/locales/en/messages.ftl/?status=unreviewed&string=195020

Hov, ja. 

> "Clip" er tidligere blevet oversat med "Klip". I dine forslag er det oversat med "Optagelser".

Det havde jeg ikke lagt mærke til. Men det er ikke helt indlysende. Både "lydklip" og "lydoptagelse" giver mening, men "klip" alene bliver svært at forstå, hvis det ikke kvalificeres yderligere i en sætning, fx "Har du hørt det dér klip med statsministeren, der...?" Når det står alene i en sætning, så synes jeg, at "optagelse" er nemmere at afkode. Og "klip" har jeg på fornemmelsen mest bruges om video, mens "optagelse" især bruges om lyd.

> Du har oversat "Website" med "Hjemmeside" flere steder.

Ja. Uden at tænke nærmere over det. Jeg hverken bruger eller hører "websted" i dagligdagen, så jeg skal virkeligt tvinge mig selv til at bruge det. Men jeg retter lige strengene igennem, når jeg får tid senere.

**Comment by fnielsen** [comment]
Jeg forstår ikke interfacet. Jeg følger https://pontoon.mozilla.org/da/common-voice/all-resources/?status=unreviewed&string=213503 og indtaster "OPTAG DIN STEMME" for record-voice-wave. Trykker SUGGEST. Derefter siger den "Same translation already exists". Hvor kan jeg så reviewe det forslag @jakobkappel kommer med? "v" virker ikke for mig.

"Voicewave" bør også oversættes konsistent.

**Comment by jakobkappel** [comment]
@fnielsen, du havde ikke rettigheder til at gemme strenge. Det har du nu. Dog går der nok lidt tid, inden serveren har vænnet sig til den nye virkelighed.

Gå til https://pontoon.mozilla.org/da/common-voice/web/locales/en/messages.ftl/?status=unreviewed&string=202000

Og tryk derefter på fluebenet ud for dét forslag, du vil godkende: 

![Skærmbillede 2020-07-29 kl  14 24 29](https://user-images.githubusercontent.com/3586612/88799805-58eea580-d1a7-11ea-86e0-fe766c5d5787.png)

---

I tilfælde, hvor du er utilfreds med de nuværende forslag, så må du meget gerne tilføje nye. 

- Du skal først skifte fra review-tilstand ved at klikke på tandhjulet under det lyse tekstfelt og klikke på "Make suggestions" (OPDATERING: Nej, de har lavet noget om. Du kan nøjes med simpelthen at overskrive nuværende forslag og klikke "Suggest")
- Tilføj nye forslag
- Filtrer på Unreviewed, når du er færdig: 

![Skærmbillede 2020-07-29 kl  14 23 13](https://user-images.githubusercontent.com/3586612/88799927-905d5200-d1a7-11ea-830d-b82ce2f7d6a8.png)

- Og indsæt URL'en hér (eller opret et nyt issue) - så læser én af os andre korrektur på dine forslag. 

---

Du har helt ret ift "Voicewave". 

Der er to forekomster: 

1. RECORD VOICEWAVE - hér virker "Optag din stemme" fint
2. Recreate Voicewave - "Gendan din stemme" er knapt så fint. 

Skal vi ikke bare holde det på engelsk?

---

Hvis du støder på andre sære ting på Pontoon, så prøv at kigge på manualen (https://github.com/MozillaDanmark/mozilla-dk/wiki/Vejledning-til-overs%C3%A6ttelse-p%C3%A5-Pontoon) Eller spørg mig eller @Joergen

**Comment by fnielsen** [comment]
Tak. Ja, nu ser det anderledes ud. Jeg har nu reviewet en enkelt "Optag din stemme". Tak for pointers!

**Comment by jakobkappel** [comment]
@fnielsen og @Joergen, jeg har nu gennemgået alle strenge med forslag fra andre end mig selv. 

Vi mangler nu blot https://pontoon.mozilla.org/da/common-voice/all-resources/?status=missing&string=213045 - vil én af jer sige god for strengene (eller eventuelt komme med bedre forslag)? For min skyld kan vi godt gemme de udestående forslag, så vi kan komme videre med projektet - men jeg vil gerne have jeres velsignelse til at gøre det.

**Comment by Joergen** [comment]
Ok - nu har jeg bragt antallet af manglende strenge ned på 4. Jeg har ændret samtlige forekomster af "klip", så nu er der lidt flere strenge, der skal gennemgås/godkendes. https://pontoon.mozilla.org/da/common-voice/all-resources/?status=unreviewed&string=179346

**Comment by fnielsen** [comment]
Bør "klip" ikke være "lydklip"? Hvad burde "voice clip" være? "Stemmelydklip"?

**Comment by jakobkappel** [comment]
"Klip" er røget ud til fordel for "Optagelse". 

Jeg synes dog, at det bliver lidt sært med  "Stemmeoptagelse". Der er jo ikke optagelser af andet end netop stemmer, så skal vi ikke bare holde os til dét? Det betyder selvfølgelig, at vi skal være lidt kreative med nogle af strengene for at undgå "Optag optagelser" (eller finde os i det)

**Comment by fnielsen** [comment]
Optagelse er fint. Jeg har svært ved at se conteksten, f.eks. "Recordings" (optagelser, vel), "Recorded Clips" (optagelser!?). Jeg har prøvet at oversætte et par stykker med "optagelse".

**Comment by jakobkappel** [comment]
Lukker denne - se #1022 

@fnielsen, hvis du har input ift. at få indsamlet sætninger (hvilket jo desværre strandede tidligere), så må du endelig sige til.

**Comment by fnielsen** [comment]
Der er vel indsamlet en del sætninger og der er også udgivet validerede optagelser, så Common Voice må nu gå godt nok for dansk.

**Comment by jakobkappel** [comment]
Ja, det er indsamlet en del. 

Men der er desværre kommet meget med, som nok ikke burde have været det - fx lidt tilfældigt afklippede sætninger fra HC. Andersens tekster (fx "ægtestand, der søges og stævnemøder, som man indlader og ikke indlader sig på!") og en masse sætninger med forældet grammatik og ortografi ("Hvor faae vi en kone til ham" ol.). Der er meget få nutidige sætninger, der overholder de tre kriterier for inklusion: 

- It must be spelled correctly (though slang spellings are allowed).
- It must make sense, and be grammatically correct and self-contained.
- It must be easily speakable, and in the correct language.

**Comment by fnielsen** [comment]
Ja. Jeg afviste en række sætninger, men der kom nok mange med alligevel.

**Comment by jakobkappel** [comment]
Jeg forstår ikke helt, hvad der er sket. Langt hovedparten af de danske sætninger ser ud til at stamme fra 1830'erne...

Kigger man på https://github.com/common-voice/common-voice/blob/main/server/data/da/sentence-collector.txt, så er der over 20.000 sætninger tilføjet, som for de fleste vedkommende ser ud til at komme fra HC. Andersens eventyr. Jeg prøver at åbne et issue og få dem fjernet.

**Comment by jakobkappel** [comment]
Ah, https://github.com/common-voice/sentence-collector/issues/411
