### ISSUE TITLE
[KORREKTUR]: Firefox Send

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#876]
https://pontoon.mozilla.org/da/test-pilot-firefox-send/send.ftl/?status=unreviewed&string=213898

Deadline 29 juli.

**Comment by jakobkappel** [comment]
Det ser godt ud, Jørgen. 

Jeg har et enkelt forslag: https://pontoon.mozilla.org/da/test-pilot-firefox-send/all-resources/?status=unreviewed&string=213895

"abusive" er ikke særligt entydigt i sammenhængen - men jeg tænker, at Mozilla gerne vil slippe for henvendelser, hvis nogen føler sig stødt over et eller andet (der strengt taget mere handler om, at de selv måske er lidt sippede).

**Comment by Joergen** [comment]
Godkendt
