### ISSUE TITLE
[KORREKTUR]: Strenge til WebThings

### ISSUE THREAD

**Issue by SuneKuntz** [MozillaDanmark/mozilla-dk#877]
__Link til strenge markeret "unreviewed" på pontoon.mozilla.org eller ny oversættelse på support.mozilla.org:__
https://pontoon.mozilla.org/da/webthings-gateway/main.ftl/?status=unreviewed&string=206279

**Comment by jakobkappel** [comment]
Det ser rigtigt fint ud, @SuneKuntz - godt arbejde!

---
Jeg har godkendt hovedparten af dine forslag, og så har jeg rettet nogle af dem ud fra følgende kriterier: 

1. Tastefejl ol. 
2. Konsistens ift. hvordan begreber oversættes i andre Mozilla-produkter (fx "password" > "adgangskode").  
3. Lidt grammatik-ting som fx [nogen/nogle](https://sproget.dk/raad-og-regler/typiske-problemer/nogen-eller-nogle)

Du kan se rettelserne her: https://pontoon.mozilla.org/da/webthings-gateway/main.ftl/?author=jakobkpetersen%40gmail.com&string=206586, hvis du har lyst (markeret med grønt). Jeg har skrevet kommentarer til flere af dem, så du kan se, hvorfor jeg har rettet. NB at funktionen med kommentarer er ret ny, og jeg har ikke vænnet mig helt til den endnu. Derfor er nogle kommentarer skrevet det forkerte sted (til strenge, når det i virkeligheden skulle have været en kommentar til en oversættelse)

---
Desuden har jeg lavet en række alternative forslag, hvor det nok mere er et smagsspørgsmål, om det skal være det ene eller det andet. Og så er der nogle strenge, som jeg ikke synes virker helt optimalt - dér har jeg skrevet kommentarer. 

Du kan se forslagene her: https://pontoon.mozilla.org/da/webthings-gateway/main.ftl/?status=missing&string=206318

Jeg har ikke godkendt forslagene med "web thing", da jeg synes at vi skal prøve at finde en løsning, der fungerer for folk, som ikke kan engelsk. Så enten skal vi opfinde ordet “web-ting” el. eller bruge “enhed”, som du også har gjort i et par af strengene med “Thing” (hvor det jo fungerer fint). 

**Bindestreger**. Vi anvender normalt bindestreger i usædvanlige, sammensatte ord for at gøre dem nemmere at afkode. Jeg er også stor fan af at hjælpe folk, der ikke er så gode til at læse, ved af at sætte bindestreger i mere almindelige sammensatte ord, fx hvis der er sære stavelsessammenstød eller gentagelse af identiske stavelser. Eksempelvis “Bevægelsessensor”. 

Jeg synes, at du skal have det sidste ord. Det er jo trods alt dig, der har ansvaret for, at projektet overhovedet er blevet til noget på dansk. Så jeg har ændret dine tilladelser, sådan at du kan godkende forslag. Det gør du ved at klikke på fluebenet ud for det forslag, du synes er bedst. 

Hvis der er nogle strenge, hvor du ikke kan se, hvad der er den bedste løsning - så skriv endelig hér. Så kan vi forhåbentlig finde på noget i fællesskab :)

---

Der foregår noget sært på pontoon-serveren for tiden. Ved flere strenge ser det sådan ud: 

![Skærmbillede 2020-07-30 kl  10 39 57](https://user-images.githubusercontent.com/3586612/88901472-1d101a80-d251-11ea-94a4-54f43ba8e04f.png)

Det burde dog ikke betyde noget ift. at strengene bliver håndteret korrekt på deres videre rejse mod det endelige produkt.

**Comment by SuneKuntz** [comment]
Jeg har nu læst alle rettelser og forslag igennem, og har samtidigt fået godkendt dem.

Med hensyn til "Web thing" så tænker jeg personligt, at ordet "enhed" egner sig bedst. Som du selv nævner, så har jeg brugt ordet i andre strenge. Derudover er der ikke en beskrivelse for, hvad 'web ting' er og dækker over, hvilket måske kunne forvirre.

**Comment by Joergen** [comment]
"Jeg kan godt lide "Web thing". Vi oversætter heller ikke "Web of Things" og "Internet of things".

**Comment by SuneKuntz** [comment]
Men "web of things" og "internet of things" bliver også brugt flere steder, hvor "web thing" (så vidt jeg kan se) er et ord Mozilla har opfundet.

**Comment by jakobkappel** [comment]
Jeg har også svært ved at regne ud, hvad "Web Thing" præcis skulle være. Kan det måske simpelthen handle om en enhed udenfor éns lokale netværk? 

I udgangspunktet vil jeg foretrække, hvis vi kunne finde et godt ord på dansk. Men på den anden side er det nok så tilpas nørdet et hjørne af virkeligheden, at det nok lige går, hvis det er på engelsk.

Og så er oversættelser jo ikke skrevet i sten. Så hvis vi ender med en løsning, der viser sig ikke at fungere i praksis - så er det jo bare at lave det om :)

**Comment by SuneKuntz** [comment]
Når jeg kigger WebThings igennem, som jeg nu har kørende på en Raspberry Pi, så har jeg svært ved at gennemskue, hvor strengen specifikt optræder. Jeg har derfor svært ved at gennemskue, om ordet "Enhed" overhovedet giver mening i konteksten strengen optræder i. 

Pointen med at folk nok er lidt nørdet når de roder med WebThings (og derfor nok kender til ordene "Web" og "Things") kan jeg dog godt forstå

**Comment by jakobkappel** [comment]
Ok, hvis vi ikke er sikre på, om "enhed" fungerer i sammenhængen (hvad end sammenhængen så er...), så synes jeg bare, at vi skal lade være med at oversætte udtrykket. 

Jeg går også i gang med at nørkle med det, så snart jeg har tid. Så mon ikke én af os støder på strengene lige pludselig?

**Comment by jakobkappel** [comment]
@SuneKuntz, så har jeg fået tid til at kigge lidt nærmere på det. 

En "Web Thing" er en repræsentation af en fysisk enhed beskrevet i overensstemmelse med API'en beskrevet på https://iot.mozilla.org/wot/ Se også https://iot.mozilla.org/framework/

Så det giver fint mening at beholde udtrykket på engelsk. 

---

Jeg har tilføjet projektet på vores liste over [projekter på Pontoon](https://github.com/MozillaDanmark/mozilla-dk/wiki/Oversigt-over-projekter-p%C3%A5-Pontoon). Vil du måske kigge teksten igennem og melde tilbage, hvis du har bedre forslag? 

---

Nå jo, og så er der kommet en ny streng: https://pontoon.mozilla.org/da/webthings-gateway/all-resources/?status=missing&string=214564

Pontoon er stadig under udvikling, så det er pt. ikke muligt at modtage notifikationer fra et enkelt projekt. Det bliver forhåbentlig lavet om snart. En helt anden måde at gøre det på er at holde øje med https://github.com/mozilla-iot/gateway/blob/master/static/fluent/en-US/main.ftl (hvor nye engelske strenge tilføjes).

**Comment by SuneKuntz** [comment]
Ja, så er der vidst ingen tvivl om, at Web Thing ikke skal oversættes :) 

Jeg får kigget teksten og strenge igennem, og melder tilbage.

**Comment by SuneKuntz** [comment]
@jakobkappel jeg kan godt lide beskrivelsen af projektet :) En absolut lille ting, kunne måske være at tilføje forkortelsen for Internet of Things "Mozilla WebThings er et projekt, hvis formål er at skabe et decentraliseret Internet of Things (IoT)." Ellers har jeg ingen forbedringsforslag.

**Comment by jakobkappel** [comment]
@SuneKuntz 

Rigtigt god pointe. Jeg retter.

**Comment by jakobkappel** [comment]
Hov, jeg havde glemt at lukke issuet hér. 

NB at projektets fremtid er uvis efter de seneste omorganiseringer hos Mozilla: 

"The team is completely dissolved due to the reorg. At the moment, the project would not take any new language requests or update the repo with changes in Pontoon. The project is actively working to move into a community-maintained state. We will update everyone as soon as that information becomes available."

(https://blog.mozilla.org/l10n/2020/08/28/l10n-report-august-2020-edition/)
