### ISSUE TITLE
[KORREKTUR]: Thunderbird.net

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#879]
https://pontoon.mozilla.org/da/thunderbirdnet/LC_MESSAGES/messages.po/?status=unreviewed&string=214045

https://www-stage.thunderbird.net/da/calendar/

**Comment by jakobkappel** [comment]
Det ser fint ud - jeg har et enkelt forslag: https://pontoon.mozilla.org/da/thunderbirdnet/LC_MESSAGES/messages.po/?status=missing&string=214043

**Comment by Joergen** [comment]
Godkendt
