### ISSUE TITLE
[KORREKTUR]: Donate website UI

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#880]
2 strenge er blevet ændret: https://pontoon.mozilla.org/da/mozilla-donate-website/LC_MESSAGES/django.po/?status=unreviewed&string=213815

Den ene streng kan ses live her: https://give.thunderbird.net/da/

**Comment by jakobkappel** [comment]
Jeg har lavet et alternativt forslag til den ene af strengene: https://pontoon.mozilla.org/da/mozilla-donate-website/LC_MESSAGES/django.po/?status=missing&string=213815 "Dit privatliv er vigtigt for Mozilla" er lidt svær at forstå, synes jeg. Men du bestemmer

**Comment by Joergen** [comment]
Godkendt
