### ISSUE TITLE
Mozilla.org/en/firefox/features/index.ftl

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#884]
https://pontoon.mozilla.org/da/mozillaorg/en/firefox/features/index.ftl/?string=213438

https://www-dev.allizom.org/da/firefox/features/

**Comment by jakobkappel** [comment]
@Joergen, jeg har godkendt de fleste af dine forslag, er kommet med forslag til ændringer og har foreslået oversættelser til de manglende strenge.

"{ -brand-name-firefox } is the fast, lightweight, privacy-focused browser that works across all your devices." er svær. Eller "lightweight" er svær. Jeg synes, det er svært at forstå, hvad det skal betyde, at en browser er "let" el. Mon ikke de tænker på hukommelsesforbruget? Og hvordan pokker skal man beskrive det med et tillægsord? Jeg kan ikke komme tanke om andet end simpelthen at droppe det helt, hvilket man kunne forsvare ved, at dét med hukommelse i grunden også handler om hastighed. Fx "{ -brand-name-firefox } er den hurtige, privatlivs-fokuserede browser, der virker på alle dine enheder."

**Comment by Joergen** [comment]
Godkendt
