### ISSUE TITLE
[KORREKTUR]: Mozilla.org/en/firefox/whatsnew/whatsnew-account.ftl

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#886]
https://pontoon.mozilla.org/da/mozillaorg/en/firefox/whatsnew/whatsnew-account.ftl/?status=unreviewed&string=214698

Skulle være denne siden på stage-serveren: https://www-dev.allizom.org/da/firefox/60.0/whatsnew/all/

**Comment by jakobkappel** [comment]
Jeg kan ikke få vist strengene - men de er vel også så tilpas lige ud ad landevejen, at det ikke kan gå helt galt. 

Dog er jeg i tvivl om "Use { -brand-name-firefox } for mobile." Så vidt jeg kan regne ud skal "mobile" dække over telefoner + tablets - og så bliver "mobilen" forkert. Hvad med simpelthen "telefoner og tablets"?

**Comment by Joergen** [comment]
Her er et skærmbillede fra den engelske side, efter jeg har manipuleret med en css-regel display:none.
Der må være tale om en telefon.

![Get_more_done ](https://user-images.githubusercontent.com/3466269/90958464-039b7080-e495-11ea-970b-6035a968e9ff.png)

**Comment by jakobkappel** [comment]
Det har du helt ret i. 

Gad vide, hvor SMS-strengen dukker op henne?

**Comment by Joergen** [comment]
??

**Comment by jakobkappel** [comment]
Ja, det fik jeg da formuleret helt forkert. Jeg mente: Hvor kan vi oversætte SMS-strengen henne?

**Comment by jakobkappel** [comment]
Jeg har fundet den (og den er oversat)
