### ISSUE TITLE
Tre nye strenge til mozilla.org

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#888]
https://pontoon.mozilla.org/da/mozillaorg/en/banners/firefox-daylight-launch.ftl/?status=unreviewed&string=214864

Det kommer til at se nogenlunde sådan ud: 

![Skærmbillede 2020-08-27 kl  20 33 03](https://user-images.githubusercontent.com/3586612/91481505-d5f36480-e8a4-11ea-9020-71de991f2141.png)

**Comment by Joergen** [comment]
Godkendt
