### ISSUE TITLE
[KORREKTUR]: Firefox til Android (Deadline 6. sept)

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#889]
https://pontoon.mozilla.org/da/android-l10n/all-resources/?status=unreviewed&string=214629

**Comment by jakobkappel** [comment]
Det ser godt ud. 

Jeg har gemt alle - og har to ændringsforslag: 

https://pontoon.mozilla.org/da/android-l10n/all-resources/?status=missing&string=214852

**Comment by Joergen** [comment]
Godkendt
