### ISSUE TITLE
[[Korrektur]] Mozilla.org/en/firefox/features/shared.ftl

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#890]
Det ser ud til, at der er strenge, der deles af flere sider: https://pontoon.mozilla.org/da/mozillaorg/en/firefox/features/shared.ftl/?string=213398

https://www-dev.allizom.org/da/firefox/features/

**Comment by Joergen** [comment]
https://pontoon.mozilla.org/da/mozillaorg/en/firefox/features/shared.ftl/?status=unreviewed&string=213401

**Comment by jakobkappel** [comment]
Det ser også godt ud. Men det er godt nok lidt af en tanketorsk, at de beder folk oversætte "{ -brand-name-firefox }"...
