### ISSUE TITLE
[KORREKTUR]: Firefox til Android

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#891]
https://pontoon.mozilla.org/da/android-l10n/all-resources/?status=unreviewed&string=214895

Udviklerne besluttede, at de lige ville have yderligere 14 strenge med i denne ombæring.

**Comment by Pokersut** [comment]
Alle godkendt på nær én, hvor du vist havde læst forkert 🙂

**Comment by Joergen** [comment]
Tak for det, @Pokersut
