### ISSUE TITLE
[KORREKTUR]: Nye strenge til Firefox iOS (Deadline: 7/9)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#892]
https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed&string=214766

Skærmbilleder: https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.firefox-ios.l10n-screenshots.latest/da

@Joergen, jeg har gemt alle dine forslag og tilføjet forslag til de manglende oversættelser.

**Comment by Joergen** [comment]
Jeg har godkendt og lavet ændringsforslag til fire strenge. Se kommentarerne ud for to af forslagene. 
https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed&string=214788

**Comment by jakobkappel** [comment]
Det var nogle fine forslag, så jeg gemte allesammen. Tak for hjælpen!
