### ISSUE TITLE
[KORREKTUR]: Strenge til diverse Mozilla.org-sider

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#893]
https://pontoon.mozilla.org/da/mozillaorg/en/banners/firefox-daylight-launch.ftl/?status=unreviewed&string=214912

https://pontoon.mozilla.org/da/mozillaorg/en/firefox/channel.ftl/?status=unreviewed&string=214695
Stage: https://www-dev.allizom.org/da/firefox/channel/desktop/

https://pontoon.mozilla.org/da/mozillaorg/en/firefox/facebook_container.ftl/?status=unreviewed&string=214950
Stage: https://www-dev.allizom.org/da/firefox/facebookcontainer/  muligvis kun synlig på en mobil

https://pontoon.mozilla.org/da/mozillaorg/en/firefox/mobile.ftl/?status=unreviewed&string=214637
Stage: https://www-dev.allizom.org/en-US/firefox/mobile/ streng synlig på den engelske side

**Comment by jakobkappel** [comment]
Det ser godt ud - jeg har gemt alle forslag.
