### ISSUE TITLE
[KORREKTUR]: En håndfuld nye strenge til mozilla.org

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#894]
https://pontoon.mozilla.org/da/mozillaorg/en/firefox/whatsnew/whatsnew-fx81.ftl/?status=unreviewed&string=214958

Jeg kan desværre ikke regne ud, hvor strenge bliver vist henne. 

@Joergen, ved du det?

**Comment by Joergen** [comment]
https://www-dev.allizom.org/firefox/81.0/whatsnew/all/

På nogle sprog viser siden strengene vedrørende QR-koden og på andre sprog vises en formular til indtastning af mailadresse. (Dansk, Tysk)

**Comment by jakobkappel** [comment]
Tak, Jørgen

Det var i øvrigt en sjov detalje, at der ikke vises det samme på alle sprog. Men det er mit indtryk at QR-koder havde en meget kort storhedstid i Danmark - det er sikkert det samme andre steder.

**Comment by Joergen** [comment]
Jeg har sjovet nok lige brugt en QR-kode i dag. Red Barnet samlede ind med QR-kode og Mobile Pay.

**Comment by jakobkappel** [comment]
Ja, det var da et pudsigt sammentræf. Og idéen er jo rigtigt god. Jeg tror dog, at mange blev skræmt væk i starten, hvor alle reklamebureauer gik helt bersærk med koderne - og man skulle trykke 117 gange på sin telefon for at skanne dem.

**Comment by Joergen** [comment]
Jeg har lavet ændringsforslag til et par af strengene: https://pontoon.mozilla.org/da/mozillaorg/en/firefox/whatsnew/whatsnew-fx81.ftl/?status=unreviewed&string=214953

**Comment by jakobkappel** [comment]
For pokker. Den hér var simpelthen røget for langt ned i dyngerne... Men nu har jeg godkendt forslagene
