### ISSUE TITLE
Få styr på bøvl med picture-in-picture-toggle-shortcut-mac-alt

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#897]
https://pontoon.mozilla.org/da/firefox/browser/browser/browserSets.ftl/?string=215076

der refererer til 

https://pontoon.mozilla.org/da/firefox/browser/browser/browserSets.ftl/?string=215069

Kommentar fra Jørgen: 

Ud fra kommentaren tror jeg, at du skal vælge tasten, der er over tasten, der bruges i denne genvej: -mac&string=215069 På et Windows-tastatur er det tasten ). Der findes lignende tastaturgenveje til Windows, men de virker så vidt jeg kan se ikke. Måske er det bedst at spørge et sted. Både ] og } krævet Alt Gr-tasten i Windows, Se engelsk layout her, hvor der ikke kr: https://en.wikipedia.org/wiki/Keyboard_layout#/media/File:Qwerty.svg

**Comment by Joergen** [comment]
På Windows + Linux skulle tastaturgenvejen være **Ctrl+Skift+]** eller **Ctrl+Skift+}**. Efter at have tjekket diverse bug-rapporter, fandt jeg denne på Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1611154

**Comment by Joergen** [comment]
Jeg har lavet forslag til de to alternative genveje til Mac og Windows. 
https://pontoon.mozilla.org/da/firefox/all-resources/?search=picture-in-picture-toggle-shortcut&string=215069

https://transvision.mozfr.org/?recherche=picture-in-picture-toggle-shortcut&repo=gecko_strings&sourcelocale=en-US&locale=da&search_type=entities

**Comment by jakobkappel** [comment]
@Joergen, det virker som en god løsning. Tak for hjælpen!
