### ISSUE TITLE
Et par nye strenge til Android L10n

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#898]
https://pontoon.mozilla.org/da/android-l10n/all-resources/?status=missing&string=215269

@Joergen, jeg har gemt dine forslag - og har to nye. 

Jeg kom forresten i tvivl om strengene med "clear" ("Clear password", "Clear username") efter at jeg godkendte dem. Er det måske bedre med "Slet..."?

**Comment by Joergen** [comment]
Jeg synes "Ryd" er ok. Først vælger man mellem "Slet" og "Rediger" i en menu. "Slet" sletter hele det gemte login fra Firefox. Vælger man i stedet "Rediger, kan man redigere adgangskoden og brugernavnet. På skærmen er det muligt at trykke på et X ud for Brugernavn, så feltet Brugernavn ryddes. Trykker man på X'et ud for Adgangskode, så ryddes feltet Adgangskode. Strengene er til en skærmlæser.

**Comment by DAF-admin** [comment]
Ok, så er jeg med. Og jeg er helt enig.

**Comment by DAF-admin** [comment]
> Ok, så er jeg med. Og jeg er helt enig.

Hov, jeg er logget ind med en arbejdskonto...

/Jakob
