### ISSUE TITLE
Nye strenge til Firefox

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#902]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=215698

**Comment by Joergen** [comment]
Jeg har lavet ændringsforslag: https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=215688

**Comment by jakobkappel** [comment]
Perfekt, mange tak. Jeg har gået dine forslag igennem, gemt de fleste og rettet et par småting. Og så skal jeg lige huske mig selv på at læse de dér kommentarer fra udviklerne...
