### ISSUE TITLE
[Oversættelse/Korrektur]: Mozilla.org/en/firefox/new/desktop.ftl 	

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#904]
Der er lavet forslag til 119 af 122 strenge.
https://pontoon.mozilla.org/da/mozillaorg/en/firefox/new/desktop.ftl/?status=missing&string=215012
Stage: https://www-dev.allizom.org/da/firefox/new/ og https://www-dev.allizom.org/da/firefox/download/thanks/

**Comment by jakobkappel** [comment]
Det ser rigtigt fint ud, @Joergen 

Jeg har føjet en håndfuld forslag til: https://pontoon.mozilla.org/da/mozillaorg/en/firefox/new/desktop.ftl/?status=missing&string=213995

Har du forresten været i kontakt med ham Mads?

**Comment by Joergen** [comment]
Nej, men jeg har kontaktet Sune vedr. WebThings Gateway

**Comment by Joergen** [comment]
Tak, @jakobkappel. Jeg har godkendt dine forslag.
