### ISSUE TITLE
[KORREKTUR]: Mozilla.org/en/firefox/whatsnew/whatsnew-s2d.ftl

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#905]
2 nye strenge: https://pontoon.mozilla.org/da/mozillaorg/en/firefox/whatsnew/whatsnew-s2d.ftl/?status=missing&string=214691
Stage (Engelsk): https://www-dev.allizom.org/en-US/firefox/whatsnew/all/

**Comment by jakobkappel** [comment]
@Joergen Det er altså svært med streng, der indeholder "privacy". Bliver det ikke mere dækkende med "beskyttelse af dit privatliv"?

Og måske "Det kan du få med { -brand-name-firefox } til mobilen."

**Comment by Joergen** [comment]
Ændret.
