### ISSUE TITLE
[KORREKTUR]: Mozilla.org/en/footer.ftl

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#907]
Syv nye strenge: https://pontoon.mozilla.org/da/mozillaorg/en/footer.ftl/?status=unreviewed&string=216314
Stage (engelsk): https://www-demo1.allizom.org/en-US/

**Comment by jakobkappel** [comment]
Det ser fint ud, @Joergen 

Jeg ombestemte mig med en sidste streng, jeg var lidt i tvivl om. Det er jeg ikke længere, så den er gemt - og jeg lukker her :)
