### ISSUE TITLE
[KORREKTUR]: WebThings Gateway

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#909]
Ni nye strenge: https://pontoon.mozilla.org/da/webthings-gateway/main.ftl/?status=unreviewed&string=214967

**Comment by jakobkappel** [comment]
Jeg har gemt de fleste og har lavet et par forslag til nogle af strengene: 

https://pontoon.mozilla.org/da/webthings-gateway/main.ftl/?status=unreviewed&string=215441

@SuneKuntz og @Joergen - er der én af jer, der gider kigge på dem?

**Comment by Joergen** [comment]
Der er lige kommet en stak nye strenge til projektet!

**Comment by Joergen** [comment]
Jeg har godkendt nogle af de nye strenge og lavet ændringsforslag til resten:
https://pontoon.mozilla.org/da/webthings-gateway/main.ftl/?status=unreviewed&string=217031

@jakobkappel  eller @SuneKuntz - hvis en af jer har tid.

**Comment by jakobkappel** [comment]
Og _så_ fik jeg tid til at kigge på det :)

**Comment by jakobkappel** [comment]
Jeg har gået alle forslag igennem og har gemt, så der nu er lige præcis 0 manglende strenge. Godt arbejde, begge to!
