### ISSUE TITLE
[KORREKTUR]: Donate - Mozilla content, Donate - Thunderbird content og Donate website - UI

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#910]
Donate - Mozilla content. To strenge: https://pontoon.mozilla.org/da/donate-mozilla-content/templates/pages/mozilla-donate.pot/?string=216742

Efter en synkronisering dukkede der en ny fil op med 59 strenge. Jeg har lavet forslag (baseret på de "gamle" strenge) til 54 af de 59 strenge: https://pontoon.mozilla.org/da/donate-mozilla-content/templates/pages/mozilla-donate/faq.pot/?string=216797

Donate - Thunderbird content. Fire strenge: https://pontoon.mozilla.org/da/donate-thunderbird-content/templates/pages/mozilla-donate.pot/?string=216741

Donate website - UI. 11 strenge: https://pontoon.mozilla.org/da/mozilla-donate-website/LC_MESSAGES/django.po/?status=unreviewed&string=216607

https://donate.mozilla.org/da/
https://give.thunderbird.net/da/

**Comment by jakobkappel** [comment]
Det ser rigtigt fint ud, @Joergen 

Jeg har rettet nogle småfejl, og så er der følgende forslag: 

https://pontoon.mozilla.org/da/donate-mozilla-content/templates/pages/mozilla-donate/faq.pot/?status=missing&string=216744

https://pontoon.mozilla.org/da/donate-thunderbird-content/templates/pages/mozilla-donate.pot/?status=missing&string=216738

**Comment by Joergen** [comment]
Rettet et par småting og godkendt.
