### ISSUE TITLE
[KORREKTUR]: Nye strenge til Android L10n

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#912]
https://pontoon.mozilla.org/da/android-l10n/all-resources/?status=missing&string=216612

@Joergen, jeg har gennemgået og gemt dine forslag. 

Jeg er i tvivl om de to med "controller". Måske lyder "styreenhed" lidt gammeldags? Hvis det handler om sådan nogle dimser til spillekonsoller, så har jeg i hvert fald kun hørt det omtalt på engelsk.

**Comment by Joergen** [comment]
Jeg har godkendt alle undtagen to. I Android L10n har vi oversat "Top site" med "Foretrukne websteder" de fleste steder. Det foretrækker jeg. Der er nemlig en engelsk streng "Show most visited sites", der er oversat med "Vis mest besøgte websteder". https://transvision.mozfr.org/?recherche=Top+site&repo=android_l10n&sourcelocale=en-US&locale=da&search_type=strings
Jeg havde lavet et ændringsforslag til en af de ældre gemte strenge. Nu har jeg også lavet et til et af dine nye forslag.  
https://pontoon.mozilla.org/da/android-l10n/mozilla-mobile/fenix/app/src/main/res/values/strings.xml/?status=unreviewed&string=216237

Jeg har ikke noget bud på de to "controllere" til Firefox Reality.

**Comment by jakobkappel** [comment]
Du har helt ret ift. oversættelsen af "top site". 

Jeg har godkendt dine forslag :)
