### ISSUE TITLE
[KORREKTUR]: Donate - Mozilla content, Donate - Thunderbird content og Donate website - UI

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#913]
Fem strenge. Der dukkede (som sædvanligt) nogle nye og lettere omskrevne strenge op.

https://pontoon.mozilla.org/da/donate-mozilla-content/templates/pages/mozilla-donate/faq.pot/?status=unreviewed&string=217338
https://pontoon.mozilla.org/da/donate-thunderbird-content/templates/pages/mozilla-donate/help.pot/?status=unreviewed&string=217304
https://pontoon.mozilla.org/da/mozilla-donate-website/LC_MESSAGES/django.po/?status=unreviewed&string=217337

**Comment by jakobkappel** [comment]
Beklager, den hér var røget under min radar. Jeg har gemt alle forslag
