### ISSUE TITLE
[KORREKTUR]: Mozillaorg/en/firefox/features/index.ftl

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#914]
Syv nye strenge: https://pontoon.mozilla.org/da/mozillaorg/en/firefox/features/index.ftl/?status=unreviewed&string=217980

Stageserver (de nye strenge vises kun på den engelske side): https://www-dev.allizom.org/en-US/firefox/features/

**Comment by Pokersut** [comment]
Alle strenge godkendt!
