### ISSUE TITLE
[KORREKTUR/OVERSÆTTELSE]: Android L10n. Deadline 29 december

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#915]
Jeg har lavet forslag til 14 af 15 strenge - så der mangler én.

https://pontoon.mozilla.org/da/android-l10n/all-resources/?status=missing&string=217742

**Comment by jakobkappel** [comment]
@Joergen, jeg synes at det forslag, @Pokersut er kommet med, fungerer fint. Men måske med en bindestreg, "faneblads-tæller"? Sikke et ord :)

**Comment by Joergen** [comment]
Jeg har godkendt forslaget. Jeg tror, at strenge hvor kommentaren indeholder "Content description", er til skærmlæsere. Så jeg har droppet bindestregen.

**Comment by jakobkappel** [comment]
Det tror jeg, du har ret i. Vi kan evt. lige tjekke med flod eller én af de andre, når de er tilbage fra ferie.
