### ISSUE TITLE
"Firefox blokerede mere end xxx sporings-mekanismer" > "...har blokeret..."?

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#916]
![Skærmbillede 2021-01-03 kl  15 57 26](https://user-images.githubusercontent.com/3586612/103481743-2d6a8980-4ddd-11eb-8102-bfa933aeced0.png)

**Comment by Joergen** [comment]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=missing&string=219986
https://pontoon.mozilla.org/da/firefox/all-resources/?search=sporings-mekanismer+siden&string=204810

Den første streng er vist den nye udgave af den, du har taget skærmbillede af.

**Comment by jakobkappel** [comment]
Det tror jeg, at du har helt ret i. Jeg kigger lige de andre strenge igennem og lukker hér, når jeg er færdig.
