### ISSUE TITLE
[KORREKTUR]: Mozilla.org/en/banners/fundraising.ftl

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#920]
Seks nye strenge: https://pontoon.mozilla.org/da/mozillaorg/en/banners/fundraising.ftl/?status=unreviewed&string=217976

https://www-dev.allizom.org/en-US/

**Comment by jakobkappel** [comment]
Jeg har to ændringsforslag: 

https://pontoon.mozilla.org/da/mozillaorg/en/banners/fundraising.ftl/?status=missing&string=217976

**Comment by Joergen** [comment]
Rettet et par slåfejl og godkendt dine forslag.
