### ISSUE TITLE
[KORREKTUR]: Mozilla.org/en/firefox/developer.ftl

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#921]
Nye og rettede strenge: https://pontoon.mozilla.org/da/mozillaorg/en/firefox/developer.ftl/?status=unreviewed&string=217918

Strengene er kun synlige på den engelske stage-side: https://www-dev.allizom.org/en-US/firefox/developer/

**Comment by jakobkappel** [comment]
Tre forslag: https://pontoon.mozilla.org/da/mozillaorg/en/firefox/developer.ftl/?status=missing&string=217915

@Joergen, ved du forresten, hvordan man på en nem måde kan finde ud af, hvad indholdet i variabler som fx { -brand-name-developer-edition } er? Transvision kan ikke hjælpe, og det virker lidt bagvendt at lede efter det på de forskellige websteder.

**Comment by Joergen** [comment]
@jakobkappel  Jeg har godkendt dine forslag.
Nej. Da jeg lavede forslag til siden, kiggede jeg på den engelske side på stage-serveren. Fx kiggede jeg efter, hvad { -brand-name-beta } var.
