### ISSUE TITLE
[KORREKTUR]: Firefox til iOS. Deadline 17. februar

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#922]
https://pontoon.mozilla.org/da/firefox-for-ios/firefox-ios.xliff/?status=unreviewed&string=220029

Én streng er ikke oversat. Strengen "1Password Fill Browser Action" skal ifølge Delphine ikke oversættes.

**Comment by jakobkappel** [comment]
@Joergen, jeg har godkendt forslagene. 

Men det undrer mig, at hun ikke mener at strengen 1Password skal oversættes. Og det har mange af de andre sprog i øvrigt gjort. 

Skal vi bare "oversætte" med den engelske streng eller hvad synes du?

**Comment by Joergen** [comment]
Fra Notifications på Pontoon https://pontoon.mozilla.org/notifications/: 
"delphine has sent a message in Firefox for iOS

1 week, 3 days ago
You may have seen that there is a strange string that fell through the cracks as part of the latest iOS export: "1Password Fill Browser Action". Please feel free to ignore it, it will be removed at our next export. If you've already translated, don't worry about that either. Thank you and sorry for any confusion that might have led to"
