### ISSUE TITLE
Forkerte eller dobbelte Access Keys

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#928]
Jeg har fundet nogle dobbelte Access Keys i Firefox:

- Tag snapshot… 
https://pontoon.mozilla.org/da/firefox/all-resources/?search=Tag+snapshot&string=220968
**s** ændres til **T**
- Tilføj separator
https://pontoon.mozilla.org/da/firefox/all-resources/?search=Tilf%C3%B8j+separator&string=220733
**p** ændres til **e**

Der er sikkert flere end ovenstående. Luk ikke issuet, men slet punkterne, når fejlene er rettet og rettelserne bekræftet.

**Comment by jakobkappel** [comment]
@Joergen, jeg har lavet ændringerne - med en enkelt undtagelse (se ovenfor).

**Comment by Joergen** [comment]
Åh, jeg havde ikke lige tænkt på, at udvalget kunne være begrænset. Men jeg har prøvet at indtaste "o" i feltet med "k" og gemt. Jeg tjekker i morgen, om det lykkedes at ændre genvejen på den måde.

**Comment by jakobkappel** [comment]
O-k :)

**Comment by jakobkappel** [comment]
@Joergen 

Jeg har føjet forslag til ift. de to sidste på listen: 

https://pontoon.mozilla.org/da/firefox/all-resources/?search=Tag+snapshot&string=220968
https://pontoon.mozilla.org/da/firefox/all-resources/?search=Tilf%C3%B8j+separator&string=220733

Mangler vi mere for at kunne lukke issuet?

**Comment by Joergen** [comment]
Der er nogle sammenfald, der er af ældre dato. Jeg orker ikke at løse dem pt. Det vil sikkert kræve, at flere strenge skal ændres, da der er et begrænset antal bogstaver at vælge mellem.

**Comment by jakobkappel** [comment]
Nej, lad os kigge på det igen, når vi støder på noget, der ser helt forkert ud. 

Vil du ikke dobbelttjekke de to forslag i min foregående kommentar og så lukke issuet?

**Comment by Joergen** [comment]
Jeg har rettet, så de stemmer med mine forslag. 
Du havde ikke lavet et nyt forslag til https://pontoon.mozilla.org/da/firefox/all-resources/?search=Tilf%C3%B8j+separator&string=220733

**Comment by jakobkappel** [comment]
> Jeg har rettet, så de stemmer med mine forslag.
> Du havde ikke lavet et nyt forslag til https://pontoon.mozilla.org/da/firefox/all-resources/?search=Tilf%C3%B8j+separator&string=220733

Hov, jeg glemte viste at trykke på knappen...
