### ISSUE TITLE
For lang oversættelse af "Bookmark Current Tab"

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#929]
Oversættelsen af "Bookmark Current Tab" med "Gem bogmærke til det aktuelle faneblad" er for lang det ene af stederne. Tidligere har vi oversat  "Bookmark This Tab…" med "Bogmærk dette faneblad…".
![Gem bogmærke](https://user-images.githubusercontent.com/3466269/111456797-b83dfd80-8717-11eb-9f44-62b4bc2d2e75.png)
Bemærk, at jeg har rettet "Senester bogmærker" til "Seneste bogmærker".

**Comment by Joergen** [comment]
https://transvision.mozfr.org/?recherche=Bookmark+Current+Tab&repo=gecko_strings&sourcelocale=en-US&locale=da&search_type=strings

**Comment by jakobkappel** [comment]
Ja, hvad f... har jeg lavet der? Godt at du fangede dén med "senester" også!
