### ISSUE TITLE
"Denne mailadresse optrådte ikke i datalækken { $breachName }." > "Denne mailadresse optrådte ikke i { $breachName }-datalækken ." ?

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#937]
Det ser lidt sært ud: 

![billede](https://user-images.githubusercontent.com/3586612/114317332-da088580-9b07-11eb-9d7c-94bc80443c0a.png)

Datalækken hedder jo ikke "Facebook". 

Er det ikke bedre med

![billede](https://user-images.githubusercontent.com/3586612/114317368-0e7c4180-9b08-11eb-91d3-d7cc536b028e.png)

?

**Comment by Joergen** [comment]
Jeg ved ikke rigtigt.
Fandt tre strenge, der har lignende format:
https://pontoon.mozilla.org/da/firefox-monitor-website/all-resources/?string=198819
https://pontoon.mozilla.org/da/firefox-monitor-website/all-resources/?string=198850
https://pontoon.mozilla.org/da/firefox-monitor-website/all-resources/?string=198808

**Comment by Joergen** [comment]
Jeg er ved at gennemgå forslag til Firefox Monitor. Jeg kan godt se, at det er bedre med dit forslag.
@jakobkappel retter du?

**Comment by jakobkappel** [comment]
@Joergen, jeps - og så tager jeg lige de sidste strenge også.

**Comment by jakobkappel** [comment]
#938
