### ISSUE TITLE
[KORREKTUR]: Firefox Monitor

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#938]
https://pontoon.mozilla.org/da/firefox-monitor-website/all-resources/?status=unreviewed&string=213213

**Comment by Joergen** [comment]
En rettelse og et ændringsforslag. https://pontoon.mozilla.org/da/firefox-monitor-website/all-resources/?status=unreviewed&string=206070
"password manager" er andre steder oversat med "program til håndtering af adgangskoder".

**Comment by jakobkappel** [comment]
Tak :) Godt gået at jeg lige fik "oversat" 'phone number' med 'mailadresse' (>_<)
