### ISSUE TITLE
[KORREKTUR]: Strenge til Firefox til iOS (Deadline: 28. april)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#940]
https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed&string=223170

**Comment by Joergen** [comment]
https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=unreviewed&string=223189

Ændringsforslag til to strenge: Fjernet apostrof fra "Kopier", så den matcher andre lignende strenge.

**Comment by jakobkappel** [comment]
Tak for hurtig hjælp, @Joergen. Sikkerkopier... ಠ_ಠ
