### ISSUE TITLE
Opret issue på Bugzilla ift. for lang streng til iOS

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#941]
![billede](https://user-images.githubusercontent.com/3586612/116787875-f2d0df00-aaa6-11eb-8b2b-fc8676859bbe.png)

`Firefox blokerer sporings-teknologier på tværs af websteder, sporing via sociale medier, cryptominers, fingerprinters og sporings-indhold.`

Jeg har ikke nogle gode bud lige nu, men det kan jo være, at de dukker op lige pludselig :)

**Comment by Joergen** [comment]
Der er mange sprog, der har længere strenge end den danske. Måske er det en opgave for udviklerne at finde en løsning.
https://transvision.mozfr.org/string/?entity=firefox_ios/firefox-ios.xliff:146fdad5ffe925ff4c6248a2f7d16443&repo=firefox_ios

**Comment by jakobkappel** [comment]
Nå, det ser ud til, at de primært bruger Github nu - så jeg har oprettet der: https://github.com/mozilla-mobile/firefox-ios/issues/8624
