### ISSUE TITLE
[KORREKTUR]: Donate - Mozilla content + Donate - Thunderbird content + Donate website - UI

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#943]
https://pontoon.mozilla.org/da/donate-mozilla-content/templates/pages/mozilla-donate/help.pot/?string=223713
https://pontoon.mozilla.org/da/donate-mozilla-content/templates/pages/mozilla-donate/faq.pot/?status=unreviewed&string=224101
https://pontoon.mozilla.org/da/donate-thunderbird-content/templates/pages/mozilla-donate/help.pot/?status=unreviewed&string=223347
https://pontoon.mozilla.org/da/mozilla-donate-website/LC_MESSAGES/django.po/?status=unreviewed&string=223716

https://give.thunderbird.net/da/help/

**Comment by jakobkappel** [comment]
Hov, undskyld - den hér var druknet i min indbakke. 

Jeg har forslag til nogle små-rettelser, ellers ser alt godt ud. 

https://pontoon.mozilla.org/da/donate-mozilla-content/templates/pages/mozilla-donate/faq.pot/?status=unreviewed&string=224101
https://pontoon.mozilla.org/da/mozilla-donate-website/LC_MESSAGES/django.po/?status=unreviewed&string=223716
