### ISSUE TITLE
KORREKTUR: Firefox (Deadline: 23/5)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#944]
@Joergen, jeg har godkendt de fleste af dine strenge og har lavet nogle få små-rettelser. 

Der er et enkelt af dine forslag, jeg er i tvivl om: 
"Account disconnected" - "Forbindelsen til kontoen er afbrudt"> "Ingen forbindelse til kontoen" _eller_ "Forbindelsen til kontoen blev afbrudt"?

Og så har jeg lavet forslag til de manglende strenge (de har vist haft gang i de lange cigaretter derovre i Californien, da de fandt på nogle af strengene ;) 

https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=223414

Men jeg kan se, at du har siddet og godkendt dem nogenlunde sideløbende med at jeg har lavet forslagene. Så jeg åbner bare issuet hér, sådan at vi ikke overser noget :)

**Comment by Joergen** [comment]
"Account disconnected" - "Forbindelsen til kontoen er afbrudt". De har bare ændret den engelske streng fra "Account **D**isconnected" til "Account **d**isconnected".
Used as the FxA toolbar menu item title when the user needs to reconnect their account.
https://bug1700993.bmoattachments.org/attachment.cgi?id=9211543

Den ene af de to manglende strenge forstår jeg ikke: https://pontoon.mozilla.org/da/firefox/all-resources/?status=missing&string=223414

Tilføjet senere: Jeg har lavet et ændringsforslag, så strengen ligner andre lignende strenge. https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=223560

**Comment by jakobkappel** [comment]
> "Account disconnected" - "Forbindelsen til kontoen er afbrudt". De har bare ændret den engelske streng fra "Account Disconnected" til "Account disconnected".
> Used as the FxA toolbar menu item title when the user needs to reconnect their account.
> https://bug1700993.bmoattachments.org/attachment.cgi?id=9211543

Ah, det havde jeg overset. Jeg har godkendt dit forslag.

> Den ene af de to manglende strenge forstår jeg ikke: https://pontoon.mozilla.org/da/firefox/all-resources/?status=missing&string=223414

Jeg kan heller ikke rigtigt følge med hér. Det virker sjusket skrevet - der er jo ikke noget subjekt i sætningen. Og hvad skulle det betyde, at Firefox (må det vel være) "neatly contains information"?

> Tilføjet senere: Jeg har lavet et ændringsforslag, så strengen ligner andre lignende strenge. https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=223560

Nå ja, det er sådan, de plejer at se ud. Jeg har gemt dit forslag

**Comment by Joergen** [comment]
Disse to strenge hænger sammen
upgrade-dialog-new-item-**tabs**-title = Modern tabs
upgrade-dialog-new-item-**tabs**-description = Neatly contain information, supporting focus and flexible movement.

![neatly](https://user-images.githubusercontent.com/3466269/119260099-8cd10680-bbd1-11eb-9d5d-58b8f7f22e76.png)

**Comment by jakobkappel** [comment]
Ok, så giver det bedre mening.

Nyt forslag: 
https://pontoon.mozilla.org/da/firefox/all-resources/?search=neatly&string=223216
