### ISSUE TITLE
Notifications oversat med "meddelelser"

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#948]
"Notifications" i Firefox er normalt oversat med "Beskeder". Men "Allow %S to send notifications?" er oversat med "Giv %S lov til at sende meddelelser?" Det skal være "Giv %S lov til at sende beskeder?"
https://pontoon.mozilla.org/da/firefox/browser/chrome/browser/browser.properties/?search=Allow&string=220805

**Comment by jakobkappel** [comment]
Godt fanget, @Joergen! 

Tror du ikke, at de to øverste på https://transvision.mozfr.org/?recherche=meddelelser&repo=gecko_strings&sourcelocale=en-US&locale=da&search_type=strings skal være "beskeder" også?

**Comment by Joergen** [comment]
Nej.
"Vis mig ikke meddelelser som denne igen" vises, når Firefox har forhindret et socialt netværk i at spore dig på en side. (Doorhanger). Den næste "Giv %S lov til at sende meddelelser?" er den, der lige er blevet rettet. De resterende strenge med "meddelelser" på Transvision hører ikke til Firefox.
