### ISSUE TITLE
Korrektur: Thunderbird (stram deadline!)

### ISSUE THREAD

**Issue by Pokersut** [MozillaDanmark/mozilla-dk#953]
Så er der en ordentlig stak strenge klar til korrektur (569!) - og desværre med en ret stram deadline på søndag, så vidt vi ved:
https://pontoon.mozilla.org/da/thunderbird/all-resources/?status=unreviewed

Jeg har lavet forslag til alle strengene, på nær en enkelt: https://pontoon.mozilla.org/da/thunderbird/all-resources/?status=missing&string=224299. Jeg har skrevet og efterspurgt noget kontekst, men ikke hørt fra dem endnu - så hvis nogen af jer har et bud på, hvad "space" er, så fyr endelig løs!

Mikkel

**Comment by Joergen** [comment]
Jeg har gennemgået strengene, lavet nogle smårettelser og godkendt.
Jeg har lavet et forslag til https://pontoon.mozilla.org/da/thunderbird/all-resources/?status=unreviewed&string=224299
https://element.io/blog/spaces-the-next-frontier/ https://matrix.org/blog/2021/05/17/the-matrix-space-beta

**Comment by Joergen** [comment]
Dette issue skulle ikke være lukket endnu!

**Comment by Pokersut** [comment]
Jeg er stadig ikke sikker på, hvad et "space" er, men lad os bare beholde den engelske betegnelse :-) Tak for korrektur, Jørgen! 

Jeg må i øvrigt (med nogen skam - jeg er trods alt sproglærer!) indrømme, at kvaliteten af de foreslåede Google-oversættelser på Pontoon efterhånden er så god, at de i langt de fleste tilfælde kan accepteres uden yderligere redigering - og det sparer faktisk en del tid!
