### ISSUE TITLE
Bug 1717416 Error in translation of "Discard" button in about:logins

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#954]
Jeg har godkendt de forslag, jeg lavede til Bug 1717416 og lukket buggen, da der er deadline.
https://pontoon.mozilla.org/da/firefox/browser/browser/aboutLogins.ftl/?search=confirm-discard&string=200878
https://bugzilla.mozilla.org/show_bug.cgi?id=1717416
@jakobkappel du kan selvfølgelig ændre strengene, hvis du har bedre forslag.

**Comment by jakobkappel** [comment]
Jeg synes, at det er en fin løsning :)
