### ISSUE TITLE
[KORREKTUR]: Firefox til Android - Deadline 12 juli.

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#956]
19 strenge
https://pontoon.mozilla.org/da/firefox-for-android/all-resources/?status=unreviewed&string=224572

Deadline 12 juli.

**Comment by Pokersut** [comment]
Alle godkendt pånær en enkelt, hvor jeg har foreslået en alternativ præposition - kan ikke helt gennemskue konteksten, så måske er den oprindelige oversættelse bedst.

**Comment by Joergen** [comment]
Vi har oversat lignende strenge med "Søg efter logins" både i Firefox til Android og Firefox til computer.
Jeg kan ikke finde strengen i selve produktet, måske er funktionen ikke implementeret endnu. Eneste kontekst er kommentaren.
Jeg beholder den oprindelige oversættelse for nu. Tak @Pokersut
