### ISSUE TITLE
[KORREKTUR]: Firefox til Android

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#968]
21 strenge: https://pontoon.mozilla.org/da/firefox-for-android/mozilla-mobile/fenix/app/src/main/res/values/strings.xml/?status=unreviewed&string=228800

**Comment by Pokersut** [comment]
Har lavet er par alternative forslag. Resten godkendt. 

Hvordan har I det med den bestemte form af "app" - jeg synes, det ser pænest ud med apostrof ("app'en"), men måske er det blevet så almindeligt et ord, at "appen" fungerer bedre?

**Comment by Joergen** [comment]
Ifølge retskrivningsordbogen er det ok at bruge "appen". https://dsn.dk/soeg/?soegeord=app
Vi har brugt "app'en" en enkelt gang: https://pontoon.mozilla.org/da/all-projects/all-resources/?search=app%27en&string=201765
Er det dig @Pokersut , der har escaped apostrofferne? https://pontoon.mozilla.org/da/firefox-for-android/mozilla-mobile/fenix/app/src/main/res/values/strings.xml/?status=unreviewed&string=231018

**Comment by Pokersut** [comment]
Ok. så lad os beholde "appen". 

Og ja, det er mig, der har escapet apostrofferne, for det sagde Pontoon, at man skulle! Mindes ikke, jeg har gjort det før ...

**Comment by Joergen** [comment]
Det afhænger nok af filtyperne. Jeg kan ikke se et problem her, men måske reagerer Pontoon automatisk, hvis den ser filen som en XML-fil.  https://github.com/mozilla-l10n/android-l10n/blob/master/mozilla-mobile/fenix/app/src/main/res/values-da/strings.xml
Det er også muligt, at Mozilla escaper tegn i nogle filer. Jeg kan huske, at der var et problem med den danske og svenske oversættelse af nogle strenge med " i Firefox. Problemet blev løst, uden at vi behøvede at gøre noget.
