### ISSUE TITLE
[KORREKTUR]: Strenge til Firefox (Deadline: 26/9)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#971]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=231472

Jeg er ikke glad for løsningen ift. "Tab Unloadning", men har desværre ikke bedre forslag.

**Comment by Joergen** [comment]
Den er ikke nem. Loading = Indlæsning. Unloading = Udlæsning. Men det giver vel ikke mere mening. Strengene med "Tab Unloadning" bliver nok ikke blandt de mest sete.

Jeg har gennemgået og godkendt forslagene.
