### ISSUE TITLE
[OVERSÆTTELSE][KORREKTUR]: Firefox til iOS - Deadline 21. oktober

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#975]
37 strenge. Jeg har lavet forslag til de 36: https://pontoon.mozilla.org/da/firefox-for-ios/firefox-ios.xliff/?status=missing&string=233048
Nogle af forslagene er er fra lignende strenge (godkendte og forslag) i Firefox til Android.

**Comment by jakobkappel** [comment]
Det ser godt ud, @Joergen - jeg har gemt alle strenge. 

Og så har jeg lavet et forslag til den manglende streng: https://pontoon.mozilla.org/da/firefox-for-ios/firefox-ios.xliff/?status=unreviewed&string=233046

Alternativer kunne være: 

- Mere ryddelige fanebladsgrupper
- Bedre overblik med fanebladsgrupper

Men de bliver jo så nogle længere.

**Comment by Joergen** [comment]
Godkendt
