### ISSUE TITLE
Skrivebords-bogmærker

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#976]
Vi har oversat "Desktop Bookmarks" med "Skrivebords-bogmærker" i Firefox til Android. En Mikkel har på Pontoon foreslået, at vi ændrer det til "Desktop-bogmærker". Jeg fik afvist forslaget ved en fejl. Men han har en pointe: https://pontoon.mozilla.org/da/firefox-for-android/mozilla-mobile/fenix/app/src/main/res/values/strings.xml/?status=unreviewed&search=Desktop+Bookmarks&string=199505 (Se kommentarer). Jeg laver også et forslag til strengen.

**Comment by jakobkappel** [comment]
Ja, det har han absolut ret i. Oversættelsen er vist lavet på automatpilot, da strengen først dukkede op. 

Det er forresten sært, at Mozilla holder fast i "Desktop" for at oprette skellet mellem computer-mobildims. 

Er der plads til at gøre det endnu mere tydeligt, hvad der er på spil med "Bogmærker fra din computer"?

**Comment by jakobkappel** [comment]
Jeg prøver lige at skrive en mail til ham Mikkel. Det kan jo være, at han har nogle andre gode forslag :)

**Comment by Joergen** [comment]
Jeg har skrevet til ham og takket for forslaget.

**Comment by jakobkappel** [comment]
Jamen, så er han i hvert fald takket eftertrykkeligt.

**Comment by Joergen** [comment]
Jeg tror, der er plads til "Bogmærker fra din computer". Så det oversætter jeg det med.
