### ISSUE TITLE
[KORREKTUR]: Nye strenge til Firefox [Deadline: 24. oktober ]

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#977]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=232948

---

Jeg nåede frem til, at "Colorways" fungerer bedst som "Farvekombinationer", selvom det nok ikke er lige så spændende et ord som originalen sikkert er tænkt som. Men ordbogens "Farvesætning" og tilsvarende obskure begreber synes jeg ikke giver så meget mening.

Der er en manual til at teste den nye funktionalitet her: https://docs.google.com/document/d/e/2PACX-1vT1UexRCb9Sb_GRuYxw6Tyrnwg6TVTWHvx4XA2y6ev5vVoffn9_X0ptf8bjqaCoG3ustQyjAUdg65zE/pub#h.2xllpd7w357t

**Comment by Joergen** [comment]
@jakobkappel Jeg har lavet ændringsforslag til tre af strengene: https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=232948
Jeg tjekker normalt diverse access keys. Der er en i Places jeg ikke kunne finde, men har godkendt. Måske falder jeg over den en dag.  https://pontoon.mozilla.org/da/firefox/all-resources/?time=202110191950-202110201950&string=232928

**Comment by jakobkappel** [comment]
Strengen erstatter "Vis i hentningsmappe" i menuen ved højreklik på hentede filer, så det er nok bedre med 'v': 

![Skærmbillede fra 2021-10-21 12-20-47](https://user-images.githubusercontent.com/3586612/138259550-36f49175-fd6f-4279-8b4f-33b0b3a72ef2.png)

Skulle "Fjern fra historik" måske have 'f' og "Gå til..." 'g'?

**Comment by Joergen** [comment]
Jeg forstår ikke, hvorfor den streng er i filen "places.ftl". De andre strenge fra skærmbilledet er i "downloads.ftl". Derfor kunne jeg ikke finde strengen i vinduet Arkiv.
Jeg ændrer de andre access keys til dine forslag.

**Comment by Joergen** [comment]
Det lykkedes mig at finde strengen i vinduet Arkiv.

**Comment by jakobkappel** [comment]
> Det lykkedes mig at finde strengen i vinduet Arkiv.

Det kan jeg så ikke finde ud af - hvor har den gemt sig?

Jeg lukker lige, så det ikke ser ud til, at jeg har overskredet deadline ;)

**Comment by Joergen** [comment]
Åbn vinduet Arkiv. Klik på Filhentninger til venstre i vinduet Arkiv. Højreklik på en filhentning til højre i vinduet.
Strengen er på engelsk. Det er den også i panelet Filhentninger. Der er sikkert en fejl.
https://bugzilla.mozilla.org/show_bug.cgi?id=469441

**Comment by jakobkappel** [comment]
Ja, dér var den. Der er også dukket "Always open similar files" op, men den er ikke kommet på Pontoon endnu. Det var ellers noget af en gammel traver, den bug :D
