### ISSUE TITLE
[KORREKTUR]: Mozilla.org/en/banners/firefox-app-store.ftl

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#980]
Fem strenge: https://pontoon.mozilla.org/da/mozillaorg/en/banners/firefox-app-store.ftl/?status=unreviewed&string=231302
Live på Android eller iOS: https://www-dev.allizom.org/firefox/ Vælg Engelsk nederst på siden for at se strengene.

**Comment by jakobkappel** [comment]
Jeg synes ikke, at "Privatlivs-browseren" fungerer så godt - og jeg er heller ikke sikker på, at der er plads til det: 

<img width="375" alt="Skærmbillede 2021-11-08 kl  21 30 38" src="https://user-images.githubusercontent.com/3586612/140813884-f65c5be9-9064-4ff0-9143-dcd22f2fe1b8.png">

Den anonyme browser
Beskyt dit privatliv

**Comment by Joergen** [comment]
Jeg er heller ikke begejstret for strengen, men kunne ikke komme på noget bedre.
Sådan ser det ud på en Android-enhed:
![Android](https://user-images.githubusercontent.com/3466269/140819614-791e945f-413b-46e7-8db0-c38055c47fe0.png)

Er følgende to forslag? "Den anonyme browser" "Beskyt dit privatliv"

**Comment by jakobkappel** [comment]
Hov, ja - det skulle jeg have skrevet. 

Det er svært. Jeg kan se, at nogle af sprogene har "Den private browser". Det kunne måske også gå, selvom det på dansk strengt taget er lidt vrøvlet. 

Måske "Den fortrolige browser"

Jeg har det som om der er et eller andet godt ord, vi kunne bruge. Men komme i tanke om det kan jeg så ikke finde ud af lige nu. Det kan være, at det dukker op :)

**Comment by Joergen** [comment]
Jag lader issuet være åbent nogle dage. Hvis der ikke kommer bedre forslag, bruger jeg "Beskyt dit privatliv".

**Comment by Pokersut** [comment]
Den er svær. En hurtig brainstorm:

- Sikker surf
- Surf sikkert
- Anonym på nettet
- Anonymt på nettet
- Privat og sikker
- Privatliv og sikkerhed

**Comment by Joergen** [comment]
Tak for forslagene. Jeg valgte "Privat og sikker".
