### ISSUE TITLE
[OVERSÆTTELSE][KORREKTUR]: Focus til iOS - Deadline 15 november

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#981]
@jakobkappel Jeg har godkendt de fleste af dine forslag. Jeg har lavet ændringsforslag og lavet forslag til de manglende strenge - undtagen til to strenge, der mangler oversættelse.
https://pontoon.mozilla.org/da/focus-for-ios/focus-ios.xliff/?status=missing&string=160999

**Comment by jakobkappel** [comment]
Hov, den hér var røget ned mellem gulvbrædderne. 

@Joergen, jeg har gennemgået dine forslag, tilføjet et par nye og har lavet forslag til de manglende strenge: 

https://pontoon.mozilla.org/da/focus-for-ios/focus-ios.xliff/?status=unreviewed&string=230938
