### ISSUE TITLE
[KORREKTUR]: Nye strenge til Firefox (Deadline: 28. november)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#985]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=235705

Det er lidt af en nødløsning med oversættelsen af "Total Cookie Protection", så kom gerne med bedre forslag :)

**Comment by Joergen** [comment]
Jeg har lavet ændringsforslag: https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=233952
Der er også nye forslag til ældre strenge med "Picture-in-Picture", så de bl.a harmonerer med dine seneste forslag. Toggle = Knappen. **B**illede-i-billede (stort begyndelsesbogstav og **e** sidst i ordet "billede".

**Comment by Joergen** [comment]
Første gang jeg så "Total Cookie Protection", tænkte jeg, at det var uklart, om der var tale om beskyttelse af cookies eller beskyttelse mod cookies. Jeg kan forstå, at det er op til oversætterne at levere oversættelser, der er fjerner evt. tvivl hos læseren.
Jeg har desværre ikke noget bedre bud på en oversættelse.

**Comment by jakobkappel** [comment]
Nej, det er svært. Men eftersom funktionen samler cookies fra hvert websted i en beholder af en slags, så fungerer det sådan set fint med begge fortolkninger.
