### ISSUE TITLE
[KORREKTUR]: Nye strenge til Focus til Android (Deadline: 6/12)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#986]
https://pontoon.mozilla.org/da/focus-for-android/all-resources/?status=unreviewed&string=228772

**Comment by Joergen** [comment]
Lavet to ændringsforslag og godkendt resten.
https://pontoon.mozilla.org/da/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?status=unreviewed&string=230887

**Comment by jakobkappel** [comment]
Perfekt - tak for hjælpen
