### ISSUE TITLE
The character encoding needs to be declared in the Content-Type HTTP header, using a meta tag, or using a byte order mark.

### ISSUE THREAD

**Issue by Joergen** [MozillaDanmark/mozilla-dk#989]
@jakobkappel
Der er flere strenge, der indeholder følgende sætning eller en der er næsten magen til. The character encoding needs to be declared in the Content-Type HTTP header, using a meta tag, or using a byte order mark. I nogle strenge har du fået "using a meta tag" med, selvom det ikke er i den engelske tekst. Men mit største problem med at læse korrektur er, at jeg synes der mangler et komma. Eller er der noget andet galt med oversættelserne. 
Her er en sætning, der går igen i flere af strengene:
The character encoding needs to be declared in the Content-Type HTTP header, using a meta tag, or using a byte order mark.
Tegnkodningen skal deklareres i Content-Type-HTTP-headeren (mangler der et komma her) ved at bruge et meta-tage eller et byte order mark.

https://pontoon.mozilla.org/da/firefox/dom/chrome/layout/htmlparser.properties/?search=or+using+a+byte+order+mark&string=236840

**Comment by Joergen** [comment]
https://www.w3.org/International/questions/qa-html-encoding-declarations

**Comment by jakobkappel** [comment]
@Joergen Ja, de er ikke nemme. Og det bliver selvølgelig ikke bedre af, at jeg er kommet til at kopiere for meget ind fra tidligere forslag. 

Kommasætningen er dog god nok, så måske skal de lange sætninger brydes op i flere: 

> Tegnkodningen skal deklareres i Content-Type-HTTP-headeren ved at bruge et meta-tag eller et byte order mark.

->

> Tegnkodningen skal deklareres i Content-Type-HTTP-headeren. Det kan du gøre ved at bruge et meta-tag eller et byte order mark.

eller

> Brug et meta-tag eller et byte order marked til at deklarere tegnkodningen i Content-Type-HTTP-headeren

I det sidste tilfælde forsvinder "needs to be" så godt nok.

Jeg spekulerer over det og ser, om jeg kan finde på noget bedre :)

**Comment by Joergen** [comment]
Jeg bliver ved med at læse den engelske tekst, som om der er tre forskellige måder at deklarere tegnkodningen på.
`<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>`
`<meta charset="utf-8"/>`
`BOM`

**Comment by jakobkappel** [comment]
> Jeg bliver ved med at læse den engelske tekst, som om der er tre forskellige måder at deklarere tegnkodningen på. `<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>` `<meta charset="utf-8"/>` `BOM`

Det er der nemlig. Men det fik jeg lavet rod i, da jeg lavede de første forslag. Jeg har lavet nogle nye (og får lige styr på de sidste strenge ved samme lejlighed).

**Comment by jakobkappel** [comment]
^ #992
