### ISSUE TITLE
[KORREKTUR]: Firefox (Deadline: 9. januar)

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#992]
https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=236672

**Comment by Joergen** [comment]
Site Permissions 
Ny type tilføjelse. Se Franciscos notification: https://pontoon.mozilla.org/notifications/

**Comment by jakobkappel** [comment]
@Joergen - så er der forslag til de sidste strenge: https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=237290

**Comment by Joergen** [comment]
"Site Permissions" er oversat med "Websteds-indstillinger" i Firefox til Android. Men skal vel oversættes med noget andet her. "Websteds-tilladelser"?
https://transvision.mozfr.org/?recherche=Site+Permissions&repo=gecko_strings&sourcelocale=en-US&locale=da&search_type=strings

**Comment by Joergen** [comment]
Jeg har også lavet nogle ændringsforslag + skrevet en kommentar til en af strengene.

**Comment by jakobkappel** [comment]
> Jeg har også lavet nogle ændringsforslag + skrevet en kommentar til en af strengene.

Jeg er enig i din kommentar. Og svarer lige hér også: Hvad med "...<link>vores suppport</link>" eller måske "support-websted"?

**Comment by Joergen** [comment]
Så er vi nede på to forslag: https://pontoon.mozilla.org/da/firefox/all-resources/?status=unreviewed&string=236672

**Comment by jakobkappel** [comment]
Og så er de godkendt :)
