### ISSUE TITLE
Forkert oversættelse i Pocket-menu, når man ikke er logget ind

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#993]
Teksten på den nederst knap er forkert.

![Skærmbillede fra 2022-01-04 10-36-15](https://user-images.githubusercontent.com/3586612/148040152-58f098e0-9bb7-458c-9872-4df07f5c5ec7.png)

Tilmeld med mailadresse?

**Comment by jakobkappel** [comment]
https://pontoon.mozilla.org/da/firefox/browser/browser/aboutPocket.ftl/?search=pocket-panel-signup-signup-email&string=224259

**Comment by Joergen** [comment]
Rettet
