### ISSUE TITLE
[KORREKTUR]: Side om Mozillas historie

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#995]
https://pontoon.mozilla.org/da/mozillaorg/en/mozorg/about/history.ftl/?status=unreviewed&string=219622

https://www.mozilla.org/en-US/about/history/

**Comment by Joergen** [comment]
Jeg har lavet ændringsforslag: https://pontoon.mozilla.org/da/mozillaorg/en/mozorg/about/history.ftl/?status=unreviewed&string=219606
Stage: https://www-dev.allizom.org/da/about/history/

**Comment by jakobkappel** [comment]
Det var også nogle gode forslag - tak for hjælpen. 

Jeg har lavet et nyt forslag til strengen med "more than any one company". For jeg kan ikke få nogle af løsningerne med "større end" til at give mening: Enten skal det vel være a. "større end" >den virksomhed, Mozilla havde været hidtil< (og hvorfor så ikke bare skrive dét?), eller 2. større end >virksomheder kan være, sådan generelt< (hvilket selvfølgelig bliver noget vrøvl). 

Så "mere end (underforstået: 'blot/bare') en virksomhed" synes jeg giver bedre mening.

**Comment by jakobkappel** [comment]
https://pontoon.mozilla.org/da/mozillaorg/en/mozorg/about/history.ftl/?status=unreviewed&string=219607
