### ISSUE TITLE
[KORREKTUR]: mozorg/fundraising

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#996]
https://pontoon.mozilla.org/da/mozillaorg/en/banners/fundraising.ftl/?status=unreviewed&string=235262

- Jeg kan ikke finde ud af, hvor strengene vises henne.
- Strengen "We’re proudly nonprofit..." er oversat meget frit. Jeg synes ikke, at metaforen med internettet som 'healthy' fungerer så godt på dansk.
- Et par af strengene er håbløst forældede (medmindre de beslutter at genbruge dem næste jul). Men så er der da én grøn statuslinje til ;)

**Comment by Joergen** [comment]
Jeg tror, at strengene vises i en "banner" som den, du ser på denne side: https://www-dev.allizom.org/da/
Indholdet kan varieres alt efter, om der er en højtid eller lignende undervejs.
