### ISSUE TITLE
[KORREKTUR] Terminology

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#998]
https://pontoon.mozilla.org/da/terminology/common/?status=unreviewed&string=212307

<del>Hovedparten af strengene er [klar til korrektur](https://pontoon.mozilla.org/da/terminology/all-resources/?status=unreviewed&string=212218) - med undtagelse af nedenstående, som vi skal have fundet en løsning på.

<del>1. Nogle af strengene peger på to forskellige begreber, der tilfældigvis på engelsk kan beskrives med samme ord: 

<del>`""Sign". Verb. To issue a digital certificate as verification of a website's identity; or, to enter user credentials to access a system. E.g. Sign in to sync your tabs, bookmarks, logins.`

<del>`"Appear". Verb. 1. to come into sight; become visible or noticeable 2. to seem or give the impression of being. E.g. Choose the alternative search engines that appear below the address bar; the add-on downloaded from this site could not be installed because it appears to be corrupt.`

<del>Jeg hælder til at prøve på at få lavet de to strenge om. Alternativt skal vi høre, om det er i orden at angive to ord i oversættelsen (fx "Signere, logge ind"

<del>2. "Unresponsive" som adjektiv ("Not reacting or responding. E.g. A script from the extension is running on this page, and making it unresponsive.") Jeg kan ikke finde et modsvarende dansk ord. Vi plejer at skrive om med "...svarer ikke". 
</del>

**Comment by Joergen** [comment]
Jeg kan se, at den norske Terminology bruger flere kommaseparerede ord eller sætninger.
Se eksempel med "appear" her: https://pontoon.mozilla.org/nb-NO/all-projects/all-resources/?string=159661

**Comment by jakobkappel** [comment]
> Jeg kan se, at den norske Terminology bruger flere kommaseparerede ord eller sætninger. Se eksempel med "appear" her: https://pontoon.mozilla.org/nb-NO/all-projects/all-resources/?string=159661

Så synes jeg bare, at vi skal gøre det samme. Jeg laver forslag til de to strenge.

**Comment by Joergen** [comment]
Jeg har lavet ændringsforslag og tilføjelser.
https://pontoon.mozilla.org/da/terminology/common/?status=missing&string=212224

**Comment by jakobkappel** [comment]
Det var nogle gode forslag, @Joergen :) 

Jeg har gemt alle, bortset fra to:

https://pontoon.mozilla.org/da/terminology/common/?status=missing&string=212251

Den med "compact" er sær. Det er i hvert fald ikke nogen oplagt kandidat til en ordliste...

**Comment by Joergen** [comment]
Jeg tror ikke det vises nogen steder.
