### ISSUE TITLE
[KORREKTUR]: Et par strenge til mozilla.org

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#999]
https://pontoon.mozilla.org/da/mozillaorg/en/mozorg/home-mr2-promo.ftl/?status=missing&string=234083
https://pontoon.mozilla.org/da/mozillaorg/en/navigation.ftl/?status=unreviewed&string=214668

**Comment by Joergen** [comment]
Dem godkendte jeg i går!

**Comment by jakobkappel** [comment]
For saden da... Det kunne jeg da godt lige have tjekket. Jeg var midt i at oprette issuet i går, men blev aldrig færdig...
